### ISSUE TITLE
VSCode Plugin: allow different tag names other than gql

### ISSUE THREAD

**Issue by dontsave** [apollographql/apollo-tooling#1003]
Firstly, thanks for your work here. After spending a frustrating few hours with a number of competing VSCode graphql plugins, Apollo's was the only one to work with minimal hassle right out of the box. That's great!

My only request is to allow the plugin to parse tagged template literals other than `gql`. I currently have a number of projects that use gatsbyjs which insists on using a `graphql` tag. My workaround for this is to import graphql aliased as gql, but ideally this is a feature the plugin should be able to handle. I tried updating the `tagName` option in apollo.config, but it didn't seem to work.

Thanks!

**Comment by janicduplessis** [comment]
I was able to get it working with gatsby using this config

apollo.config.js
```js
module.exports = {
  client: {
    includes: [
      'src/**',
      'node_modules/gatsby-transformer-sharp/fragments.js',
    ],
    tagName: 'graphql',
    service: {
      name: 'website',
      url: 'http://localhost:8000/___graphql',
    },
  },
};
```

Make sure that the gatsby dev server is running also.

**Comment by dontsave** [comment]
Ah! Thanks! My issue was that I was putting `tagName` in service as opposed to client. That's a great tip on including the sharp fragments as well
