### ISSUE TITLE
Generating Base Types and Using gql for Source of Types

### ISSUE THREAD

**Issue by calben** [apollographql/apollo-tooling#1031]
Hey everyone,

If anybody has the time to help out a poor systems programmer out of his element, I'd appreciate it!

I have a Postgraphile server with a few types and a couple many to many associations between the types.
A test server is currently up at http://mytrackdb.calben.xyz/graphiql.

Postgraphile generates a remarkably clean `schema.gql` file, but I've also used the apollo cli to generate a `schema.json` through inspection.

My codegen command is:
```
    "graphql-gen": "apollo codegen:generate --localSchemaFile=graphql-schema.json --target=typescript --includes=src/**/*.ts --tagName=gql --addTypename --globalTypesFile=src/types/graphql-types.ts types"
```

I've created two files with a total of 4 queries, and as expected 4 files are created in types.
These files are perfect.
However, no types are generated for the "base" types in my database.
There is the `getTeamAndUnlinkedStudent_teamById` but not just a `team` that can be used as a base type for components and other bits of code.

Do I need to code my base types by hand?

After I have my base types, is there an idiomatic way to marshal or convert the results of a query into a partial or full representation of one of the base types?

Would it be possible to generate the types files based on the gql file produced by Postgraphile rather than the schema.json file produced by inspecting the server?
Would there be an advantage to using the graphql file?

Is there a better place to ask these questions?

Thanks and sorry for opening this up as an issue!

**Comment by calben** [comment]
I've found an alternative solution that seems to work well with Apollo React at https://graphql-code-generator.com
However, if these features are also available in Apollo Tooling, I'd love to know!

Thanks

**Comment by switchnollie** [comment]
Is there any possibility to the described with `apollo codegen` rather than [https://graphql-code-generator.com/]()? The issue was closed without any hints on how to do this with the tool itself.
