### ISSUE TITLE
Likely bug in extractGraphQLDocumentsFromJSTemplateLiterals

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/apollo-tooling#1050]
See: https://github.com/apollographql/apollo-tooling/blob/c4ccd53e70a806a714fdada7312ea63b99f45977/packages/apollo-language-server/src/document.ts#L88

There's probably an issue with the magical +4 here, it seems to be assuming the length of gql`, but we support custom tagNames in the function.

A simple breaking test + fix would be a very simple approach to demonstrating this bug and resolving.

Thanks @glasser for reporting!

**Comment by rlarcher** [comment]
Sure, I have a PR for this here with a simple test https://github.com/apollographql/apollo-tooling/pull/1326

**Comment by trevor-scheer** [comment]
Closed in #1326, thanks @rlarcher!
