### ISSUE TITLE
Add support for `.gql` files in `apollo-language-server`

### ISSUE THREAD

**Issue by ksonnad** [apollographql/apollo-tooling#1128]
The current situation in `vscode-apollo` is very confusing. The extension will syntax-highlight `.gql` files but the schema-based features don't work. I would expect the features of the extension to work consistently across every file type -- if it's syntax-highlighted, the schema validation should also work.

There's a workaround, you can add `.gql` to the `includes` configuration of `apollo.config.js`. But the default values for that option aren't documented anywhere.

Can `.gql` files just be added to the language-server's default `includes` list?

**Comment by JakeDawkins** [comment]
Yeah, @ksonnad that sounds reasonable! If you (or someone) wants to open a PR for that, I could give it a look!

**Comment by ksonnad** [comment]
🙌
