### ISSUE TITLE
apollo service:push fails because it makes assumptions about the environment

### ISSUE THREAD

**Issue by ThomWright** [apollographql/apollo-tooling#1132]
**Intended outcome:**

Successful `apollo service:push`

**Actual outcome:**

Failed `apollo service:push`

```
Error: EISDIR: illegal operation on a directory, read
    at Object.loadConfig (/app/node_modules/apollo-language-server/lib/config/loadConfig.js:49:50)
```

**How to reproduce the issue:**

Create an empty directory called `.env` in the root of the project and run `apollo service:push`.

**Versions**

`apollo@2.6.2`
`apollo-language-server@1.5.4`

**Culprit**

The precise problem is that `apollo-language-server` checks for the existence of `.env`, and assumes that if it exists then it is a config file it can read. In this case it is a directory. In fact, it could be a directory or a completely irrelevant file.

In general the problem is that `apollo-language-server` tries to make guesses about the environment it's running in. I would much prefer to configure it with explicit arguments (to the CLI, which are passed to the `apollo-language-server` library). I would rather it didn't look at my files, or my environment variables.

I should be able to be free to do what I want with my environment without worrying about nested dependencies looking at it and breaking.

**Comment by JakeDawkins** [comment]
@ThomWright interesting... loading env variables from `.env` and similar files as well as the environment is a fairly common practice. Especially with CLI tools. I think the benefits outweigh the sacrifices pretty strongly for convenience and the ability to customize configuration in multiple ways for different dev environments/CI.

For those reasons, I don't think `remove .env files or env variables` is really an option at this point. Maybe we could improve the error messaging for this particular case? Or am I misunderstanding your suggestion?

**Comment by ThomWright** [comment]
Well, the simple fix is to not assume that `.env` is a file, and instead check if it's a directory.

**Comment by JakeDawkins** [comment]
Yeah, I think that's pretty reasonable :) regardless of what we do, we shouldn't be failing out if something's not what we expect
