### ISSUE TITLE
VSCode Plugin: Support for embedded string in PHP file

### ISSUE THREAD

**Issue by swashata** [apollographql/apollo-tooling#1155]
Hello,

Firstly thank you very much for this awesome extension. It works beautifully and saves a lot of time on client-side developments.

I do have a feature request. Before I come to that, here's a little about the backstory.

I develop WordPress plugins and currently in the process of developing a plugin where it will provide a graphql server. For that I am using [graphql-php](https://webonyx.github.io/graphql-php/getting-started/) which can create a Apollo compliant server written in PHP.

Now using the PHP server and `apollo.config.js`

```js
module.exports = {
	client: {
		service: {
			name: 'something.test',
			url: 'http://something.test/my-plug/graphql',
		},
	},
};
```

I can point apollo client to my GraphQL endpoint URL and it works fine in JavaScript/TypeScript files. I mean I am very thankful and just blown away that this extension can talk to my in-development graphql-server (not written with apollo-server, but graphql-php) and provide intellisense within my typescript files.

![awesome-apollo](https://user-images.githubusercontent.com/1623381/55275959-54944d00-5313-11e9-8d33-4d84707f941f.gif)

This is just awesome.

But for testing out the server, I do write integration tests in PHP where I do something like

```php
$mutation = <<<'GQL'
mutation CreateCategory($title: String!, $description: String!) {
	createCategory(data: {
		title: $title
		description: $description
	}) {
		id
		title
		description
	}
}
GQL;
for ( $i = 0; $i < 10; $i++ ) {
	self::executeGraphQLQuery(
		$mutation,
		[
			'title' => 'Category ' . $i,
			'description' => 'This category is created in ' . $i . ' iteration',
		]
	);
}
```

Now life would've been complete, if the string inside the PHP [newdoc](https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.nowdoc), i.e, the string after `$mutation = <<<'GQL'` and before `GQL;`

1. Syntax highlighted.
2. Optionally provide that same awesome language server feature.

Thank you very much for your consideration. I am a regular user of this plugin and if by any means I can help, please point me in the direction.

**Comment by trevor-scheer** [comment]
Hey @swashata, thanks for the great writeup. At this time, support for PHP is not something we'd be building ourselves, but we would definitely consider a PR for it!

I'll point to a previous PR that we merged recently that adds support for Ruby. If you're interested in implementing this, it would be much appreciated!

https://github.com/apollographql/apollo-tooling/pull/1304
