### ISSUE TITLE
[vscode plugin] autocomplete broken at v1.5.1

### ISSUE THREAD

**Issue by dontsave** [apollographql/apollo-tooling#1167]
Just moved back to a graphql project and noticed that apollo no longer autocompletes queries in .graphql files or in gql (or custom) tags. There is no error in the console. The plugin loads fine and appears to load the schema fine from remote.

reverting to version `1.5.0` seems to solve the issue. The issue is also present in `1.5.2`

Apollo config:
```
module.exports = {
  client: {
    includes: [
      'src/**',
      'node_modules/gatsby-transformer-sharp/fragments.js',
      ],
      tagName: 'graphql',
      service: {
        name: 'ds.local',
        url: 'http://localhost:8800/___graphql',
       },
    },
};
```

VSCode info:

```
Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

**Comment by ZenSoftware** [comment]
This seems to be a Windows specific issue.  Version 1.6.4 works fine on Linux, but not on Windows.  Reverting to 1.5.0 works on Windows.

**Comment by jtmthf** [comment]
Also having this same issue but with macOS. Here is my config file

```js
module.exports = {
  client: {
    includes: ['src/**', 'node_modules/gatsby-*/**/*.js'],
    tagName: 'graphql',
    service: {
      name: 'gatsby'
      url: 'http://localhost:8000/___graphql',
    },
  },
};

```

**Comment by dylanwulf** [comment]
I am also experiencing this issue, reverting back to 1.5.0 works for me. In my case, it seems that validation is also working incorrectly. It will validate the query once when VSCode starts up, but it will not re-validate when I change the query (unless I close and re-open VSCode)

**Comment by JakeDawkins** [comment]
Autocomplete while typing should be working on windows with the latest release of #1213. It does look like there's an issue with the `ctrl+space` autocomplete though, so I'll leave this issue open until I can figure out what's going on there!

**Comment by dylanwulf** [comment]
@JakeDawkins Looks like the problem with `ctrl+space` was fixed by #1361

**Comment by JakeDawkins** [comment]
@dylanwulf great! I don't have the time today to verify this, so I'll close this issue and if anyone disagrees, let me know :)

**Comment by dylanwulf** [comment]
@JakeDawkins I'm now using v1.10.0 of the vscode extension, and it seems the ctrl+space problem has returned.
