### ISSUE TITLE
Allow reusable fragments (js/ts)

### ISSUE THREAD

**Issue by pie6k** [apollographql/apollo-tooling#1181]
Use case: Being able to reuse fragments (by importing them) in many queries and still have types generated

Example:

Fragment:
```ts
export const UserBasicData = gql`
  fragment UserBasicData on User {
    id
    username
  }
`;
```

Later on, this fragment is imported in other queries
```ts
import { UserBasicData } from './UserBasicData'

const queryA = gql`
  ${UserBasicData}

  query QueryA {
    me {
      ...UserBasicData
    }
  }
`;

const queryB = gql`
  ${UserBasicData}

  query QueryA {
    findUser(id: 2) {
      ...UserBasicData
    }
  }
`;
```

It breaks because apollo is not able to resolve my import (which is fine)

At first - it looks like apollo-tooling would have to be aware of my importing system (eg. webpack/typescript) - but it doesn't:

It's aware of my fragment definition (and it is indeed generating proper types for it), so technically it is able to resolve fragment name to proper type.

It could require config like
```json
          "rules": {
            "KnownFragmentNames": "off",
            "NoUnusedFragments": "off"
          }
```

as it has 'to trust' me I know what I'm doing because it's not able to verify if my imports are working properly.

It would be very useful to use it this way as it'd allow me to have single source of truth about data shape inside many queries.

**Comment by conradreuter** [comment]
If you decide to work on this, it would also be cool if [fraql](https://github.com/smooth-code/fraql) worked out-of-the-box with that.

**Comment by webberwang** [comment]
I'm also seeing the benefits of not prefixing generated fragments with the parent's name.

Current:
```javascript
export interface RestaurantFragment {
  __typename: "Restaurant";
  menus: MenuFragment_restaurant | null;
}

export interface MenuFragment_restaurant {
  __typename: "Menu";
  name: string;
```

Proposed:
```javascript
export interface RestaurantFragment {
  __typename: "Restaurant";
  menus: MenuFragment_restaurant | null;
}

export interface MenuFragment {
  __typename: "Menu";
  name: string;
```

**Comment by pie6k** [comment]
I've switched to https://graphql-code-generator.com/docs/getting-started/ (I'm not author of it or related to it in any way) and it does support it exactly as described here

**Comment by trevor-scheer** [comment]
@pie6k, thanks for submitting an issue! I'm not sure I understand the ask here. 

My misunderstanding stems from these two statements:
>It breaks because apollo is not able to resolve my import (which is fine)
...which seems to be in conflict with this one:
>It's aware of my fragment definition (and it is indeed generating proper types for it)

If you can provide a small reproduction that highlights the incorrect behavior, that would be very helpful!
