### ISSUE TITLE
Feature request: Compress insignificant whitespace in queries when generating code

### ISSUE THREAD

**Issue by lilyball** [apollographql/apollo-tooling#1182]
When generating code, the resulting query objects include a string literal with the complete GraphQL query definition, including all of the whitespace. This makes it look rather ugly in the source, and also just seems completely unnecessary to send to the server.

Specifically I'm generating Swift code, though I'd assume this holds true for other languages as well.

It would be nice if `apollo client:codegen` would just replace all sequences of insignificant whitespace (i.e. whitespace not in strings) with a single space character. It looks like the codegen already strips out comments, so we don't have to worry about those, and without comments newlines have no significance either, so those can be included in the whitespace compression.

For example, given the following query:

```graphql
query Foo($name: String!) {
  user(login: $name) {
    id
    displayName
  }
}
```

`apollo client:codegen` produces the following definition:

```swift
public final class FooQuery: GraphQLQuery {
  public let operationDefinition =
    "query Foo($name: String!) {\n  user(login: $name) {\n    __typename\n    id\n    displayName\n  }\n}"
  …
}
```

What I'm asking for is to instead produce:

```swift
public final class FooQuery: GraphQLQuery {
  public let operationDefinition =
    "query Foo($name: String!) { user(login: $name) { __typename id displayName } }"
```

There's obviously a couple of spaces that could still be trimmed (e.g. between punctuation), but I'm not looking for the 100% optimal compression, just something that's readable and omits the large runs of obviously-irrelevant whitespace.

**Comment by JakeDawkins** [comment]
Yeah, I think this would still be a good thing to do. Either this or a multiline string

**Comment by david-coyle-sjc** [comment]
I'm seeing an issue here, where my iOS swift sources, pass through the literal `\n` in the query, it's not converted to an actual new line.  This causes the queries to fail, obviously.
I've even removed all the newlines from my .graphql query specs, and yet the codegen is adding them back in.

**Comment by designatednerd** [comment]
@david-coyle-sjc Can you take a look at PR #1441 - that adds support for a multiline string, which should stop that literal from being passed through.

**Comment by designatednerd** [comment]
@lilyball - are you still interested in an option for this? I moved to the multiline-string for readability, but from a standpoint of "Do we really need to send whitespace?", I *think* the answer is no. I could take a look at some kind of option to not send the whitespace, although that may be a bit.

**Comment by lilyball** [comment]
@designatednerd I'm still interested in this.

**Comment by designatednerd** [comment]
@lilyball Am I correct in assuming that it's only at the point of hitting the network where the removal of the whitespace matters? I'll try to take a look at this next week

**Comment by lilyball** [comment]
Pretty much. Without #1441 it also matters from the perspective of reading the source, and to be honest, I'd rather remove whitespace than switch to multiline strings anyway because the raw query isn't really what I'm looking at the source for and using multiline strings just means even more of the vertical space of the file is now devoted to raw queries.

**Comment by designatednerd** [comment]
Unfortunately from a standpoint of debugging, it's a LOT easier for people to see problems when those strings are multi-line. I can definitely still do some work to make sure the whitespace gets stripped when it hits the network, though.

I've got Vague Long-Term Plans™ to make the file not so bloody long in the future, but at the moment I think "easier to figure out wtf is going wrong" is probably higher priority at this very moment than "oh god this file is so damned long"

**Comment by lilyball** [comment]
If you keep it with whitespace in the source and then strip when it hits the network, that means reimplementing GraphQL syntax parsing in Swift just to figure out which whitespace is sensitive (e.g. whitespace in string literals) and which isn't. That seems like a really bad idea.

I don't understand how these strings help with debugging. I have literally never looked at the `operationDefinition` static property while debugging and I don't know why I would. The `.graphql` file is the source of truth for how the operation is defined, and I only actually look at the generated `.swift` file if I have a question about what the API looks like (e.g. if I've forgotten how fragments get represented).

**Comment by designatednerd** [comment]
I meant debugging more from a standpoint of "Staring at the code and trying to figure out what's wrong with it" than "actually doing something at runtime with a debugger". This is particularly helpful in my case when someone can send me a screenshot or an `API.swift` file I can get a look at but doesn't want to send me their whole project - that way I don't have to ask them for their `.graphql` files and schema as well. 

That's a good point about doing it at runtime being more error-prone - I'll take a look at whether there might be a better way to generate the string when we have the parsed information.

**Comment by lilyball** [comment]
If someone sends you an `API.swift` file, you can take the `operationDefinition` and dump it into a GraphQL formatter if you don't want to read the compact version. That said, I consider all the extraneous spacing and newline escapes in the operation definition to be the biggest problem with readability and a compact version (with judicious spacing around punctuation) should be reasonably readable.

**Comment by lilyball** [comment]
This has been done at this point. If the query contains a multiline string the whitespace removal is disabled; ideally it would compress just the insignificant whitespace, but I'll take what I can get.

**Comment by spacether** [comment]
Which PR implemented this feature?

**Comment by designatednerd** [comment]
Looks like a combo of #1441 and #1538 - there's a `suppressSwiftMultilineStringLiterals` option which can now be passed in.
