### ISSUE TITLE
Broken link to Apollo Config docs

### ISSUE THREAD

**Issue by rlancer** [apollographql/apollo-tooling#1195]
Link to Apollo Config currently 404s https://www.apollographql.com/docs/references/apollo-config.html

![image](https://user-images.githubusercontent.com/1339007/56249448-d1e0f100-6079-11e9-9ff2-833f39c33c5d.png)

**Comment by JakeDawkins** [comment]
@rlancer sorry about this! We have a brief outage yesterday during a company hackathon on docs that lasted around 10 mintues. This shouldn't be an issue anymore :)

**Comment by normantas** [comment]
Several months after the issue was raised, I can confirm that the link is still broken.
Could someone please give me a working link to the documentation for Apollo Config?

**Comment by JakeDawkins** [comment]
So sorry @normantas! Here's the working link: https://www.apollographql.com/docs/devtools/apollo-config/
