### ISSUE TITLE
Dart Codegen

### ISSUE THREAD

**Issue by smkhalsa** [apollographql/apollo-tooling#1203]
With the rise in popularity of flutter, I'd love to be able to use Apollo Engine with my flutter projects.

**Comment by trevor-scheer** [comment]
@smkhalsa, thanks for submitting an issue. While we'd love to be able to support this, we can't commit to building or maintaining this. It may be worth investigating an oclif plugin (see: https://oclif.io/docs/plugins.html), which the CLI supports. We'd love to see some plugins for the CLI pop up, and would be happy to support how we can!
