### ISSUE TITLE
apollo-graphql publishes ES6 to npm, can't be parsed in IE

### ISSUE THREAD

**Issue by mxmul** [apollographql/apollo-tooling#1210]
**Intended outcome:**

apollo-graphql can be imported in a JS application, and then parsed / executed in IE without a transpilation step. It's unexpected for libraries to publish anything other than ES5 to the public registry.

**Actual outcome:**

The code published to the NPM includes many ES6+ constructs (including rest/spread), and will fail to parse in older browsers. This forces consumers of the package to transpile their node_modules if they need to support IE or other older browsers.

(CMD-F for "..." in https://unpkg.com/apollo-graphql@0.2.0/lib/transforms.js)

**How to reproduce the issue:**

Create a simple JS entry point that imports apollo-client, e.g:

```
$ cat main.js
import { defaultEngineReportingSignature } from 'apollo-graphql';
```

and bundle it with Webpack. This resulting JS bundle cannot be parsed in IE11, unless you add babel-loader and begin transpiling everything in node_modules.

**Versions**

apollo-graphql@0.2.0

**Comment by trevor-scheer** [comment]
Thanks for submitting an issue, @mxmul. For the time being, we're really only interested in supporting this package for use in a node environment. Furthermore, this package is undocumented and (for now) really just intended for internal use. Please feel free to fork and change as you see fit!
