### ISSUE TITLE
VS Code plugin not loading Engine schema on Windows

### ISSUE THREAD

**Issue by arjunyel** [apollographql/apollo-tooling#1225]
**Intended outcome:**

Expect to load the schema from Apollo Engine into the Windows 10 VS Code and to get all the VS Code features working

**Actual outcome:**

On Windows 10 latest VS code and latest apollo plugin 1.6.4 (tested on two different windows devices, one WSL one regular powershell) the output console says
 `
🚀 Apollo GraphQL v1.6.4
❌ Service stats could not be loaded. This may be because you're missing an apollo.config.js file or it is misconfigured. For more information about configuring Apollo projects, see the guide here (https://bit.ly/2ByILPj).
`

However with the same apollo.config.js in Ubuntu 18.04 in Hyper-V it works perfectly and I get autocomplete in .graphql files

Apollo config:
`module.exports = {
  client: {
    service: 'xxxx-8899'
  }
};`

**How to reproduce the issue:**

On Windows 10:

1. Push a schema to an apollo engine schema
1. make a new folder with a .env file and an apollo.config.js with the engine service `module.exports = {
  client: {
    service: 'xxxx-8899'
  }
};`

1. Check VS Code output to see if loaded correctly and/or try autocomplete in a .graphql file

**Versions**

- Apollo GraphQL VS Code Plugin: 1.6.4
- VS Code: 1.33.1
- Windows 10

**Comment by helloncanella** [comment]
same with mac.

**Comment by trevor-scheer** [comment]
@arjunyel @helloncanella is this still an ongoing issue?

**Comment by arjunyel** [comment]
Hi I recently was able to get it to work with a remote schema, if I have another issue with it Ill open a new issue. Thanks!
