### ISSUE TITLE
Unable to install apollo graphql extension in latest vscode

### ISSUE THREAD

**Issue by vikasraj789** [apollographql/apollo-tooling#1256]
Unable to install Extension 'apollographql.vscode-apollo-1.6.4' as it is not compatible with Code '1.24.0'.

**Comment by JakeDawkins** [comment]
@vikasraj789 `1.24.0` is not a recent version of VS Code. It was released in June of 2018. The latest is `1.33.1`. We don't support versions of VS Code older than November 2018.

**Comment by vikasraj789** [comment]
@JakeDawkins sorry. My mistake.

**Comment by JakeDawkins** [comment]
No worries!
