### ISSUE TITLE
Generate stub interfaces for empty query *Variables

### ISSUE THREAD

**Issue by tekacs** [apollographql/apollo-tooling#130]
### Problem

At least in the TypeScript generator, apollo-codegen appears not to generate a type when a server-side GraphQL endpoint takes no variables.

Whilst this makes some degree of sense, it means that the type at the point where the variables are sent currently has to be hardcoded to an empty object type `{}`.

This breaks forward-portability of these endpoints, since migrating the server-side signature does not automatically update the client-side function passing `*Variables` (since it previously didn't exist).

### Proposed Solution

Generate an empty interface for `*Variables`, making this consistent with generation for endpoints that do take variables.

Currently (we have an `apollo.mutate` wrapper, but the principle is the same):
```ts
// no type generated
apollo.mutate<..., {}>(...) // when the server is updated, this will be out of date & potentially error at runtime
```

Proposed:
```ts
interface SomeQueryVariables { }
apollo.mutate<..., SomeQueryVariables>(...) // when the server is updated, this will be updated and break the TS compile until changed, if the changed fields are not provided
```

Understandably some people may prefer to have this turned off, so it might need to be an option?

Thanks!

**Comment by rricard** [comment]
@tekacs I think that we could put it by default and I'm not for adding it as an option... However, we have more pressing issues right now but I think a PR should be pretty easy to do.

**Comment by rricard** [comment]
@martijnwalraven It may be easier to handle that at IR level though...

**Comment by martijnwalraven** [comment]
@rricard: What do you mean by handling this at the IR level? The IR includes variables for operations, but it is up to the target to decide what to do with them. We don't generate `*Variables` for Swift for example, but define these as properties on the generated operation class.

**Comment by rricard** [comment]
What I mean is instead of passing a null with the operation variables (if I'm not wrong, I can recheck that), we can pass an empty variable set even if there are no variables.

**Comment by rricard** [comment]
I mean it's not even this. It's actually the GraphQL compiler I'm talking about at this point
