### ISSUE TITLE
TypeError: Property name expected type of string but got null

### ISSUE THREAD

**Issue by pvinis** [apollographql/apollo-tooling#1309]
I am getting this.
```
$ apollo-codegen generate ./app/**/queries.ts --addTypename --schema ./app/schema.json --target typescript --output ./app/__generated__/types.ts
TypeError: Property name expected type of string but got null
    at validate (/Users/pvinis/Source/sense/niceday/node_modules/@babel/types/lib/definitions/utils.js:161:13)
    at Object.validate (/Users/pvinis/Source/sense/niceday/node_modules/@babel/types/lib/definitions/utils.js:172:7)
    at validate (/Users/pvinis/Source/sense/niceday/node_modules/@babel/types/lib/validators/validate.js:17:9)
    at builder (/Users/pvinis/Source/sense/niceday/node_modules/@babel/types/lib/builders/builder.js:46:27)
    at Object.Identifier (/Users/pvinis/Source/sense/niceday/node_modules/@babel/types/lib/builders/generated/index.js:320:31)
    at nonNullableTypeFromGraphQLType (/Users/pvinis/Source/sense/niceday/node_modules/apollo-codegen-typescript/src/helpers.ts:47:34)
    at TypescriptAPIGenerator.typeFromGraphQLType (/Users/pvinis/Source/sense/niceday/node_modules/apollo-codegen-typescript/src/helpers.ts:55:20)
    at TypescriptAPIGenerator.handleFieldValue (/Users/pvinis/Source/sense/niceday/node_modules/apollo-codegen-typescript/src/codeGeneration.ts:428:20)
    at fields.map.field (/Users/pvinis/Source/sense/niceday/node_modules/apollo-codegen-typescript/src/codeGeneration.ts:347:20)
    at Array.map (<anonymous>)
error Command failed with exit code 1.
```

Could it be something similar to https://github.com/apollographql/apollo-tooling/issues/569?

**Intended outcome:**

No errors.

**Actual outcome:**

Errors.

**How to reproduce the issue:**

Have a `schema.json` with something like:
```
 {
              "name": "firstName",
              "description": "",
              "args": [],
              "type": {
                "kind": "NON_NULL",
                "name": null,
                "ofType": {
                  "kind": "SCALAR",
                  "name": "String",
                  "ofType": null
                }
              },
              "isDeprecated": false,
              "deprecationReason": null
            },
```

**Comment by trevor-scheer** [comment]
@pvinis, thanks for submitting an issue! Could you please provide a runnable reproduction? I'll also recommend upgrading to apollo v2.x, as 1.x is no longer supported.

**Comment by jtomaszewski** [comment]
Have you resolved it anyhow? I just encountered this issue on "apollo-codegen": "0.20.2" .

**Comment by lihao-id** [comment]
- `npm install --save-dev @babel/plugin-transform-destructuring` 

- 
`
. babelrc
{
  "plugins": [
    ["@babel/plugin-transform-destructuring", { "useBuiltIns": true }]
  ]
}
`

**Comment by jfeaver** [comment]
I was trying to install apollo-codegen locally to my project with yarn and was getting this same error. When I tried installing apollo-codegen globally, as per the setup instructions, this error went away.

My package.json dependencies had been (just now realizing I should have added codegen to my dev dependencies...):
```
  "dependencies": {
    "@angular/common": "~10.0.14",
    "@angular/core": "~10.0.14",
    "@angular/forms": "~10.0.14",
    "@angular/platform-browser": "~10.0.14",
    "@angular/platform-browser-dynamic": "~10.0.14",
    "@angular/router": "~10.0.14",
    "@apollo/client": "^3.0.0",
    "@capacitor/core": "2.4.0",
    "@ionic-native/core": "^5.0.7",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "@ionic/cli": "^6.10.1",
    "@ionic/storage": "^2.1.3",
    "apollo-angular": "^2.0.4",
    "apollo-codegen": "^0.20.2",
    "graphql": "^15.0.0",
    "rxjs": "^6.6.2",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.1"
  },
```

**Comment by OjeshManandhar** [comment]
> I was trying to install apollo-codegen locally to my project with yarn and was getting this same error. When I tried installing apollo-codegen globally, as per the setup instructions, this error went away.
> 
> My package.json dependencies had been (just now realizing I should have added codegen to my dev dependencies...):
> 
> ```
>   "dependencies": {
>     "@angular/common": "~10.0.14",
>     "@angular/core": "~10.0.14",
>     "@angular/forms": "~10.0.14",
>     "@angular/platform-browser": "~10.0.14",
>     "@angular/platform-browser-dynamic": "~10.0.14",
>     "@angular/router": "~10.0.14",
>     "@apollo/client": "^3.0.0",
>     "@capacitor/core": "2.4.0",
>     "@ionic-native/core": "^5.0.7",
>     "@ionic-native/splash-screen": "^5.0.0",
>     "@ionic-native/status-bar": "^5.0.0",
>     "@ionic/angular": "^5.0.0",
>     "@ionic/cli": "^6.10.1",
>     "@ionic/storage": "^2.1.3",
>     "apollo-angular": "^2.0.4",
>     "apollo-codegen": "^0.20.2",
>     "graphql": "^15.0.0",
>     "rxjs": "^6.6.2",
>     "tslib": "^2.0.0",
>     "zone.js": "~0.11.1"
>   },
> ```

I have `apollo-codegen` in `devDependencies` and still get that error

**Comment by nassim99** [comment]
@OjeshManandhar  i was having the same problem

fixed by:

-  installing apollo-codegen globally
-  remove apollo-codegen from dependencies/devDependencies

**Comment by sshquack** [comment]
Thanks @nassim99 

The docs mention that this tool `can be installed globally` but it should say `must be installed globally`.
<img width="787" alt="Screenshot 000089@2x" src="https://user-images.githubusercontent.com/5678459/154881610-e536974b-8e85-4388-8492-1bc885865d1b.png">

This has the same effect as `npx apollo-codegen ...`

**Comment by iDuuck** [comment]
Also getting this (again). Worked before by de-installing the local dependency, but came back after some time.
