### ISSUE TITLE
Upgrading to Angular v8, @endemolshinegroup/cosmiconfig-typescript-loader requires a peer of cosmiconfig@>=5

### ISSUE THREAD

**Issue by dauledk** [apollographql/apollo-tooling#1322]
**Intended outcome:**
When installing dependencies for Apollo in my Angular v8 app, I expect no warnings.

**Actual outcome:**
I get the warning message:
```
npm WARN @endemolshinegroup/cosmiconfig-typescript-loader@1.0.0 requires a peer of cosmiconfig@>=5 but none is installed. You must install peer dependencies yourself.
```
I can see in the `package-lock.json` file, that the chain is: 
`apollo` requires ==> `apollo-language-server` requires ==> `@endemolshinegroup/cosmiconfig-typescript-loader` 

**How to reproduce the issue:**
Install dependencies with `npm i`

**Versions**
Dependencies:
```js
    "apollo-angular": "^1.6.0",
    "apollo-angular-link-http": "^1.7.0",
    "apollo-cache-inmemory": "^1.6.0",
    "apollo-client": "^2.6.0",
    "apollo-link-context": "^1.0.17",
    "apollo-link-error": "^1.1.10",
    "apollo-upload-client": "^10.0.1",
```
dev-dependencies:
```js
"apollo": "^2.12.5",
```

**Comment by trevor-scheer** [comment]
@dauledk thanks for submitting an issue, can you please provide a runnable reproduction? A repo that we can clone would be great.
