### ISSUE TITLE
apollo-language-server has a high severity vulnerability from lodash.merge 4.6.1

### ISSUE THREAD

**Issue by sean6bucks** [apollographql/apollo-tooling#1327]
**Intended outcome:**

updated packages that pass security vulnerability checks from services like npm or snyk

**Actual outcome:**

`apollo-language-server` is using `lodash.merge` @ v4.6.1 which has known issues and is causing high severity vulnerability warnings in security checks for multiple packages used by and including main `apollo` package

**Versions**

apollo-language-server@1.9.1
apollo@2.12.5

The issue is known for `merge` per-method lodash package and is "planned" to be fixed, but in the mean time would be good to replace with cherry-picked from the primary lodash package `lodash/merge` or replaced, these possible solutions are mentioned https://github.com/lodash/lodash/issues/4193 and https://github.com/googleapis/nodejs-vision/issues/381

**Comment by JakeDawkins** [comment]
Updated to 4.6.2 in #1387. Thanks :)
