### ISSUE TITLE
Apollo codegen import fragment from another npm package

### ISSUE THREAD

**Issue by hansololai** [apollographql/apollo-tooling#1341]
I am following a pattern where I put graphql fragment as a class attribute of a ui component. For example, a user component, more info about this pattern [here](https://medium.com/airbnb-engineering/how-airbnb-is-moving-10x-faster-at-scale-with-graphql-and-apollo-aa4ec92d69e2) 
```
const User = (props)=>{
return props.name
}
User.fragment=gql`
fragment UserName on User{
name
}
```
Then in the place I use this component, I import the component and use the fragment in the query
```
import User from './user.js';
query = gql`
${User.fragment}
getUser(id:1){
...UserName
}
```
Then I do apollo client:codegen to generat types for the query. 
This all works well if the User component is in another js file. 
At some point I need to make the User component into a seperate npm package, and I get the fragment not found error. I am guessing it is because codegen is not able to find the fragment in a compiled ES5 file, then is there a way to load it manually?

**Comment by trevor-scheer** [comment]
@hansololai, it sounds to me like you would want your new package to generate and export those types on its own, does that seem reasonable?

Another approach that should work is to configure your `includes` to also search your package's source folder via the `client.includes` config option.
https://www.apollographql.com/docs/references/apollo-config/#clientincludes

Be careful, by default `client.excludes` is set up to ignore `node_modules` by default. You may need to configure the excludes more specifically.

**Comment by hansololai** [comment]
@trevor-scheer  Thanks, the include is what I endup doing, my new package does generate the types, but they are just the types for the fragment, in this case, the type for UserName fragment is exported from the package, but the query result type,
```
interface Result {
  getUser: Result_getUser
}
interface Result_getUser{
   // same as the fragment type
}
```
Cannot be generated. But the include node_module/package/src totally worked. Thanks!
