### ISSUE TITLE
operationId is invalid for swift codegen

### ISSUE THREAD

**Issue by Codebear98** [apollographql/apollo-tooling#1362]
- operationId mismatch with sever due to missing `\n` in apollo-codegen-swift.

You can find there is `\n` to separate fragments in `apollo-codegen-core`
```
  const sourceWithFragments = [
    operation.source,
    ...Array.from(fragmentsReferenced).map(fragmentName => {
      const fragment = fragments[fragmentName];
      if (!fragment) {
        throw new Error(`Cannot find fragment "${fragmentName}"`);
      }
      return fragment.source;
    })
  ].join("\n");
```
https://github.com/apollographql/apollo-tooling/blob/master/packages/apollo-codegen-core/src/compiler/visitors/generateOperationId.ts

However in `apollo-codegen-swift`, the missing `\n` causing operationId mismatch with server.

```
if (fragmentsReferenced.size > 0) {
  this.printNewlineIfNeeded();
  this.printOnNewline(
    "public var queryDocument: String { return operationDefinition"
  );
  fragmentsReferenced.forEach(fragmentName => {
    this.print(
      `.appending(${this.helpers.structNameForFragmentName(
        fragmentName
      )}.fragmentDefinition)`
    );
  });
  this.print(" }");
}
```

https://github.com/apollographql/apollo-tooling/blob/master/packages/apollo-codegen-swift/src/codeGeneration.ts

**Comment by designatednerd** [comment]
@Codebear98 Is this any better with iOS 0.13.0 (calling through to tooling 2.16) that's adding the trailing newline now?

**Comment by Codebear98** [comment]
checked apollo-ios 0.13.0 don't have such issues anymore, operationID is now valid! @designatednerd thanks for the upgraded!
