### ISSUE TITLE
Generating types without describing queries

### ISSUE THREAD

**Issue by alexkarpxb** [apollographql/apollo-tooling#1364]
Hi, I'm new to apollo and graphql and I have one question about apollo codegen:

Is there a way to generate all types only by graphql server schema, without describing queries in client sources? 

I'm trying to run this command: 

` apollo codegen:generate --target typescript --localSchemaFile=schema.json  --outputFlat`

but if I don't describe query in sources I get following error: 

`No operations or fragments found to generate code for`

**Comment by syffs** [comment]
@alexkarpxb if you post an issue and you fixed it afterward, you should post an update for future reference
did you resolve this ?
