### ISSUE TITLE
404 apollographql/apollo-tools

### ISSUE THREAD

**Issue by ranjitnadar** [apollographql/apollo-tooling#1373]
Need help or want to talk all things Apollo Tooling? Issues here are reserved for bugs or feature requests, but you ask for help in our Spectrum community:
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@apollographql%2fapollo-tools - User not found
npm ERR! 404
npm ERR! 404  '@apollographql/apollo-tools@^0.3.6' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'apollo-server-core'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\indx\AppData\Roaming\npm-cache\_logs\2019-07-02T13_11_25_521Z-debug.log
- Apollo's Spectrum community: https://spectrum.chat/apollo

**Comment by JakeDawkins** [comment]
I'm not sure what you're asking about here. I'm going to close this since there's not enough context. Also, `apollo-tools` isn't a package maintained by Apollo
