### ISSUE TITLE
How to download schema in SDL format?

### ISSUE THREAD

**Issue by essaji** [apollographql/apollo-tooling#1408]
Hey guys!

We are using graphQL schema in SDL format at our client side. I tried to download schema from the registry using `apollo client:download-schema output.graphql` but it looks like its downloading it in `JSON` format. I know we can convert it using `printSchema` function from `graphql` library but I was wondering is there already a way or flag which I can use to directly download it in `SDL` format?

If not, I will be happy to create a PR to add this feature, may be add another flag i.e. `--sdl` to download it in `SDL` format.

Thanks in anticipation

**Comment by JacksonKearl** [comment]
Hey @essaji, that sounds good to me. And it will help with our work in `apollo service:codegen`, as that operates from SDL as well. I'd probably configure this as `--target SDL`, for better uniformity with our other commands.

**Comment by lgandecki** [comment]
Go fot it @essaji ! ;)

**Comment by essaji** [comment]
Closing this thread as the feature has been added & expected to be released soon 🎉

**Comment by skanygin** [comment]
Looks like isn't released yet.
<img width="1663" alt="Снимок экрана 2019-11-14 в 16 31 06" src="https://user-images.githubusercontent.com/14076150/68861240-33466c80-06fc-11ea-83c1-ef76f52c7987.png">

**Comment by EmadKaizen** [comment]
All generated file still in json format

```apollo/2.21.3 win32-x64 node-v12.13.1```

**Comment by dylanwulf** [comment]
@skanygin @EmadKaizen It seems to be working fine for me (I'm on v2.21.2 at the moment). Keep in mind that this feature is _only_ available when using the `client:download-schema` command, _not_ when using the `service:download` command.
