### ISSUE TITLE
Number of Types: 0 (0 client types)

### ISSUE THREAD

**Issue by patricknick** [apollographql/apollo-tooling#1410]
**Intended outcome:**

Apollo GraphQL plugin for VS Code should load the available GQL types from my local service and merge them with the local types, even if the service is started AFTER VS Code. At least the "Reload schema" command should help.

```
------------------------------
🚀 Apollo GraphQL v1.7.4
------------------------------
✅ Service Loaded!
🆔 Service ID: test
🏷 Schema Tag: current
📈 Number of Types: 184 (22 client types)
```

**Actual outcome:**

The plugin loads successfully but recognizes 0 types.

```
------------------------------
🚀 Apollo GraphQL v1.7.4
------------------------------
✅ Service Loaded!
🆔 Service ID: test
🏷 Schema Tag: current
📈 Number of Types: 0 (0 client types)
```

**How to reproduce the issue:**

1. Startup VS Code, make sure, your local server is NOT yet running
2. The plugin will report an error in the Output with "ECONNREFUSED", which makes sense, as the service is not yet running.
3. Start the GraphQL service (we use an Apollo server)
4. Click on this button on the bottom right of VS Code to show the plugin status:
![image](https://user-images.githubusercontent.com/25477019/61384165-59741100-a8b0-11e9-81f7-b48a22bd32a4.png)
5. You will see the actual outcome with 0 loaded types.

**Some notes:**
- The plugin works as intended, if we start the service BEFORE we start VS Code.
- The command "Apollo: Reload Schema" does not fix the issue. Still 0 types are loaded.
- Editing the apollo.config.js (just open it and press save) triggers the plugin to reload properly.

My config looks like this:
```
module.exports = {
  client: {
    name: 'my-client',
    service: {
      name: 'test',
      url: 'http://localhost:3010/graphql',
    },
  },
};
```

**Versions**

- Apollo GraphQL v1.7.4

**Comment by JakeDawkins** [comment]
Ah, good catch! Reloading the schema should definitely fix it, and ideally, we'd be able to load client types with no remote schema. I think that's failing because we merge local with remote schemas, so if there's no remote schema, merging fails.


I'm not sure if we can do anything about the ECONNREFUSED error, although I'm interested in the possibility of polling/clicking a button to refresh without manually calling reload schema

**Comment by patricknick** [comment]
Enabling to use a client-only schema would be great indeed!

The ECONNREFUSED is probably not an issue. VS Code reports this error on startup, therefore a user should be aware about this and gets a hint on what's wrong. Some sort of polling would be amazing, as you don't have to remember clicking the "reload" button anymore but you can simply start coding like in any other language. 

Will you tackle this bug yourself or could you give me some directions to start with a PR?

**Comment by JakeDawkins** [comment]
This could get a bit tricky. I'm working on some issues with errors and some quality of life issues, so I may be able to take a look at this. If you don't see any chatter/solutions for this soon, just ping me again.

**Comment by patricknick** [comment]
@JakeDawkins Think it's time for the promised ping. 😄Did you get the time yet to have a look into this?

**Comment by patricknick** [comment]
No worries, keep on with your amazing work! When I find time I'll try to have a look myself too. :)

**Comment by patricknick** [comment]
The VS Code command "Reload schema" does now correctly load the types. Therefore I consider this done. Thanks guys! 🙂
