### ISSUE TITLE
codegen: output warning if query type generation is suppressed because of naming conflict

### ISSUE THREAD

**Issue by thefliik** [apollographql/apollo-tooling#1427]
As mentioned in #670, `apollo codegen` requires query names to be unique for a project when generating types. If two queries have the same name, type generation for the second query will be silently skipped.

This behavior is unexpected. It would be very helpful is apollo codegen output a console warning, including a filepath, whenever this occurs.

**Comment by JakeDawkins** [comment]
Hey @thefliik, I'd like to see if I can add a warning to this. Can you provide me with a simple reproduction repo that's affected by this to save me some time?

**Comment by thefliik** [comment]
@JakeDawkins here you go: https://github.com/thefliik/apollo-tooling-issue

I left some simple reproduction steps in the repo's readme
