### ISSUE TITLE
VsCode Extension Service stats could not be loaded

### ISSUE THREAD

**Issue by olaf89** [apollographql/apollo-tooling#1440]
**Intended outcome:**
I would like to use autocomplete

**Actual outcome:**
When running extension the output is 
```
🚀 Apollo GraphQL v1.9.0
------------------------------
❌ Service stats could not be loaded. 
This may be because you're missing an apollo.config.js file or it is misconfigured. 
For more information about configuring Apollo projects, see the guide here (https://bit.ly/2ByILPj).
```
My config is

apollo.config.js
```
module.exports = {
  client: {
    includes: ['./src/client.schema.ts'],
    service: {
      localSchemaFile: './node_modules/@mycompany/gql-schema/schema.graphql'
    }
  }
};
```
Where schema.graphql is the SDL.

I tries on mac and Linux.

**How to reproduce the issue:**

**Versions**

**Comment by jasonpaulos** [comment]
Hi @olaf89, have you tried giving your service a name, such as:
```javascript
module.exports = {
  client: {
    includes: ['./src/client.schema.ts'],
    service: {
      name: 'Local service',
      localSchemaFile: './node_modules/@mycompany/gql-schema/schema.graphql'
    }
  }
};
```
Let me know if that helps.

**Comment by olaf89** [comment]
Hey, unfortunately it does not help.

**Comment by JakeDawkins** [comment]
Interesting, @olaf89 Is this still an issue? 

I can't seem to reproduce this locally. Can you provide any more info or a simple reproduction repo with an operation in a src file, a basic schema and a node_modules folder with nothing but a folder that contains the schema with instructions on how to reproduce this?

**Comment by olaf89** [comment]
Here is a repo, just try to get apollo tools initialized cause im always getting error
https://github.com/olaf89/apollo-tools-issue

```
Field "Query.viewer" already exists in the schema. It cannot also be defined in this type extension.

Type "User" already exists in the schema. It cannot also be defined in this type definition.

Field "User.id" already exists in the schema. It cannot also be defined in this type extension.

Field "User.name" already exists in the schema. It cannot also be defined in this type extension.
```

or just 
```
 Service stats could not be loaded. This may be because you're missing an apollo.config.js file or it is misconfigured. For more information about configuring Apollo projects, see the guide here (https://bit.ly/2ByILPj).
```

**Comment by JakeDawkins** [comment]
@olaf89 I'm not sure what's going on here for you. When I clone that repo and run codegen against it using the most recent version of the CLI, I don't get any errors, and I get properly generated types. Same thing with the VS Code extension, it loads the schema properly for me.

<img width="1287" alt="Screen Shot 2019-09-10 at 10 14 47 AM" src="https://user-images.githubusercontent.com/9259509/64621659-0bf9b900-d3b4-11e9-9818-7020425f16b3.png">
<img width="936" alt="Screen Shot 2019-09-10 at 10 14 57 AM" src="https://user-images.githubusercontent.com/9259509/64621662-0c924f80-d3b4-11e9-9de1-394017603e4a.png">

Can you make sure everything is up to date (`apollo@2.18.1`, `vscode-apollo@1.10.0`)? Also, is there anything else that could be causing this? Are you on Windows/linux/mac?

**Comment by olaf89** [comment]
So i removed VS code extension and installed it again which fixed it. Its weird cause the same thing happened on my Mac and Linux and it was also not working for my team mates.

Anyway closing the issue thanks for help.

**Comment by torstenaan** [comment]
> So i removed VS code extension and installed it again which fixed it. Its weird cause the same thing happened on my Mac and Linux and it was also not working for my team mates.
> 
> Anyway closing the issue thanks for help.

Reinstalling helped me as well. Thanks :)

**Comment by enomado** [comment]
https://user-images.githubusercontent.com/707007/138576525-23b32211-4f72-40eb-a7fd-0602c50202ef.mp4

Is it okay? https://github.com/apollographql/vscode-graphql/issues/38

**Comment by dkhrunov** [comment]
> 2021-10-24.00-01-09.mp4 
> Is it okay? [apollographql/vscode-graphql#38](https://github.com/apollographql/vscode-graphql/issues/38)

Same issue

**Comment by hassan-devDz** [comment]
> 2021-10-24.00-01-09.mp4
> 
> Is it okay? [apollographql/vscode-graphql#38](https://github.com/apollographql/vscode-graphql/issues/38)

Same issue

**Comment by ameeruljunaidi** [comment]
> 2021-10-24.00-01-09.mp4 
> Is it okay? [apollographql/vscode-graphql#38](https://github.com/apollographql/vscode-graphql/issues/38)

Hi, I have the same issue! It only worked on the config file.
