### ISSUE TITLE
Reload schema command doesn't reflect added fields

### ISSUE THREAD

**Issue by venkatd** [apollographql/apollo-tooling#1446]
I have a apollo.config.js like this:
```javascript
module.exports = {
  client: {
    includes: ['src/**/*.js', 'src/*.js'],
    service: {
      url: 'http://localhost:4000'
    }
  },
};
```

If I add a field to`http://localhost:4000` and run the `Apollo: Reload schema` command, this field is not picked up unless I completely restart VSCode.

Hoping to get this working for a demo on Apollo I'm giving next week :). Will make the workflow a lot smoother if I can modify the backend and then show the results immediately.

A minimal reproduction is below:
[reload-test.zip](https://github.com/apollographql/apollo-tooling/files/3438621/reload-test.zip)

Steps to reproduce:
- `npm install`
- `npm server.js`
- Open the folder in vscode and in `src/client.js` you'll be able to see that autocomplete is working properly
- stop the server, uncomment the year property, and restart the server
- In vscode, run the `Apollo: Reload schema` command
- Go back to `src/client.js` and try to type something. You'll see that the year field is not being picked up
- Restart vscode and go back to `src/client.js` you'll see the year field is now available

However, if I do the same but I comment out a field such as author and call the reload schema command, this gets picked up properly without needing a restart with a message like `Cannot query field "author" on type "Book".`

Any guidance on where to begin investigating would be appreciated!

**Comment by venkatd** [comment]
Ok, I think I found a fix for this just opened a PR.

**Comment by JakeDawkins** [comment]
Merged! Thank you so much. The reproduction is fantastic! I'll have to use this as an example for others. It made it super easy to test :)
