### ISSUE TITLE
[managed federation] support --localSchemaFile for service:check/push

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/apollo-tooling#1448]
Using the `service:check` and `service:push` commands for managed federation (with the `--serviceName` argument) only supports the `--endpoint` option, not `--localSchemaFile`.

I understand why this is the case: with managed federation, you don't want to check or push the _actual_ schema (which includes federation elements like `_entities` and `@requires`.) Instead, you want to push the "partial schema" provided by the `{ _service { sdl } }` query. The differences between the two schemas is a bit confusing and could lead to mistakes.

However, requiring a running server in automated CI infrastructure is challenging. I have to manage both the server process and `apollo` process in parallel. And our servers can be difficult to run in CI, due to runtime dependencies and access control.

I would prefer to write the partial schema to a file in one command, and subsequently run `apollo service:check --localSchemaFile`. Bonus point for allowing service:check/push to accept STDIN so I can just pipe the output from one command to another!

It's probably a good idea to sanity check the partial schema content to ensure it's not the full federated schema. The commands could raise an error if both `--serviceName` is present *and* `type _Service` exists in the local schema file.

***

The commands to generate the local schema file should be straight-forward in most cases.

In node.js, you can use [`printSchema`](https://github.com/apollographql/apollo-server/blob/ddeb71f8d6a0f3c91646aa0c7c99d2003b5bf73f/packages/apollo-federation/src/service/printFederatedSchema.ts#L63).

In ruby, you can make a rake task that uses [`Schema.federation_sdl`](https://github.com/Gusto/apollo-federation-ruby/blob/b7f19b99c385e94d29bed8dd34cc06383ce01ea2/lib/apollo-federation/schema.rb#L50).

In java, it'd be great if [`SchemaTransformer#sdl`](https://github.com/apollographql/federation-jvm/blob/dd7d64e12b1e1fad16b9138d9c074beadac292a6/graphql-java-support/src/main/java/com/apollographql/federation/graphqljava/SchemaTransformer.java#L137) was a public function. In the meantime, creating a printable schema is as easy as:

```java
final SchemaGenerator.Options options = SchemaGenerator.Options.defaultOptions()
    .enforceSchemaDirectives(false);

GraphQLSchema schemaWithoutFederation = new SchemaGenerator().makeExecutableSchema(
  options,
  typeDefinitionRegistry, // <-- types from a parsed SDL file *before* using Federation.transform
  RuntimeWiring.newRuntimeWiring().build());

final SchemaPrinter.Options options = SchemaPrinter.Options.defaultOptions()
    .includeScalarTypes(true)
    .includeExtendedScalarTypes(true)
    .includeDirectives(true);

System.out.println(new SchemaPrinter(options).print(schemaWithoutFederation()));
```

Regardless of the language, all federation libraries need to support the `_Service.sdl` field, so that can be reused for printing to local files.

cc @zionts

**Comment by nihalgonsalves** [comment]
This is possible as of `apollo@2.19.0`: https://github.com/apollographql/apollo-tooling/blob/master/CHANGELOG.md#apollo2190
