### ISSUE TITLE
Missing types on globalTypesFile

### ISSUE THREAD

**Issue by marcosfede** [apollographql/apollo-tooling#1479]
running  
`apollo client:codegen --includes='./src/**/*.{js,jsx}' --addTypename --target=typescript --globalTypesFile='src/typings/globalSchemaTypes.d.ts' && apollo client:codegen --includes='./src/**/*.{ts,tsx}' --addTypename --target=typescript --globalTypesFile='src/typings/globalSchemaTypes.d.ts' `

generates several files with definitions but lots of them have invalid references to  types that are missing on globalSchemaTypes. One example: 

// on some generated file:
import { PaymentInput } from "./../../../../../typings/globalSchemaTypes.d";

but That type does not exist on the generated globalSchemaTypes

For what I can tell all the missing types correspond to: Enums or Input Types

**Intended outcome:**
valid `.ts` files with the needed types on globalSchemaTypes

**Actual outcome:**
invalid imports

**Versions**
apollo/2.17.2 linux-x64 node-v10.16.3

**Comment by marcosfede** [comment]
I figured this is related to another issue, I'll open a separate ticket for that one

**Comment by jordmccord** [comment]
I'm having the same problem, did you manage to find a solution or find out what the issue is?

**Comment by marcosfede** [comment]
@jordmccord There were queries with the same name, and the types were not generating correctly. In the latest version the cli will throw a warning if this happens for you

**Comment by jordmccord** [comment]
No that doesn't seem to be the issue, I have the latest version, no errors and can find any queries with the same name. The symptoms are the same though, I'm getting a blank global schema file generated and imports generated for missing Enums or Input Types.

**Comment by Whispers12** [comment]
@marcosfede any updates?

**Comment by marcosfede** [comment]
@Whispers12 My issue was related to running the comand twice due to having some problems with queries with the same name. I solved it giving each query/mutation a unique name.
