### ISSUE TITLE
File '../../tsconfig.base' not found

### ISSUE THREAD

**Issue by HansHammel** [apollographql/apollo-tooling#1519]
related to https://github.com/apollographql/apollo-client/issues/3374

![image](https://user-images.githubusercontent.com/6475700/64572603-56554880-d368-11e9-855c-0d12bf6e700c.png)

![image](https://user-images.githubusercontent.com/6475700/64572628-6b31dc00-d368-11e9-9138-703f907e99e6.png)

all latest stable packages via npm

**Comment by Alamut98** [comment]
i also got same issue in new version. how to fix this error?

**Comment by abernix** [comment]
While the warning is certainly accurate, I'm trying to determine how this actually affects you.  In other words, why is this a problem, and what are you trying to accomplish by navigating the installed `node_modules`?
