### ISSUE TITLE
Just updated from Apollo 1.8.3 to 2.16.0, codgen:generate no longer works.

### ISSUE THREAD

**Issue by jonah-neugass-ck** [apollographql/apollo-tooling#1528]
So I just upgraded the Apollo tooling from 1.83 to 2.16.0 and my codegen:generate command is no longer working.

This is the command that had been working:

`apollo codegen:generate --target=swift --queries="./graphql/**" --schema="./graphql/schema.json" ./graphql-ios/API.swift`

**Intended outcome:**

The intended outcome is that the codgen command works and generates an API.swift file.

**Actual outcome:**

Here is the error that I get:
```
$ apollo codegen:generate --target=swift --queries="./graphql/**" --schema="./graphql/schema.json" ./graphql-ios/API.swift
 ›   Error: Unexpected argument: ./graphql-ios/API.swift
 ›   See more help with --help
```
**How to reproduce the issue:**

Run the command above.

**Versions**

Apollo 2.16.0

**Comment by designatednerd** [comment]
Hey @jonah-neugass-ck - can you please take a look at our updated scripts in the [iOS installation instructions](https://www.apollographql.com/docs/ios/installation/#adding-a-code-generation-build-step) - some of the names of the parameters changed. I think the one throwing you off at the moment is `--schema` should be `--localSchemaFile` and the name has to be quoted

**Comment by jonah-neugass-ck** [comment]
Awesome, thanks for the help.

**Comment by designatednerd** [comment]
Sure. Please feel free to close this out if those updated instructions work.

**Comment by jonah-neugass-ck** [comment]
I will, one other question, do you have documentation on how to generate persisted queries with hashed query ids?

**Comment by designatednerd** [comment]
Not directly but take a look at the [description on `operationIdsPath`](https://github.com/apollographql/apollo-tooling#apollo-clientcodegen-output), then on the client there should be an option on instantiation to use operation IDs. Right now there's still [an open PR](https://github.com/apollographql/apollo-ios/pull/608) for full support on that though.

**Comment by jonah-neugass-ck** [comment]
Great, thanks!
