### ISSUE TITLE
swift: field of type `self` conflicts with implicit `self` in initializer

### ISSUE THREAD

**Issue by lilyball** [apollographql/apollo-tooling#1530]
When generating Swift code where an object has a field named `self`, this synthesizes code that looks like

```swift
public struct Foo: GraphQLSelectionSet {
    // …
    public init(`self`: `Self`? = nil) {
        self.init(unsafeResultMap: ["__typename": "Foo", "self": `self`.flatMap { … }])
    }
    // …
}
```

Unfortunately, while the escaping makes this syntactically correct, the parameter <code>\`self\`</code> conflicts with the implicit parameter `self` because, while `self` is indeed a keyword, the compiler also treats it as equivalent to the identifier.

The use of the synthesized variable <code>public var \`self\`: \`Self\`</code> is perfectly fine as it doesn't actually reference the identifier within itself, and AFAICT no other generated code in the type references the `self` var (if it did, <code>self.\`self\`</code> would work fine of course). So we really just need to fix the initializer.

I'm pretty sure `self` is the only token we have to treat specially here, and I'm tempted to just name it `_self`, although of course if there's another field explicitly named `_self` then it would conflict; maybe we can detect that and tack on trailing underscores until we find something unique, e.g. `_self_`, `_self__`, etc. In any case, this change wouldn't be visible outside of the function as long as we keep the external parameter name as <code>\`self\`</code>. With the proposed fix the above type would become

```swift
public struct Foo: GraphQLSelectionSet {
    // …
    public init(`self` _self: `Self`? = nil) {
        self.init(unsafeResultMap: ["__typename": "Foo", "self": _self.flatMap { … }])
    }
    // …
}
```

CC @designatednerd

**Comment by lilyball** [comment]
I wish I would have caught this earlier as part of https://github.com/apollographql/apollo-tooling/pull/1515 but I have no idea how to run a development build of `apollo` against anything; when I tried, I just got errors that indicated that node didn't have its paths set up properly to load stuff.

**Comment by lilyball** [comment]
Well this is quite bizarre. I'm writing a test for this scenario, and when I have an alias `_self: name`, the field `_self` ends up with the variable name `self` instead of `_self`!

**Comment by lilyball** [comment]
Ugh, the `_self` -> `self` issue is due to the `camel-case` library, which apparently makes no effort to preserve leading/trailing underscores.

**Comment by lilyball** [comment]
BTW I'm currently working on this.

**Comment by designatednerd** [comment]
Thanks for looking into this - it's definitely a hellish nest of special cases.

**Comment by designatednerd** [comment]
To test against local:

- In the `apollo-tooling` repo root, run `npm install` on your branch to get the binaries installed. You may want to run `npm install --clean` or just nuke the `node_modules` folder before doing that. 
- In the `apollo-ios` repo, temporarily replace the contents of `scripts/check-and-run-apollo-cli.sh` with the following to call the generated binary: 

  ```
  APOLLO_CLI="[path/to/apollo-tooling/root]/packages/apollo/bin/run"
  set -x
  $APOLLO_CLI "$@"
  ```

**Comment by lilyball** [comment]
Is there any way to do this without globally installing the development copy?

**Comment by designatednerd** [comment]
As long as you don’t pass the -g flag it should install locally

**Comment by lilyball** [comment]
ok well, I tried doing `npm install` and then running the `packages/apollo/bin/run` already and it was giving me IIRC `node-env` errors and not having codegen available. I'm not on that computer at the moment to verify exactly what I saw.

**Comment by designatednerd** [comment]
Weird - definitely make sure the `[path/to/apollo-tooling/root]` is to your *checkout* of `apollo-tooling` rather than to it within `npm` stuff, otherwise that will use the system one.

**Comment by lilyball** [comment]
I'm not actually using `scripts/check-and-run-apollo-cli.sh` if that makes a difference. We have our own script that runs `apollo` and manipulates `.xcfilelist`s as necessary.

**Comment by lilyball** [comment]
I'm leaving on vacation tomorrow so I'm definitely not going to have a chance to test this against my production codebase. That shouldn't stop this PR from being reviewed and hopefully merged though.

**Comment by lilyball** [comment]
Just tested this again, `npm install --clean` from the root of `apollo-tooling`, and then ran `packages/apollo/bin/run help client:codegen` and I get a bunch of spew about `Error Plugin: apollo: Cannot find module 'apollo-env'` followed by `Error: command client:codegen not found`

**Comment by lilyball** [comment]
In fact, the `package.json` file defines a `client:codegen` command and if I run `npm run client:codegen` I get the same problem, presumably because it's literally calling `packages/apollo/bin/run client:codegen` itself.

**Comment by designatednerd** [comment]
yeah for some reason I've found that doing `npm run clean; npm install` seems to play a bit nicer. I'm not familiar enough with Node to know why, unfortunately.

**Comment by lilyball** [comment]
My suspicion is this only actually works if you install globally, and so it's not working on my setup because my global install of `apollo` is done via Nix, meaning `apollo-env` isn't in my normal global npm load paths (I did check to make sure a Homebrew-installed npm also fails when building locally so the usage of Nix is not why the local build isn't working).

**Comment by lilyball** [comment]
Well what do you know, `npm run clean; npm install` worked whereas `npm install --clean` didn't (I actually added `git clean -xfd` but that just deleted a single lockfile).
