### ISSUE TITLE
Error: Cannot find any-observable implementation nor global.Observable.

### ISSUE THREAD

**Issue by johntran** [apollographql/apollo-tooling#1541]
**Intended outcome:**

Be able to successfully run `codegen`.

**Actual outcome:**

Not able to run `codegen`. I get this error instead

```
Error: Cannot find any-observable implementation nor global.Observable. You must install polyfill or call require("any-observable/register") with your preferred implementation, e.g. require("any-observable/register")('rxjs') on application load prior to any require("any-observable").
    at loadImplementation (~/apollo-tools-repro/common/temp/node_modules/.registry.npmjs.org/any-observable/0.3.0/node_modules/any-observable/register.js:29:9)
    at ~/apollo-tools-repro/common/temp/node_modules/.registry.npmjs.org/any-observable/0.3.0/node_modules/any-observable/loader.js:30:18
    at Object.<anonymous> (~/apollo-tools-repro/common/temp/node_modules/.registry.npmjs.org/any-observable/0.3.0/node_modules/any-observable/index.js:2:39)
```

**How to reproduce the issue:**

Repro repo and instructions in `README.md`: https://github.com/johntran/apollo-tools-repro

**Versions**

Node: 10.16.0
`apollo`: 2.18.3

**Other Info**

Seems related?
https://github.com/SamVerschueren/listr/issues/91

**Comment by johntran** [comment]
This is definitely a pnpm problem:

Solved the above by adding `shamefully-flatten=true` to my `.npmrc`.

Closing this out

**Comment by Tymek** [comment]
It's a problem with `any-obserable` and/or `rxjs`, since it worked with `.npmrc`:
``` .npmrc
hoist-pattern[]=*rxjs*`
```
