### ISSUE TITLE
apollo service:check not working

### ISSUE THREAD

**Issue by khaledosman** [apollographql/apollo-tooling#1544]
I was trying out `apollo service:check`, I have everything set up with a proper ENGINE_API_KEY in my `.env` file, and `apollo service:push` works fine, but apollo service:check doesn't.

My apollo config file points to my lambda endpoint as Im using NodeJS without webpack so I can't load/require .graphql files, this is what it looks like:
```js
module.exports = {
  service: {
    endpoint: {
      url: '<aws-lambda-url>/dev/graphql'
    }
    // // OR
    // localSchemaFile: './path/to/schema.graphql'
  }
}
```

**Intended outcome:**
Expected to see a schema check that doesn't error out or reports problems if it does

**Actual outcome:**
```
$ apollo service:check
  ✔ Loading Apollo Project
  ⠧ Validating schema against tag current on graph ovs-graphql
    → Validating schema
  ✔ Loading Apollo Project
  ✖ Validating schema against tag current on graph ovs-graphql
    → https://engine.apollographql.com/service/ovs-graphql/upgrade.
    Comparing schema changes
    Reporting result
```

**Versions**
```js
$ apollo -v
apollo/2.18.3 darwin-x64 node-v12.10.0
```

**Comment by JakeDawkins** [comment]
From what I can tell @khaledosman, you don't have the `Team` license of the graph manager, which is required (I'm pretty sure) for `service:check` to work. While there's no error message (which is terrible), the url is pointing you to upgrade your plan. I'll close this for now unless there's any update :)

**Comment by amitjagtap21** [comment]
apollo:push --tag=dev gives me ServerError: Response not successful: Received status code 502 error. can you please help me in this
