### ISSUE TITLE
Allow Apollo codegen to split API into multiple files.

### ISSUE THREAD

**Issue by jonah-neugass-ck** [apollographql/apollo-tooling#1571]
We have a very large implementation of GraphQL and the generated API.swift file is enormous, making it hard to code review or even fit into some editors. Our current API.swift file is 135,277 lines. It would be great to be able to add functionality to apollo codegen for splitting up the API.swift file into multiple API files to avoid this issue.

**Comment by designatednerd** [comment]
@jonah-neugass-ck This is actually already possible! If you pass in a folder path (which has to already exist) rather than a file path, it will generate individual swift files rather than one gigantic file.

**Comment by jonah-neugass-ck** [comment]
@designatednerd That's great. Thanks for the info. Also, are there any tips anywhere on how to optimize the size of the generated files?

**Comment by designatednerd** [comment]
Not at the moment - I've got [a project on the iOS side](https://github.com/apollographql/apollo-ios/projects/2) to convert the actual "generation" part of codegen to Swift and take advantage of stuff like Codable, but that's in its infancy.

**Comment by jonah-neugass-ck** [comment]
That's awesome! One last question...when using the codegen command with the operationIdsPath switch, the query names in the json file don't actually match the generated swift classes. For instance the swift class will be GetConfigQuery but the name in the json file will be GetConfig. Is there any easy way to get those to match?

Thanks for all the help!

**Comment by designatednerd** [comment]
I believe the class name is basically `name of operation + type of operation` so since `GetConfig` is a query it becomes `GetConfigQuery`. The json file predates my time here so I'm not entirely sure why that isn't the same as the class name.

**Comment by jonah-neugass-ck** [comment]
Gotcha. Thanks again.

**Comment by designatednerd** [comment]
You bet - mind if I close this issue out?

**Comment by aaronrogers** [comment]
What's the expected output for this?  With the new Swift codegen library I specify `.multipleFiles` with a folder path and instead of one really big file I end up with two.  A small `Types.graphql.swift` and a huge `{MainAPI}.graphql.swift`.  I was hoping for N number of files for each class or struct in `{MainAPI}.graphql.swift`.

**Comment by designatednerd** [comment]
In theory it should generate one .graphql.swift file per operation - mind opening up an issue on the iOS repo so I can dig in to this? It would also help to know if you have all your operations in one big `.graphql` file or if they're spread across multiple files.

**Comment by aaronrogers** [comment]
Will do, thanks.
