### ISSUE TITLE
[Swift] client:codegen modifies existing files even when no changes in schema / mutations

### ISSUE THREAD

**Issue by ldiqual** [apollographql/apollo-tooling#1573]
On iOS, `client:codegen` overwrites the generated API.swift even though there is no changes in either `schema.json` or any of the client's graphql files. This prevents SwiftUI from rendering live previews because API.swift gets touched on build.

Would it be possible to skip building if there are no modifications?

**Comment by designatednerd** [comment]
Yeah this is something I'm working on fixing in updated codegen - there's [a workaround in terms of manually adding inputs and outputs](https://github.com/apollographql/apollo-ios/issues/369#issuecomment-425966048) but I've got [creating an `xcfilelist` automagically](https://github.com/apollographql/apollo-ios/issues/636) on the to-do list. 

Would welcome any PR help you can give on this end though!

**Comment by ldiqual** [comment]
Neat! Seems that adding:

Input: `$(SRCROOT)/App/**/*.graphql`
Output: `$(SRCROOT)/App/API.swift`

did the job. Thank you

**Comment by designatednerd** [comment]
Cool - I'll share this in the related threads on the iOS repo!

**Comment by designatednerd** [comment]
I've added this suggestion to [Advanced Codegen Tips & Tricks on the iOS docs](https://www.apollographql.com/docs/ios/installation/#advanced-codegen-tips-and-tricks), so I'm gonna close this out. 

Still planning on eventually generating an `xcfilelist` as part of the swift codegen project, but doc updates at least addresses this particular issue.

**Comment by koenpunt** [comment]
In addition to the input/output files, you could also first write to a temporary file, and compare that to the existing file, and then only moving the temporary file in place when the files differ;

```sh
"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" API.swift.new
if ! diff -q ./YourTarget/API.swift.new ./YourTarget/API.swift; then
  mv ./YourTarget/API.swift.new ./YourTarget/API.swift
else
  rm ./YourTarget/API.swift.new
fi
```

I've also created a PR to add this to the docs: https://github.com/apollographql/apollo-ios/pull/881
