### ISSUE TITLE
Apollo CLI unable to verify the first certificate when downloading schema via HTTPS

### ISSUE THREAD

**Issue by AttilaTheFun** [apollographql/apollo-tooling#1590]
I'm currently stuck using the Apollo CLI v1.9.1 to download schemas from my GraphQL API because any version higher than that does not seem to like my SSL certificate. When I try to upgrade to the latest, v2.18.3 and run the schema downloading script I get the following error:

$ apollo schema:download --endpoint=https://api.mywebsite.com Path/To/Schema/schema.json
  ✔ Loading Apollo Project
  ✖ Saving schema to Path/To/Schema/schema.json
    → request to https://api.mywebsite.com/ failed, reason: unable to verify the first certificate
FetchError: request to https://api.mywebsite.com/ failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/apollo/node_modules/node-fetch/lib/index.js:1455:11)

FWIW I would get this error in v1.9.1 too, but that version allows me to pass the '-k' flag to basically force the CLI to accept the certificate without verification. To my knowledge this flag no longer exists in Apollo CLI v2.0 and above. 

Some reports of similar errors online point to some javascript package the CLI depends on expecting a certain format for the SSL certs (It might be problematic because I have a wildcard SSL cert for my domain).

Given that I can't really change that format, I need a way to either force the client to accept the certs or Apollo needs to be able to handle these certs.

**Comment by AttilaTheFun** [comment]
Oh great! That worked. I think the online docs for the schema:download command don't include those params, but --help works.

**Comment by JakeDawkins** [comment]
Yay! Glad it worked 😄

**Comment by woeterman94** [comment]
Got the same issue :( 
  request to https://localhost:44303/ failed, reason: unable to verify the first certificate

**Comment by CezarCrintea** [comment]
@woeterman94  set NODE_TLS_REJECT_UNAUTHORIZED=0

**Comment by webmakaka** [comment]
Hello!
I have the same issue:

```
$ apollo schema:download --endpoint=https://tinyhouse.dev/api --skipSSLValidation schema.json
  ✔ Loading Apollo Project
  ✖ Saving schema to schema.json
    → FetchError: request to https://tinyhouse.dev/api failed, reason: unable to
…
    Error: FetchError: request to https://tinyhouse.dev/api failed, reason: 
    unable to verify the first certificate
```

tinyhouse.dev i specify in hosts file.

Here is my project:
https://github.com/webmakaka/TinyHouse-A-Fullstack-React-Masterclass-with-TypeScript-and-GraphQL

$ apollo --version
apollo/2.32.0 linux-x64 node-v12.20.0

I think it worked half of year ago. But i am not sure.

Any suggestions?

**Comment by CezarCrintea** [comment]
$ NODE_TLS_REJECT_UNAUTHORIZED=0 && npx apollo client:download-schema --endpoint=https://localhost:5001/graphql --includes=src/**/*.ts is not working? I just tested it now. --skipSSLValidation is not working anymore

**Comment by webmakaka** [comment]
```
$ NODE_TLS_REJECT_UNAUTHORIZED=0 && npx apollo client:download-schema --endpoint=https://tinyhouse.dev/api --includes=src/**/*.ts
```

![Screenshot from 2021-01-02 13-37-23](https://user-images.githubusercontent.com/10372159/103455730-7567ae80-4d00-11eb-873a-843c02fbccf2.png)

May be something wrong with my [apollo.config.js](https://github.com/webmakaka/TinyHouse-A-Fullstack-React-Masterclass-with-TypeScript-and-GraphQL/blob/master/app/client/apollo.config.js)?

**Comment by vkmita** [comment]
Please reopen this issue. I am experiencing this issue as well!

**Comment by antikvarBE** [comment]
Yes, same here.

**Comment by zicodeng** [comment]
Same here, I think the recent release has caused...

**Comment by EduardoLwx** [comment]
I made a downgrade to 2.29.0. This version is ok

**Comment by shevchenkonik** [comment]
The same problem with the 3 version.
