### ISSUE TITLE
Custom added via apollo.config.js are ignored.

### ISSUE THREAD

**Issue by andsee** [apollographql/apollo-tooling#1601]
**Intended outcome:**

When adding a custom directive via clientOnlyDirectives vscode plugin should no longer complain about it being an unknown directive.

**Actual outcome:**

GraphQLSchemaValidationError: Unknown directive "function". error reported and plugin unable to initialize.

**How to reproduce the issue:**
Define a schema with a custom directive (for example @function used by AppSync):

`type Query {
	getInvites(userId: ID): String @function(name: "AppSyncRDSLambda-${env}")
}`

Ensure your apollo.config.js contains:
`module.exports = {
    client: {
        clientOnlyDirectives: ["function"],
....`

Note that the plugin will complain about the function directive being unknown and hence not validate the schema.

**Versions**

Apollo GraphQL 1.11.0
VSCode 1.39.2

**Comment by JakeDawkins** [comment]
@andsee if you're trying to use a custom directive, you still need it defined in SDL somewhere. For example, Relay has a couple custom directives that are used on the client, but for the extension to know about their usage (where they're allowed, on what types, etc), you'd still need to define them and include that SDL file in your `client.includes` list.

For example,

```graphql
# directives.graphql
directive @myClientOnlyDirective(field: String!) on FIELD
```

```javascript
// apollo.config.graphql
module.exports = {
  client: {
    name: 'My Client Project',
    includes: ['src/**/*.graphql', './directives.graphql'],
  ...
```

The [apollo-vscode-relay](https://github.com/relay-tools/vscode-apollo-relay) package does this for relay projects, but I'm not sure if there's something similar for appsync projects.

But I think this will solve your problem, so I'll close this issue for now. Let me know if not :)
