### ISSUE TITLE
service:push does not update the Federated serviceURL when the schema hasn't changed

### ISSUE THREAD

**Issue by nihalgonsalves** [apollographql/apollo-tooling#1639]
**Intended outcome:**

`service:push` allows the `serviceURL` to be updated independent of schema changes

**Actual outcome:**

You must make a schema change before a `serviceURL` update takes effect

**How to reproduce the issue:**

```sh
# first:
apollo service:push --localSchemaFile test.graphql --serviceURL=http://a.example.com/graphql --serviceName test
# this doesn't update the URL on Graph Manager
apollo service:push --localSchemaFile test.graphql --serviceURL=http://b.example.com/graphql --serviceName test
# however if you change test.graphql in any way, and then re-run the command, it works
```

**Versions**

`apollo/2.21.0 darwin-x64 node-v12.12.0`

**Comment by zionts** [comment]
This was indeed an issue, but it has since been resolved. If you encounter this again, please reopen this ticket and feel free to `@` me!
