### ISSUE TITLE
apollo-env requires @types/node-fetch to compile

### ISSUE THREAD

**Issue by vcfvct** [apollographql/apollo-tooling#1670]
**Intended outcome:**
Should compile without having to install `@types/node-fetch`

**Actual outcome:**
getting compile error
`node_modules/apollo-env/lib/fetch/fetch.d.ts(6,195): error TS7016: Could not find a declaration file for module 'node-fetch'.`

**How to reproduce the issue:**
do a `tsc` with apollo-env or `apollo-server-core` as dependency.

**Versions**
`0.6.0`

**Comment by yvann** [comment]
I have the same error 👍

**Comment by AndrewKvalheim** [comment]
PR: #1701

**Comment by glen-84** [comment]
@trevor-scheer I believe that this was fixed by #1749 (the above PR can also be closed).

**Comment by trevor-scheer** [comment]
Thanks for reporting, @glen-84!
