### ISSUE TITLE
[TypeScript] Could not find a declaration file for module 'node-fetch'

### ISSUE THREAD

**Issue by kripod** [apollographql/apollo-tooling#1686]
When using `apollo-env` through `apollo-server`, I get the following error during TypeScript builds:

```
node_modules/apollo-env/lib/fetch/fetch.d.ts(6,195): error TS7016: Could not find a declaration file for module 'node-fetch'
```

This can be fixed by adding `@types/node-fetch` as a dependency of `apollo-env`. Or as an alternative, update `node-fetch` to v3, as [it bundles type declarations](https://github.com/bitinn/node-fetch/issues/668) with itself.

**Comment by glen-84** [comment]
Duplicate of #1670 (?)

**Comment by kripod** [comment]
@glen-84 Thank you for noticing! I'm closing this in favor of #1670.
