### ISSUE TITLE
vscode extension: Service stats could not be loaded

### ISSUE THREAD

**Issue by moun3iim** [apollographql/apollo-tooling#1724]
I'm facing a problem with installing vscode extension in typescript server project

![Screenshot from 2019-12-15 20-12-31](https://user-images.githubusercontent.com/44704549/70867641-ec0bff80-1f77-11ea-92d6-7396b9acfd4a.png)

this is my apollo.config.js configs:

```
module.exports = {
    client: {
      service: {
          name: "API",
          url: "http://www.localhost:4000/"
      },
      includes: ["./src/**/*.(ts|js)"],
      excludes: ["**/*.graphql"]
    }
  };
```

**Comment by PuffCab** [comment]
Hey @ghost , you marked this issue as completed. which was your solution?
