### ISSUE TITLE
[codegen] add @generated pragma to generated files

### ISSUE THREAD

**Issue by slonoed** [apollographql/apollo-tooling#1727]
We use Phabricator as a diff tool and code management. It supports `// @generated` comment on top of the file and marks such file as generated for diffs. Would be cool if codegen add this comment to type files.

**Comment by JakeDawkins** [comment]
Hey @slonoed! Thanks for opening this. I don't see any issue with adding this. Should it be applied to all file types, not just flow/ts?

**Comment by slonoed** [comment]
Hi @JakeDawkins 

Done in #1748
