### ISSUE TITLE
Respect .env

### ISSUE THREAD

**Issue by jjangga0214** [apollographql/apollo-tooling#1759]
It'd be cool if vscode extension respects `.env` file, so env vars can be consumed.
 
```js
// apollo.config.js
module.exports = {
  client: {
    service: {
      name: "foo",
      url: process.env.LOCAL_SERVER_GRAPHQL_ENDPOINT,
    }
  }
}
```

**Comment by benjamin-rood** [comment]
You should be able to add the following call

    require('dotenv-flow').config();

before you define `module.exports` to load ENV vars.

**Comment by xdemocle** [comment]
issue might be related to the editor. in my vase I have same issues in visual studio code

**Comment by JakeDawkins** [comment]
FWIW, I don't see this happening anytime soon, as we'll almost certainly be reworking how these projects are configured in the near future. So while this is a good idea, since it's a JS file, requiring the env file from `dotenv` as recommended above is probably the best bet for now :)
