### ISSUE TITLE
apollo:codgen --includes does not correctly handle brace expansion in conjuction with glob

### ISSUE THREAD

**Issue by MichaelHindley** [apollographql/apollo-tooling#1781]
**Intended outcome:**

`apollo codegen:generate ./src/GraphQL/__generated__/schemaTypes.ts --outputFlat --includes=src/GraphQL/{Queries,Mutations,Subscriptions}/*.ts --target=typescript --endpoint=http://localhost:5000/graphql"` generates types for Queries, Mutations and Subscriptions as per the instructed brace expansion.
**Actual outcome:**

It generates types only for the last entry, in this case, `Subscriptions`.

**How to reproduce the issue:**

I set a flag at codegens.js#30
![image](https://user-images.githubusercontent.com/1016639/73262097-b8a2ce80-41cd-11ea-8592-957b676f4233.png)

argv correctly holds all the paths based on the glob with brace expansion as per https://www.gnu.org/software/bash/manual/html_node/Brace-Expansion.html for bash and http://zsh.sourceforge.net/Doc/Release/Expansion.html#Brace-Expansion for zsh.

![image](https://user-images.githubusercontent.com/1016639/73262130-cd7f6200-41cd-11ea-9bc7-f96225b711a5.png)

However, the `flags`variable only holds the last member of `includes` after `const { flags: { watch }, args: { output } } = this.parse(Generate);`, making apollo:codegen ignore the other directories

![image](https://user-images.githubusercontent.com/1016639/73262212-f30c6b80-41cd-11ea-853d-7fdbd3168897.png)
Resulting in only subscription types in `schemaTypes.js`.

On my colleagues computer that runs Win10, but otherwise identical shell and packages, the `includes` param holds the original glob pattern with the brace expansion syntax intact, i.e `--includes` is only 1 single entry instead of 3 brace expanded ones, and everything works as expected.

**Versions**
node v12.14.1
MacOs Catalina
zsh
bash

```json
{
  "name": "apollo",
  "description": "Command line tool for Apollo GraphQL",
  "version": "2.21.1",
  "referenceID": "21ad0845-c235-422e-be7d-a998310df972",
  "author": "Apollo GraphQL <opensource@apollographql.com>",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/apollographql/apollo-tooling.git"
  },
  "homepage": "https://github.com/apollographql/apollo-tooling",
  "bugs": "https://github.com/apollographql/apollo-tooling/issues",
  "files": [
    "/bin",
    "/lib",
    "/oclif.manifest.json"
  ],
  "main": "lib/index.js",
  "types": "lib/index.d.ts",
  "bin": {
    "apollo": "./bin/run"
  },
  "scripts": {
    "prepack": "oclif-dev manifest && oclif-dev readme",
    "postpack": "rm -f oclif.manifest.json",
    "version": "oclif-dev readme && git add README.md"
  },
  "engines": {
    "node": ">=8",
    "npm": ">=6"
  },
  "dependencies": {
    "@apollographql/apollo-tools": "^0.4.1",
    "@oclif/command": "1.5.19",
    "@oclif/config": "1.13.3",
    "@oclif/errors": "1.2.2",
    "@oclif/plugin-autocomplete": "0.1.4",
    "@oclif/plugin-help": "2.2.1",
    "@oclif/plugin-not-found": "1.2.3",
    "@oclif/plugin-plugins": "1.7.8",
    "@oclif/plugin-warn-if-update-available": "1.7.0",
    "apollo-codegen-core": "^0.35.8",
    "apollo-codegen-flow": "^0.33.33",
    "apollo-codegen-scala": "^0.34.33",
    "apollo-codegen-swift": "^0.35.13",
    "apollo-codegen-typescript": "^0.35.8",
    "apollo-env": "^0.6.0",
    "apollo-graphql": "^0.3.5",
    "apollo-language-server": "^1.17.1",
    "chalk": "2.4.2",
    "env-ci": "3.2.2",
    "gaze": "1.1.3",
    "git-parse": "1.0.3",
    "git-rev-sync": "1.12.0",
    "glob": "7.1.5",
    "graphql": "14.0.2 - 14.2.0 || ^14.3.1",
    "graphql-tag": "2.10.1",
    "listr": "0.14.3",
    "lodash.identity": "3.0.0",
    "lodash.pickby": "4.6.0",
    "moment": "2.24.0",
    "strip-ansi": "5.2.0",
    "table": "5.4.6",
    "tty": "1.0.1",
    "vscode-uri": "1.0.6"
  },
  "devDependencies": {
    "typescript": "3.6.4"
  },
  "oclif": {
    "commands": "./lib/commands",
    "bin": "apollo",
    "plugins": [
      "@oclif/plugin-help",
      "@oclif/plugin-not-found",
      "@oclif/plugin-plugins",
      "@oclif/plugin-warn-if-update-available"
    ],
    "repositoryPrefix": "<%- repo %>/blob/master/packages/apollo/<%- commandPath %>"
  },
  "gitHead": "4eea9a99d77e426e5fd03594fadbb4ed6d716da4"
}
```

**Comment by JakeDawkins** [comment]
Thanks for the detailed issue!

This looks to be a bug, and I can reproduce it locally. I'll try to take a look today and see what I can find out.

**Comment by JakeDawkins** [comment]
Ah, yeah, so it looks like this isn't actually a bug, but rather the shell just using brace expansion before the node app is actually receiving it. Since the `includes` flag isn't one that can be specified multiple times, only a single time with a  comma-separated-list, the expansion is passing it multiple times with the different values like you listed. This _shouldn't_ work after all.

For more: http://www.tldp.org/LDP/Bash-Beginners-Guide/html/sect_03_04.html

**Comment by JakeDawkins** [comment]
To still use this, you can just put double quotes around the argument like 

```
apollo codegen:generate ./src/GraphQL/__generated__/schemaTypes.ts --outputFlat --includes="src/GraphQL/{Queries,Mutations,Subscriptions}/*.ts" --target=typescript --endpoint=http://localhost:5000/graphql
```
