### ISSUE TITLE
Error: ServerParseError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by aarshaw** [apollographql/apollo-tooling#1784]
Trying to push a localSchema to Apollo Engine and falling at the first hurdle:

From the docs it looks as if given the following repo:
https://github.com/aarshaw/apollo-push-issue

I could run:
```
npx apollo service:push --localSchemaFile=schema.graphql
```
to push my schema to that service, however I recieve the following error message:
```
  ✔ Loading Apollo Project
  ✖ Uploading service to Apollo Graph Manager
    → ServerParseError: Unexpected end of JSON input
Error: ServerParseError: Unexpected end of JSON input
    at apollo_link_1.toPromise.catch.e (~/Desktop/test/node_modules/apollo-language-server/lib/providers/schema/endpoint.js:61:19)
```
any pointers or examples of how to do this would be much appreciated! Cheers!

**Comment by musemind** [comment]
I have the same problem.

**Comment by JakeDawkins** [comment]
@aarshaw Thanks for opening this, and sorry for the delay! Your config is setup as a `client` project, but you're trying to run a `service` command.

I know the distinction is a bit confusing with how the cli is set up right now. Try changing your config to look something like

```
module.exports = {
  service: {
	name: 'my-service-name'
  }
}
```

@musemind I have a feeling you may be running into a similar issue. if you are running any `service:*` command, you should have a `service` key at the top level of your config (assuming you have one), and vise versa for `client:*` commands.

Let me know it that doesn't make sense/solve the issue, and I can reopen this :)
