### ISSUE TITLE
apollo client:download fails if OUTPUT doesn't exist

### ISSUE THREAD

**Issue by mayteio** [apollographql/apollo-tooling#1788]
**Intended outcome:**
Should download the schema file, then put it in the OUTPUT argument, even if the folder specified doesn't exist.

**Actual outcome:**
My cli command:
`apollo client:download-schema ./src/__generated__/schema.json` fails when `__generated__` folder doesn't exist.

**How to reproduce the issue:**
pass a filepath with a folder that doesn't exist as the OUTPUT .

I can trace that back the [`writeFileSync` call](https://github.com/apollographql/apollo-tooling/blob/4336cd27480a3bbf363e63ea179b1e234d017812/packages/apollo/src/commands/client/download-schema.ts#L39) in `download-schema.ts` as the culprit, where `writeFileSync` will throw if a folder doesn't exist.

[This stackoverflow](https://stackoverflow.com/questions/16316330/how-to-write-file-if-parent-folder-doesnt-exist) article points to two solutions - one using `mkdirp` and one using `fs-extra`, or [this answer without additional packages](https://stackoverflow.com/a/34509653/11751844). I would like to contribute a fix to this (if you'll have one) and was wondering if there was a preference on how to solve it? Or maybe this is desired behaviour?

I believe this is important because we store generated artifacts in a `__generated__` folder, which we do not want to check into github.

Any help appreciated!

**Versions**
`apollo/2.22.0 darwin-x64 node-v13.6.0`

[Possibly related](https://github.com/apollographql/apollo-tooling/issues/792)

**Comment by JakeDawkins** [comment]
Yeah, this would be a great add! I think it should be a simple enough add. I'm going to look at adding this hopefully today :)
