### ISSUE TITLE
Apollo GraphQL vscode extension will panic when view git diff 

### ISSUE THREAD

**Issue by shynome** [apollographql/apollo-tooling#1789]
**Intended outcome:**

no panic when view git diff

**Actual outcome:**
panic when view git diff 

**How to reproduce the issue:**

add the blow content to `a.ts` and commit it to git , then use editor git diff view diffrence, the extension panic and throw error: ` ️️There are multiple definitions for the GetGithubConfig operation. All operations in a project must have unique names. If generating types, only the types for the first definition found will be generated.`
```ts
import { gql } from '@apollo/client'
let a = gql`
query something {
hello world
}
`
```

**Versions**

1.14.0

**Comment by m-haketa** [comment]
I tried git diff on my Windows 10 PC and got the same error too, but it worked fine when using WSL.

**Comment by m-haketa** [comment]
I tried again using WSL and got the same error too.

**Comment by felixfbecker** [comment]
Seeing the same every time I review the changed files in VS Code.

![image](https://user-images.githubusercontent.com/10532611/83752886-946a6900-a669-11ea-9f8b-e545b66ec43b.png)

**Comment by nibtime** [comment]
There is an open unmerged [PR](https://github.com/apollographql/apollo-tooling/pull/1894) that fixes that problem.
To get rid of this as a workaround you can manually apply the fix in your VS Code extensions folder in the following file:
`apollographql.vscode-apollo-1.16.0/node_modules/apollo-language-server/lib/project/base.js`

**Comment by m-haketa** [comment]
Thank you so much for telling me about the PR.
I applied the fix manually and it worked fine!

**Comment by rygar08** [comment]
This issue continues on windows 10 vscode for extension Apollo GraphQL. Really want to use this extension.

**Comment by chinanderm** [comment]
Any update on this?

**Comment by airtonix** [comment]
still happening
