### ISSUE TITLE
JSON codegen output: Please output types as nested JSON instead of a stringified type

### ISSUE THREAD

**Issue by designatednerd** [apollographql/apollo-tooling#1814]
In JSON for schemas, we presently output whether something is an optional or not in the following format: 

```json
"type": {
  "kind": "LIST",
  "name": null,
  "ofType": {
    "kind": "NON_NULL",
    "name": null,
    "ofType": {
      "kind": "LIST",
      "name": null,
      "ofType": {
        "kind": "NON_NULL",
        "name": null,
        "ofType": {
          "kind": "SCALAR",
          "name": "Float",
          "ofType": null
        }
      }
    }
  }
}
```

This is verbose as hell, so in the output of JSON from `codegen:generate`, we instead get the stringified TypeScript type: 

```json
"type": "[[Float!]!]",
```

The problem is that this is not super-helpful for working with Swift, where `!` indicates a force-unwrap instead of `non-null`, no annotation represents `non-null` instead of `nullable`, and `?` indicates `nullable`.

Can we please update the output of the AST in JSON to use the hideous nested JSON instead of the stringified type so that I can more easily parse this into something that will work with Swift? Thank you!

**Comment by jbaxleyiii** [comment]
@JakeDawkins this is a blocker for @designatednerd's work on the swift codegen re-write. Can you take a look at this? Happy to help pair on any questions

**Comment by designatednerd** [comment]
@JakeDawkins This is working in the `fragments` and `operations` dictionaries, but is not with the `typesUsed` dictionary. Output of the Star Wars API: [API.json.zip](https://github.com/apollographql/apollo-tooling/files/4512745/API.json.zip)

**Comment by designatednerd** [comment]
Additionally related to this: The `NamedType` type embeds a `Name` type that doesn't just give the value of the name, but another dictionary. This leads to some really confusing recursion practices. 

For example, to get a non-null type, we presently have: 
```json
"typeNode": {
  "kind": "NonNullType",
  "type": {
    "kind": "NamedType",
    "name": {
      "kind": "Name",
      "value": "String"
    }
  }
}
```

I would vastly prefer to have: 

```json
"typeNode": {
  "kind": "NonNullType",
  "type": {
    "kind": "NamedType",
    "value": "String"
  }
}
```

This way a) We don't have to have a specific `name` variable b) We don't need separate kinds for `Name` and `NamedType`.

**Comment by designatednerd** [comment]
`typesUsed` is now working. The other thing is a nice-to-have but not absolutely necessary, and it sounds like it'd be a giant pain in the ass so let's punt on it for now.
