### ISSUE TITLE
Allow exit 0 on errors reported by schema check

### ISSUE THREAD

**Issue by pcarrier** [apollographql/apollo-tooling#1852]
It'd be great to have a `apollo schema:check` option to exit 0 if the check finished, even if it returned errors, so we can fail in CI when the checks are broken, but not when they report errors. The build should be green in GitHub, the Apollo checks are where the red goes.

OTOH, ignoring the command exit code means we don't catch checks being broken in other ways (invalid command, bad API key, service is down, etc.).

**Comment by zionts** [comment]
@pcarrier happy to support this feature! Are you thinking about a CLI flag? Would you be interested in contributing a solution? I'd be happy to get you spun up and collaborate on it :)

**Comment by pcarrier** [comment]
`--ignore-returned-errors`?
