### ISSUE TITLE
`npm i apollo` fail

### ISSUE THREAD

**Issue by chereseeriepa** [apollographql/apollo-tooling#1900]
**Intended outcome:**
I was trying to run `npm i apollo` to install the apollo cli

**Actual outcome:**
I received an error:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @apollographql/apollo-tools@^0.4.6.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'apollo'
npm ERR! notarget 

```

**How to reproduce the issue:**
delete `node_modules` and run `npm i apollo`again.

**Versions**
Latest

**Comment by mccolljr** [comment]
Same issue using `yarn global add apollo`, just broke our production deploy pipeline.

**Comment by parkerself22** [comment]
@chereseeriepa you beat me to it, was just about to report this. Here are all the resolution errors (without stacktraces) from `yarn global add apollo`:
```
error Couldn't find any versions for "@apollographql/apollo-tools" that matches "^0.4.6"
Error: Couldn't find any versions for "apollo-codegen-core" that matches "^0.36.7"
Error: Couldn't find any versions for "apollo-codegen-flow" that matches "^0.34.7"
Error: Couldn't find any versions for "apollo-env" that matches "^0.6.3"
Error: Couldn't find any versions for "apollo-codegen-swift" that matches "^0.36.7"
Error: Couldn't find any versions for "apollo-graphql" that matches "^0.4.2"
Error: Couldn't find any versions for "apollo-language-server" that matches "^1.21.2"
Error: Couldn't find any versions for "apollo-codegen-scala" that matches "^0.35.7"
Error: Couldn't find any versions for "apollo-codegen-typescript" that matches "^0.36.7"
```

**Comment by mdiniz** [comment]
It seems this commit should have released 0.4.6 but it was not released: https://github.com/apollographql/apollo-tooling/commit/0bd6c257519fee6d836dc1c833cdcc3c60266a60

**Comment by SeaLife** [comment]
I was just about to start a VueJS project, but sadly, VueJS has a dependency to apollo which prevents me from installing the vue cli :/

```
npm install -g @vue/cli @vue/cli-service-globa
l
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @apollographql/apollo-tools@^0.4.6.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'apollo'
npm ERR! notarget
```

**Comment by Phoscur** [comment]
So this is a release gone wrong, with versions missing like this one? https://github.com/apollographql/apollo-tooling/commit/93e1af1881e45b2926cac196668f2f6bec1ca991#r38572282

Refs https://github.com/vuejs/vue-cli/issues/5403

**Comment by ccortezaguilera** [comment]
Based on [https://circleci.com/gh/apollographql/apollo-tooling/50286](url) seems like it was a problem with not releasing on a commit with `Release`

**Comment by swac** [comment]
We're working around this by pinning our version in CI via `yarn global add apollo@2.27.0`.

**Comment by zionts** [comment]
Thank you for reporting this issue! We're looking into this now and seeing how we can patch up the missed releases to fix this issue as quickly as possible.

**Comment by zionts** [comment]
We have taken down the faulty `2.27.2` release so `latest` should not be pointing back to `2.27.0` and `npm i apollo` should function as expected. Thank you again @chereseeriepa for opening the issue, and much thanks to everyone here for some sleuthing into what the underlying problem is as well as some patience while we resolved it.

Things should be resolved for now and we'll come back to this and see how we can improve our release pipeline and monitoring of it to catch this without needing to leave you all scratching your heads!

**Comment by BasilaryGroup** [comment]
Our GitL*b CI/CD pipeline is working. Thanks, everyone!

**Comment by curio77** [comment]
For me, `npm audit fix` still tries to pull in `@apollographql/apollo-tools@^0.4.6` for some reason, yielding the above error.  This is with `apollo` in `node_modules` being v2.27.0.

**Comment by abernix** [comment]
@curio77 @vanwalj Can you try again now?

**Comment by curio77** [comment]
Seems fixed. :+1:
