### ISSUE TITLE
apollo client:codegen --target typescript gives TypeError: context.getErrors is not a function

### ISSUE THREAD

**Issue by anark** [apollographql/apollo-tooling#1947]
**Intended outcome:**

I am intending to export my graphql types to typescript types using
```apollo client:codegen --target typescript```
I expect to generate types in the __generated__ folder
My Apollo client is running on @apollo/client v3.0.beta

**Actual outcome:**
I get the following error
```TypeError: context.getErrors is not a function
    at getValidationErrors (node_modules/apollo-language-server/lib/errors/validation.js:25:20)
    at Object.validateQueryDocument node_modules/apollo-language-server/lib/errors/validation.js:30:34)
    at Object.generate [as default] (node_modules/apollo/lib/generate.js:23:18)
    at write node_modules/apollo/lib/commands/client/codegen.js:78:54)
    at Task.task (node_modules/apollo/lib/commands/client/codegen.js:98:46)
```
 
**How to reproduce the issue:**

Run apollo codegen against a react app using @apollo/client v3.0.beta

**Versions**
   apollo cli 2.27.4
  @apollo/client v3.0.beta

**Comment by juliovedovatto** [comment]
@anark I faced this issue when using `graphl@15` dependency. I believe if you downgrade to version `graphql@14`, will sove the issue. 

That did the trick in my case.

**Comment by anark** [comment]
Downgrading to graphql@14 solved this.  Is there anyway to fix this to make it compatible with graphql@15?

**Comment by MoSattler** [comment]
Get the same. But when I downgrade to 14, I get this
```bash
Error: Cannot use GraphQLObjectType "Query" from another module or realm.
Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.
https://yarnpkg.com/en/docs/selective-version-resolutions
Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
```

**Comment by juliovedovatto** [comment]
@abernix I noticed your made a new release of `apollo-language-server`, but I'm still getting error when using codegen with typescript support, using `graphql@15.0.0`

This line: https://github.com/apollographql/apollo-tooling/blob/master/packages/apollo-language-server/src/errors/validation.ts#L63

```
typeError: context.getErrors is not a function
```

Could you take a look, please?

**Comment by benhjames** [comment]
PR #1908 fixes this 🙂

**Comment by hamzahsn** [comment]
@benhjames  unfortunately this PR is not yet merged so we cannot upgrade to it yet 😞

**Comment by abernix** [comment]
@anark @hamzahsn:

I'm copying and pasting the comments from @trevor-scheer on #1908 so you make sure you see them and can help test:

> Update: The releases associated with [this change](https://github.com/apollographql/apollo-tooling/pull/1743) can be found on the `next` dist-tag for the following packages.
> 
> • `apollo-graphql@0.5.0-alpha.0`
> • `apollo-language-server@1.23.0-alpha.0`
> • `apollo@2.29.0-alpha.0`
> 
> To install the CLI from the `next` dist-tag, for example:
> `npm i -D apollo@next`
> 
> I'll be closing this PR in favor of the previously mentioned PRs. Thanks again @benhjames for the help with this!
> 
> Please try them out and provide feedback on the release PR #2032. Barring any issues I'll release this officially before the end of the week.

Please try the `next` versions and report back with updates!

**Comment by juliovedovatto** [comment]
Just an update: I was following #1908 and now I'm using `apollo@next` package.

It is working with GraphQL 15 as expected for the project I'm working on.

**Comment by trevor-scheer** [comment]
Thanks for the update @juliovedovatto! I'm preparing the release to `latest` as we speak, so expect to see `apollo@2.29.0` in the next 10 minutes or so.

**Comment by rainysiu** [comment]
"apollo": "^2.29.0" works
