### ISSUE TITLE
Gql [Something]! should translate to "something[] | null"

### ISSUE THREAD

**Issue by micksi** [apollographql/apollo-tooling#1966]
**Intended outcome:**
Graphql type `[Something]!` should resolve to the following type `something[] | null` in typescript

**Actual outcome:**
Graphql type `[Something]!` instead resolves to `(something|null)[]` in typescript

**How to reproduce the issue:**
This graphql type
```gql
type ArtikelCollection {
total: Int!
skip: Int!
limit: Int!
items: [Artikel]!
}
```

outputs the following typescript interface 
```ts
export interface artikel_artikelCollection {
  __typename: "ArtikelCollection";
  items: (artikel_artikelCollection_items | null)[];
}
```

To my knowledge null[] is an invalid graphql type as any null value would translate directly to just null and not list of null. But the generated type indicates that it could be as list of null (null[]) when it should have been just a null value. 

The bug makes it extremely annoying to access anything in the array since the typescript thinks it could be a list of null and therefore ! (non-null) must be used even though null checks have been already have been made.

**Comment by vlindhol** [comment]
@micksi the generated types are correct, in Graphql `[Something]!` means that we will always get an array, and each element of this array is either `Something` or `null`. So valid values are e.g.

* `[Something, Something, Something]`
* `[Something, null, Something]`
* `[null, null, null]`

If you want the Typescript equivalent of `something[] | null`, that would in GraphQL be `[Something!]`. There is also `[Something!]!`, which would in typescript become `something[]` (so no nulls anywhere).
