### ISSUE TITLE
Swift Access Level Codegen

### ISSUE THREAD

**Issue by schlossmichael** [apollographql/apollo-tooling#1982]
# Motivation

Often, library authors wish to hide specific implementation details and/or manipulate data before exposing it to a client.  GraphQL types being public can cause API surface leaks, possibly resulting in the inability to guarantee API stability and ability for client to manipulate data outside of the library’s control.

We believe it’s important for a library author to have full control over their API surface.

#278 is the only other official example of an issue being opened for access levels, however we don't feel it's an uncommon ask.

# Problem

GraphQL types being `public` is fine when a project a single-target, or if the library developer intends for the generated types to be publicly exposed.  It breaks down if the developer does not wish to expose the types outside of a library, whether within its own app or distributed to clients.

To combat this, a developer's code generation script needs to have a `sed` (or similar CLT) rewrite in it to change everything from `public` -> `<NewAccessLevel>`.  This is problematic because there are few restrictions as to where the phrase `public` can exist, which requires the developer to come up with a clever solution to only replace the modifier.

For example, the following declarations are valid uses of `public` that without special consideration could be replaced incorrectly:

`public class Foo`

`public let/var bar: Foo`

`public class 'public'` (due to GitHub markdown, treat the apostrophes as backticks)

`public let/var 'public': Foo` (due to GitHub markdown, treat the apostrophes as backticks)

`public let/var publicBar: Foo`

# Solution
Pull Request: #1981

The ideal solution is to allow a user to specify an access level at codegen-time.  This way the generated Swift source will come with the requested access level.

To do this, we propose adding a `--swiftAccessLevel` argument to the codegen command line tool.  A user will then be able to specify `public`, `internal`, or `private` (although `private` wouldn't make too much sense as types and properties would not be exposed outside of their definitions).  A non-existent argument would default to `public` to maintain source compatibility.

# Alternatives Considered

A do-nothing alternative was considered.  As evidenced by there being only 1 previous issue which mentioned access levels in Swift, this is not a large "official" ask.  Ultimately though, we felt it should be the responsibility of the codegen tool to generate types and properties with a desired access level, rather than having to work around or ignore it.

An alternative was considered in which `public` was replaced with `internal` (or nothing to have default `internal`).  This idea was ultimately not moved forward with as it breaks source compatibility, and some workarounds may depend on types continuing to be `public`.

**Comment by designatednerd** [comment]
Hi! So this is actually something I've got going in the [Swift Codegen Project](https://github.com/apollographql/apollo-ios/projects/2) - basically, we're moving the portion of codegen which actually generates Swift code from Typescript to Swift. 

It's definitely still a work in progress and I don't quite have an ETA, but I've already [added support for an access modifier option](https://github.com/apollographql/apollo-ios/blob/master/Sources/ApolloCodegenLib/ApolloCodegenOptions.swift#L40), and I'm making sure to test new code generates with the appropriate modifier or lack thereof. 

Is this something you'd be willing to punt on until that gets released, or is there an urgent need for it? Wanted to check in on that before I start reviewing the PR that you've got going.

**Comment by schlossmichael** [comment]
@designatednerd that's awesome!.  This is definitely something that can be punted until then (if it's not already there).  I'll go on ahead and close out that PR and this issue can be closed then.

**Comment by fnazarios** [comment]
That solution wasn't implemented yet?

**Comment by designatednerd** [comment]
It will be in the new version of codegen slated to come out in the current quarter. Please see the [RFC in the Draft PR](https://github.com/apollographql/apollo-ios/pull/1876) for further details.
