### ISSUE TITLE
codegen:generate conflicting with schema.json on iOS project

### ISSUE THREAD

**Issue by beaneyios** [apollographql/apollo-tooling#2034]
**Intended outcome:**
When I run `"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" API.swift`, it should create an API.swift file with my generated models.

**Actual outcome:**
The build fails, because it is conflicting with the model references already in the schema, e.g:

```
 ›   Error: Error initializing Apollo GraphQL project "Unnamed Project": Error: 
 ›   Error in "Loading schema for Unnamed Project": Error: Field 
 ›   "Mutation.registerUser" already exists in the schema. It cannot also be 
 ›   defined in this type extension.
 ›
 ›   Type "User" already exists in the schema. It cannot also be defined in 
 ›   this type definition.
 ›
 ›   Field "User.username" already exists in the schema. It cannot also be 
 ›   defined in this type extension.
 ›
 ›   Field "User.email" already exists in the schema. It cannot also be defined 
 ›   in this type extension.
```

**How to reproduce the issue:**
1. Create a new Xcode project
2. Ensure you have a working local server with GraphQL set up with models (e.g. User).
3. Run `apollo schema:download --endpoint=http://localhost:8080/graphql schema.json` as per the [iOS setup instructions](https://www.apollographql.com/docs/ios/installation/)
4. Add the following run script as per the installation instructions:

```
SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
cd "${SRCROOT}/${TARGET_NAME}"
"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" API.swift
```
5. Run the project.

**Versions**
Apollo CLI version: apollo/2.28.3
Node version: node-v8.11.3
Xcode version: 11.5

**Comment by beaneyios** [comment]
Closing this for now. I think I've misunderstood what the .graphql files are actually for.

**Comment by designatednerd** [comment]
@beaneyios - OK - please feel free to open a thread in our [Spectrum chat](spectrum.chat/apollo/apollo-ios) if you have further questions.
