### ISSUE TITLE
Apollo Graphql - VSCode extension not loading after restart.

### ISSUE THREAD

**Issue by GollyJer** [apollographql/apollo-tooling#2040]
Hi. I'm using all the newest version of the Apollo Graphql extension in Visual Studio Code and having a weird issue where everything works when initially installed but then the extension doesn't load the remove scheme after a vscode restart.

[Here's a stackoverflow post with details](https://stackoverflow.com/q/62920961/25197). Any help is greatly appreciated. Thanks!

**Comment by karatekaneen** [comment]
I ran into the same issue. It required me to uninstall the extension, restart VS code and then install the extension again. Has worked perfectly since I reinstalled it.
