### ISSUE TITLE
Being able to pass request headers to `apollo service:push`

### ISSUE THREAD

**Issue by adikari** [apollographql/apollo-tooling#2202]
I have an Apollo Graphql server running in AWS lambda and can be accessed via API Gateway. The API Gateway is private and requires `x-api-key` before it can be invoked. I am using Apollo Federation. The gateway can be accessed via Authorization Token whereas the implementing service requires API Key. 

It would be nice to be able to pass headers while running `apollo service:push` along side the `serviceUrl`  option so that the gateway can use it to talk to the implementing services. 

It would also be very helpful to be able to pass headers for the `endpoint` option in `service:push` which could be used to resolve the schema.

Something like follows:

![image](https://user-images.githubusercontent.com/1757714/104269921-7f04c980-54eb-11eb-87a0-da1853dd3293.png)

Is there any existing way currently to be able to use a private endpoint that requires API key?

**Comment by andyflatt** [comment]
I have been playing with this today and it works for me:

```
npx apollo service:push \
    --graph=My-Graph-vt422r \
    --key=service:My-Graph-vt422r:QVQqUmbI9I2GFbTb68kUlw \
    --variant=current \
    --serviceName=implementing-service \
    --serviceURL=http://localhost:8020 \
    --endpoint=http://localhost:8020 \
    --header='request-id:helloworld'
```

The documentation is lacking on how to use the header option.

**Comment by adikari** [comment]
@andyflatt to confirm, then the gateway will use that header value to the downstream service when communicating?

**Comment by adikari** [comment]
I double-checked the `--header` option. It is used for intersection only if the `endpoint` for the schema is passed. 
What I am looking for is to pass header options so that the `apollo gateway`  uses it during communicating to implementing services.
