### ISSUE TITLE
Update to latest env-ci version

### ISSUE THREAD

**Issue by mjbyrnes4664** [apollographql/apollo-tooling#2219]
The `env-cli` dependency is currently outdated and contains an insecure version of `execa`. This causes security scans to fail with a critical violation. Please update `env-cli` dependency to the latest version, 5.0.2

**Comment by abernix** [comment]
Thanks for filing this! This is fixed in `apollo@2.32.5` which is now published.

(Worth noting that the dependency under scrutiny was `env-ci` rather than `env-cli` — I've updated the title of this issue accordingly.)
