### ISSUE TITLE
How to push federated services

### ISSUE THREAD

**Issue by kuskoman** [apollographql/apollo-tooling#2249]
**Intended outcome:**

Services extending each other circularly pushed to federated graph.

**Actual outcome:**

Error:
```
 → We are unable to run composition for your graph because a subgraph contains an extend declaration for the type <TYPE> which does not exist in any subgraph.
    Error: We are unable to run composition for your graph because a subgraph contains an extend declaration for the type <TYPE> which does not exist in any subgraph.
```

**How to reproduce the issue:**

I have a graph containing a few services- each is extending at least one other- there is no way to find the 'first' one, not connected to other service. There are relations where service A has type AA, but the type is extended in service B, that has type BB, which is extended in service A. Using 

```
apollo service:push --graph=$APOLLO_GRAPH --variant=$APOLLO_VARIANT --endpoint=$SERVICE_ENDPOINT --serviceName=$SERVICE_NAME --serviceURL=$SERVICE_URL"
```

I am not able to push the graph, because of the error mentioned above. Removing extended types, than adding new ones is not a solution, since we are creating a lot of dynamic environments and we want to have possibility to switch them to managed federations as a CI/CD action.

**Versions**
        `"apollo": "^2.32.5",`

Edit:
I just noticed, that my service was correctly added to apollo studio
![image](https://user-images.githubusercontent.com/15456923/112385013-6127c200-8cef-11eb-8acf-5135a51ac7fd.png)
I will try if it works when all services are added
If so I think that this error message is misleading

**Comment by kuskoman** [comment]
Reopening
I added all services
![image](https://user-images.githubusercontent.com/15456923/112461802-96202d00-8d60-11eb-92a0-cdda9ec9c3be.png)
but schema is still not composed

**Comment by dobrynin** [comment]
I have also just run into this error unexpectedly even though the type that supposedly doesn't exist has been in our federated schema for many months. Any idea?
