### ISSUE TITLE
Error: Cannot find module 'graphql/validation/rules/KnownArgumentNamesRule'

### ISSUE THREAD

**Issue by pavelusov** [apollographql/apollo-tooling#2416]
Hi. When I run command: npx apollo client:codegen .... I have that error: Error: Cannot find module 'graphql/validation/rules/KnownArgumentNamesRule'. What to do?
I tried to install fresh graphql 15.5.1 package. But without results. Rolled back the package to 15.5.0

**Comment by RvanderLaan** [comment]
Same for `apollo schema:publish`

**Comment by pavelusov** [comment]
Was conflicts between Nodejs(installed with brew) and Nodejs(installed with "n" npm package). Removed Nodejs(brew). And it has been fixed
