### ISSUE TITLE
client:codegen generates wrong typescript types for union queries

### ISSUE THREAD

**Issue by toxeus** [apollographql/apollo-tooling#2443]
**Intended outcome:**

In `__generated__/OnlyGamma.ts` only the `Gamma` union variant is mapped into typescript because *only* `Gamma` has been queried.

```typescript
/* tslint:disable */
/* eslint-disable */
// @generated
// This file was automatically generated and should not be edited.

// ====================================================
// GraphQL query operation: OnlyGamma
// ====================================================

export interface OnlyGamma_greek_Gamma {
  __typename: "Gamma";
  gamma: string;
}

export type OnlyGamma_greek = OnlyGamma_greek_Gamma;

export interface OnlyGamma {
  greek: OnlyGamma_greek;
}
```

**Actual outcome:**

In `__generated__/OnlyGamma.ts` the `Alpha` and `Beta` union variants are mapped into typescript even though *only* `Gamma` has been queried. This forces client code to needlessly check `__typename === "Gamma"` before being able to access the `gamma` field.

Moreover, `Alpha` and `Beta` are overlayed into the `OnlyGamma_greek_Alpha` type which has no fields defined. This leaves us with a confusing situation: I can check `__typename` for `Alpha` and `Beta` but I cannot access their fields.

```typescript
/* tslint:disable */
/* eslint-disable */
// @generated
// This file was automatically generated and should not be edited.

// ====================================================
// GraphQL query operation: OnlyGamma
// ====================================================

export interface OnlyGamma_greek_Alpha {
  __typename: "Alpha" | "Beta";
}

export interface OnlyGamma_greek_Gamma {
  __typename: "Gamma";
  gamma: string;
}

export type OnlyGamma_greek = OnlyGamma_greek_Alpha | OnlyGamma_greek_Gamma;

export interface OnlyGamma {
  greek: OnlyGamma_greek;
}
```

**How to reproduce the issue:**

Create `schema.graphql`
```graphql
type Alpha {
  alpha: String!
}

type Beta {
  beta: String!
}

type Gamma {
  gamma: String!
}

union Greek = Alpha | Beta | Gamma

type Query {
  greek: Greek!
}

schema {
  query: Query
}
```

create `query.graphql`

```graphql
query OnlyGamma {
  greek {
    ... on Gamma {
      gamma
    }
  }
}
```

run comand

```bash
yarn apollo codegen:generate --target=typescript --localSchemaFile=schema.graphql --includes=query.graphql
```

inspect `__generated__/OnlyGamma.ts`

**Versions**
apollo/2.33.6 linux-x64 node-v16.6.1

**Comment by FritsvanCampen** [comment]
According to your union type you have no guarantee that `gamma` exists. Greek can be Alpha _or_ Beta _or_ Gamma.

The 'actual' seems correct to me. Checking `__typename` allows you to discriminate the result.

**Comment by FritsvanCampen** [comment]
I don't think that's how unions work. The server would have to know to filter all non-gamma results based on the `... on Gamma` part. I don't think that's how it's typically done.

I'm pretty sure `... on Gamma` just allows you to access the properties of Gamma. It's not an indication to the server that you only want greek of type Gamma.

**Comment by toxeus** [comment]
I have checked the raw GraphQL response and you are right. GraphQL will send empty objects for `Alpha` and `Beta`. Therefore, `client:codegen` works correctly. 

I must admit that the way [tagged unions](https://en.wikipedia.org/wiki/Tagged_union) are implemented in GraphQL is unexpected for me.

@FritsvanCampen thank you for challenging my assumptions! I'm closing this since there's no action required for apollo-tooling.

Duplicate issues: #2433, #2082
