### ISSUE TITLE
Is this repo still under mantianace?

### ISSUE THREAD

**Issue by m1heng** [apollographql/apollo-tooling#2551]
Packages inside this repo is widely used by the community.

But it seems repo is out of human activity for couple of months, issues are left there without replying and only BOT is committing towards this repo.

`Graphql@16` supporting is needed for your users. 

Can someone from the maintenance team stands out and explain what's going on?

**Comment by petr-ujezdsky** [comment]
Just stumbled upon this
https://github.com/apollographql/apollo-tooling/pull/2552/files/de2f287c24ddfd19cde67f5e34a07bcd1c69de77

> **[2022-01-21] Note - Upcoming Deprecation Plans:** We (Apollo) are working towards fully deprecating this repository and its related projects. Most of the functionality in this repository has been replaced by newer projects and the rest will be soon. We'll share detailed migration documentation when everything here is ready to be officially deprecated, but just a heads up in case you're planning on adopting anything here for a new project (which you still can of course if the tooling here works for you - support for this tooling will be a minimal however).

**Comment by m1heng** [comment]
> Just stumbled upon this https://github.com/apollographql/apollo-tooling/pull/2552/files/de2f287c24ddfd19cde67f5e34a07bcd1c69de77
> 
> > **[2022-01-21] Note - Upcoming Deprecation Plans:** We (Apollo) are working towards fully deprecating this repository and its related projects. Most of the functionality in this repository has been replaced by newer projects and the rest will be soon. We'll share detailed migration documentation when everything here is ready to be officially deprecated, but just a heads up in case you're planning on adopting anything here for a new project (which you still can of course if the tooling here works for you - support for this tooling will be a minimal however).

Truly sad about this.

**Comment by japboy** [comment]
According to the alternative, [Rover CLI docs](https://www.apollographql.com/docs/rover/);

> Rover does *not currently* provide client-specific features, such as code generation or client checks. For these features, continue using the [Apollo CLI](https://www.apollographql.com/docs/devtools/cli/).

I am wondering if this means Rover will support the code generation/client checks later or something? Is it better to use [`@graphql-codegen`](https://github.com/dotansimha/graphql-code-generator) instead? But how about client checks? These features also should be  the key of the Apollo ecosystem. I don't know if I should stick with `apollo-tooling` for a while or wait for the new alternative...

https://www.apollographql.com/docs/rover/

**Comment by jonlambert** [comment]
Agreed - the deprecation notice is useful as a warning but it would be good to hear about the specific alternatives the Apollo team has in mind.

**Comment by comp615** [comment]
Seems like @trevor-scheer has been hard at work updating the dependencies here, so there's still some things going on! Would be good to get a maintenance release for all the dependency bumps to keep dependabot happy :)

**Comment by trevor-scheer** [comment]
Not without some struggles, but here we are:
https://github.com/apollographql/apollo-tooling/pull/2612

No ETA, but stay tuned for some major version bumps for compatibility. More details on this PR: https://github.com/apollographql/apollo-tooling/pull/2611

The long term plan is still for this repo to be sunset. I don't want to send the wrong message, but I think until we have a transition plan for everything this repo has to offer, it's helpful to keep things current for now (in particular, support for current versions of graphql and node).

**Comment by trevor-scheer** [comment]
Yes! We recommend `graphql-code-generator`.

Related:
https://github.com/apollographql/apollo-tooling/issues/2614
https://github.com/apollographql/apollo-tooling/issues/2053

**Comment by bit-void** [comment]
Thank you!
