### ISSUE TITLE
Cannot install Apollo on Node 18

### ISSUE THREAD

**Issue by shawn-dsz** [apollographql/apollo-tooling#2666]
**Intended outcome:**

Install apollo cli

**Actual outcome:**

Running `npm i apollo -D` results in:

```
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: @apollo/federation@0.27.0
npm ERR! notsup Not compatible with your version of node/npm: @apollo/federation@0.27.0
npm ERR! notsup Required: {"node":">=12.13.0 <17.0"}
npm ERR! notsup Actual:   {"npm":"8.19.2","node":"v18.12.1"}
```
I dont have this module: @apollo/federation@0.27.0 installed.

**How to reproduce the issue:**

run `npm i apollo` on Node 18.12.1

**Versions**
All Versions

**Comment by hjr3** [comment]
> But I know they're looking at only providing minimal support for this package because they plan to deprecate it.

How do we know they are planning to deprecate it?

**Comment by spawnia** [comment]
This issue is not really fixed yet, since the depedency in the `apollo` package has not been updated. @shawn-dsz would you mind reopening?

**Comment by Jianrong-Yu** [comment]
Will this issue be reopened?
The apollo CLI is just partially deprecated, we still need the `client:codegen` commands to generate the Types
