### ISSUE TITLE
Improve handling of interfaces in typescript type generation

### ISSUE THREAD

**Issue by joearasin** [apollographql/apollo-tooling#412]
I need to put together an explicit sample, but a case that looks something like: 

```
interface Head;
type CatHead implements Head...
type DogHead implements Head...

interface Animal {
   head: Head
}

type Cat implements Animal {
   head: CatHead
}

type Dog implements Animal {
   head: DogHead
}

type Query {
  animal(id: animalId): Animal
}


query {
  animal(id: $animalId){
    head
  }
}
```

will generate unnecessary types of:
`Cat_head_DogHead` and `Dog_head_CatHead`

This can be avoided for type generation by explicitly querying fragments:

```
query {
  animal(id: $animalId){
    ... on Cat {
       head
     }
     ... on Dog {
       head
     }
  }
}
```

But that feels like it should not be necessary.

**Comment by corydolphin** [comment]
Is there any movement on this issue? I think this would be a huge usability improvement
