### ISSUE TITLE
Cannot generate code for Java

### ISSUE THREAD

**Issue by landau** [apollographql/apollo-tooling#420]
- [x] has-reproduction

I am trying to generate Java code, but the following error is returned.

```sh
apollo-codegen --version
0.19.1

apollo-codegen generate src/main/resources/FetchModel.graphql --schema schema.json --target scala --output operation-result-types.java

Invalid values:
  Argument: target, Given: "java", Choices: "swift", "scala", "json", "ts", "ts-modern", "typescript", "typescript-modern", "flow", "flow-modern"
```

Many pieces of documentation state that it is possible (https://www.apollographql.com/docs/#developer-tools).

**Comment by swkumar** [comment]
Hi, is there any progress on this issue?

**Comment by landau** [comment]
Hi, @jbaxleyiii . Why did you close this?
