### ISSUE TITLE
error: Error while fetching introspection query result:

### ISSUE THREAD

**Issue by ZZHHAANNGG** [apollographql/apollo-tooling#427]
run the command get an error, but I can query on the website. Is there any specific requirement  to the server?

apollo-codegen introspect-schema http://localhost/graphql --output schema.json

error: Error while fetching introspection query result: invalid json response body at http://localhost/graphql reason: Unexpected token < in JSON at position 1

**Comment by ZZHHAANNGG** [comment]
I tried to setup a simply graphql API. But, I still got the same error. 

error: Error while fetching introspection query result: invalid json response body at http://localhost:8000/graphql reason: Unexpected token < in JSON at position 1

**Comment by ZZHHAANNGG** [comment]
I setup this sever by using graphene-python tutorial.

http://docs.graphene-python.org/projects/django/en/latest/tutorial-plain/#defining-our-models

**Comment by ApurvaB** [comment]
I am getting the same issue.Any solution for this?

**Comment by sneha1308** [comment]
add slash after the graphql

apollo-codegen introspect-schema http://localhost/graphql/ --output schema.json.

Now run the above command. Hope you will get it.

**Comment by 6ewis** [comment]
@ ZZHHAANNGG @ApurvaB  your backend is probably protected, check that it allows that it doesn't check for authentication

**Comment by ceb-luclin** [comment]
What's crazy is this is what is recommended in the docs:
`module.exports = {
  service: {
    endpoint: {
      url: "http://localhost:4000"
    }
    // OR
    localSchemaFile: './path/to/schema.graphql'
  }
};`
