### ISSUE TITLE
add example commands to README

### ISSUE THREAD

**Issue by deltaskelta** [apollographql/apollo-tooling#462]
I can't seem to figure out how to get a command to work from the docs alone. I am running typescript and I am trying to process my typescript files with gql tags. This is the current command I am trying with the error that it give

```
apollo codegen:generate *.ts --queries=./*.ts
```

```
 ›   Error: Unexpected arguments: fragments.ts, gql.ts, resolvers.ts, types.ts
 ›   See more help with --help
```

**Comment by shadaj** [comment]
Hi! When passing in glob paths, you'll need to wrap the queries argument in quotes. So `apollo codegen:generate *ts --queries="./*.ts"`. I'll add examples to the README that explain this.

**Comment by deltaskelta** [comment]
Ok I see
