### ISSUE TITLE
Short interface names

### ISSUE THREAD

**Issue by danielreichhart** [apollographql/apollo-tooling#471]
If we generate the typescript files, escpecially from nested queries, we get very long interfaces names. Sometimes longer than 70 chars, so its inconvenient to work with these interfaces.
An option in codegen:generate would be very cool, to left out the name prefix.

**Comment by corydolphin** [comment]
This is definitely a pain we experience as well. A namespace per query may make this easier.

**Comment by fseemann** [comment]
Having a namespace for each query would be a nice option.

**Comment by danielreichhart** [comment]
?

**Comment by bmitchinson** [comment]
Any updates on this?
