### ISSUE TITLE
Is it possible to download schema into `.gql` file instead of `.json`?

### ISSUE THREAD

**Issue by pie6k** [apollographql/apollo-tooling#493]
Tools like https://marketplace.visualstudio.com/items?itemName=kumar-harsh.graphql-for-vscode require schema to be defined as `.gql` and `apollo schema:download` supports json only.

**Comment by Slessi** [comment]
```sh
apollo-codegen print-schema --schema=schema.json --output=schema.gql
```

**Comment by pie6k** [comment]
This works but seems like workaround as I need to have only gql file.

**Comment by NLincoln** [comment]
You can use the [graphql-cli](https://oss.prisma.io/content/graphql-cli/03-Using-with-GraphQL-Config.html) to accomplish this.

**Comment by Slessi** [comment]
@NLincoln 

> You can use the graphql-cli to accomplish this.

[codegen.ts#L136](https://github.com/graphql-cli/graphql-cli/blob/master/src/cmds/codegen/codegen.ts#L136)

```js
const binPath = require.resolve('apollo-codegen').replace('index.js', 'cli.js')
```

`graphql-cli codegen` is using `apollo-codegen`

**Comment by pie6k** [comment]
While I'm absolutely aware of being able to use other tools - this issue is about limitation of `apollo-cli` itself.

**Comment by Slessi** [comment]
@pie6k  There are no other tools being used

`apollo-codegen` **is** this library
`graphql-cli codegen` **uses** this library

Subscribe to #501 to see when/if they plan to migrate the missing functionality following their refactor/rename to `apollo-cli`, as that is the only "limitation"
