### ISSUE TITLE
Cannot generate types using `--clientSchema` and `--schema`

### ISSUE THREAD

**Issue by fenech** [apollographql/apollo-tooling#494]
Hi, I am trying to use `apollo codegen:generate` to produce TypeScript definition files. I have a mixture of server- and client-side schema, and I'm not sure how to use the codegen tool in this case.

I have tried making each schema "standalone", defining `schema`, `Query` and `Mutation` types, but this leads to errors like `Type "Query" already exists in the schema. It cannot also be defined in this type definition.` (in this case, because `Query` is in both the client and the server schema). 

I have created a minimal repo to illustrate the issue https://github.com/fenech/apollo-cli-example

**Comment by shadaj** [comment]
Hi! When writing a client-side schema that adds additional fields (to the `Query` type for example), you'll need to use `extend type`. For example:

```
extend type Query {
  myClientSideField: String
}
```

**Comment by aleccool213** [comment]
This took me forever to find, thank you @shadaj .
