### ISSUE TITLE
RFC: apollo queries:record

### ISSUE THREAD

**Issue by jbaxleyiii** [apollographql/apollo-tooling#496]
## Query recording

This is an RFC after a discussion with @adamrneary for a feature which would allow recording of queries used by an application with an arbitrary set of variables. The use case, though wide, should first be focused on data generation for mocking of UI in storybook and for testing suites.

### Design

The basic idea is to extract all, or a subset, of operations from a front-end code base, execute them an arbitrary set of times with given variable patterns, and store the resulting data in a `__generated__/data.js` file right next to the source file (not at a root __generated__). These generated data sets would be stored in version control and rerun when queries changes on the front end (after prompting). 

The use case here is to use Apollo connected components outside of a running server. Mocked data can be used for storybook development, to create a fully mocked server, test suites, and more.

### Design considerations

Extraction of queries is currently managed via file-type or a regex for extraction (https://github.com/apollographql/apollo-cli/blob/master/packages/apollo-cli/src/commands/queries/check.ts#L69). I don't think it makes sense to include the variable set along with the query since that would lead to bundled code. Since the generated code would really be an artifact of the consumer (i.e. a test and storybook may use different variables), it makes sense to have the defining variables in such file. This would require extraction using a tool like @benjamn's [recast](https://www.npmjs.com/package/recast) which would also be an ideal improvement to regex matching we currently perform.

```
apollo queries:record --endpoint=https://api.example.com/graphql --queries=./src/**/__stories__/*.js
```

A command like the above could load all files, find a known export (`queries` seems logical), and run operations against the backend.

```js

import { USER_QUERY } from '../users'

export const queries = {
  user: {
    query: USER_QUERY,
    requests: {
      basic: { 
        variables: { id: 1 },
        headers: { authorization: 'user' }
      },
      advanced: { variables: { id: 2 }  }
   ]
}
```

The above would execute USER_QUERY twice with given headers and variables. It would create a mapping in data.js like this:

```js
//  data.js
export const data = {
  user: {
    basic: { data: { user: null } },
    advanced: { errors: [ { message: 'donut socks not found' } ] }
  ]
}
```

The storybook file could then import (possibly added by recast***) like so:

```js
import { user } './__generated__/data';
```     

- [x] feature

**Comment by adamrneary** [comment]
This sounds right to me, every detail down to `donut socks not found`. 

I think for the sake of avoiding merging conflicts and long files, we would want the saved data not in a single `__generated__/data` output, but rather in files probably running in parallel to their source. So if `./src/**/__stories__/*.{js,jsx,ts,tsx}` was the starting point, `./src/__stories__/MyFeature/MyComponentVariations.tsx` could output mocks to `./src/__mocks__/MyFeature/MyComponentMock.js` or something configurable along those lines.

**Comment by jbaxleyiii** [comment]
@adamrneary 100%! 

My thought (made clearer in an edit above) would be `./src/components/__stories__/__generated__/data.js`
