### ISSUE TITLE
What happened to the print-schema command?

### ISSUE THREAD

**Issue by Slessi** [apollographql/apollo-tooling#501]
- [x] feature

When the library was `apollo-codegen`, there was a `print-schema` command added here  be798c17bcc9e9abbecf4389e794135e0d7e26e8

But doesn't seem to have been migrated e27235b6dbf3cfd6e30ab01008bbec6347f71abf

**Comment by EndyKaufman** [comment]
How work with print-schema?

apollo print-schema --schema=http://localhost:5000/graphql --output=schema.graphql

 »   Warning: print-schema is not a apollo command.

**Comment by mdaouas** [comment]
> * [x]  feature
> 
> When the library was `apollo-codegen`, there was a `print-schema` command added here [be798c1](https://github.com/apollographql/apollo-tooling/commit/be798c17bcc9e9abbecf4389e794135e0d7e26e8)
> 
> But doesn't seem to have been migrated [e27235b](https://github.com/apollographql/apollo-tooling/commit/e27235b6dbf3cfd6e30ab01008bbec6347f71abf)

Any news on this? it has been closed and this feature is still missing.
