### ISSUE TITLE
Flowtype definitions generated by apollo-codegen are empty

### ISSUE THREAD

**Issue by CoenWarmer** [apollographql/apollo-tooling#517]
I'm attempting to use the `apollo-codegen` tool to generate flowtype definitions, as specified in the [documentation](https://www.apollographql.com/docs/angular/features/developer-tooling.html#introspect). I am using the GraphQL server that is noted in the setup instructions containing currency exchange information (https://w5xlvm3vzz.lp.gql.zone/graphql).

So I try:

```apollo-codegen introspect-schema https://w5xlvm3vzz.lp.gql.zone/graphql --output schema.json```

This generates a `schema.json` file that looks correct.

I then attempt the generate step as described in the documentation:

```apollo-codegen generate **/*.graphql --schema schema.json --target flow --output operation-result-types.flow.js```

This leads to the following file `operation-result-types.flow.js`:

```


/* @flow */
/* eslint-disable */
// This file was automatically generated and should not be edited.

//==============================================================
// START Enums and Input Objects
//==============================================================

//==============================================================
// END Enums and Input Objects
//==============================================================

```

The TS and Swift outputs are also empty.

Am I misunderstanding how this tool works? Am I incorrectly assuming you only need the schema.json file generated by `apollo-codegen introspect-schema` to create flow types from a GraphQL endpoint? Or do you need .graphql files from the endpoint in addition to the schema.json file?

**Comment by shadaj** [comment]
Hi! Could you try using the new Apollo CLI as documented in the [README](https://github.com/apollographql/apollo-cli)? It contains a variety of fixes around code generation and discovering query files.
