### ISSUE TITLE
Run queries:check against local schema

### ISSUE THREAD

**Issue by rasmusprentow** [apollographql/apollo-tooling#531]
It is currently not possible to supply a schema to `queries:check`. Why is that? 

I have a local schema and needs to check against it, but there is no `--schema` argument.

**Comment by sneko** [comment]
I'm also looking for this feature.

Any thoughts about this @martijnwalraven @shadaj please?

**Comment by rasmusprentow** [comment]
Any comment on why this is closed?

**Comment by sneko** [comment]
@jbaxleyiii ?
