### ISSUE TITLE
cannot specify multiple `--queries` on codegen:generate

### ISSUE THREAD

**Issue by bmakuh** [apollographql/apollo-tooling#538]
It does not seem to be possible to specify multiple `--queries` flags, even though oclif can support it. The use case here would when you don't have a single code directory like `src/`:
```
components/
screens/
```

Then you could generate types for each top-level directory. 

```sh
apollo codegen:generate types/graphql.ts codegen:generate --queries=components/*.ts --queries=screens/*.ts --outputFlat
```

Right now it only takes the last `queries` flag and dumps the rest.

**Comment by supermoos** [comment]
I need this too. Could anyone provide a simple example for how to create a search query that would look in two directories? Since it seems the --queries parameter can use ** search patterns, I'm not sure what more than ** it can do though?

**Comment by supermoos** [comment]
Okay, this may work for you:

`apollo codegen:generate --tagName=graphql --queries='./{graphql,src}/**/*.tsx' --schema=./gatsby-schema.json src/gatsby-queries.d.ts --outputFlat`

**Comment by megalithic** [comment]
Just wanted to update that this ended up solving things for us:

```
apollo codegen:generate types/graphql.ts --queries="./{graphql,components,screens}/**/*.{tsx,ts}" --schema schema.json --target typescript --addTypename --outputFlat
```

Thanks so much @supermoos for getting us in the right direction.
