### ISSUE TITLE
codegen:generate look for graphql under multiple folders

### ISSUE THREAD

**Issue by msreekm** [apollographql/apollo-tooling#548]
next.js project with graphql queries and mutations in multiple folders- (pages,modules) under src folder.

src
    --pages
    --modules

--queries=./src/{pages,modules}/**/*.tsx . only generate the folder for the modules (last one in the list) !

apollo codegen:generate  --queries=./src/{pages,modules}/**/*.tsx --schema=./src/schema/schema.json --target=typescript --outputFlat ./src/schemaTypes.ts

**Comment by mtford90** [comment]
Also facing this, I assumed queries would be an array but that doesn't seem to work:

```
--queries=modules/**/*.ts,lib/**/*.ts
```
