### ISSUE TITLE
Allow us to specify the generation of a index.ts that re-exports all generated types.

### ISSUE THREAD

**Issue by wesselvdv** [apollographql/apollo-tooling#550]
I would like to see the option to generate a index.ts file in the generated directory for Typescript. This index.ts should re-export all the types generated by apollo. This would allow us to import more cleanly:

Current:
```typescript
import { generatedType, generatedTypeVariables } from './__generated__/generatedType'
```

Desired:
```typescript
import { generatedType, generatedTypeVariables } from './__generated__'
```

**Comment by samdenty** [comment]
I see this has been closed, has this been implemented?
