### ISSUE TITLE
Allow us to specify a file to be generated relative to the source file.

### ISSUE THREAD

**Issue by wesselvdv** [apollographql/apollo-tooling#551]
We're currently able to specify an output directory relative to the source file, but we're not able to specify an output file relative to the source file. Something close to outputFlat, but then not relative to the workdir but to the sourcefile.

**Comment by danilobuerger** [comment]
Thats already possible, just specify `""` as output dir

**Comment by wesselvdv** [comment]
Is it also possible to give a custom name to said file, and that it contains all the types instead of one type per file?

**Comment by danilobuerger** [comment]
Yes, as mentioned in the docs:
> - For TypeScript/Flow generators with the "outputFlat" flag is set, and for the Swift generator, this specifies a 
      file or directory (absolute or relative to the current working directory) to which:
         - a file will be written for each query (if "output" is a directory)
         - all generated types will be written

**Comment by wesselvdv** [comment]
@danilobuerger The key sentence in that explanation is **(absolute or relative to the current working directory)** I would like it to be **relative to the source file of the query**.

**Comment by danilobuerger** [comment]
Maybe you could post an example so its 100% clear what you mean.

**Comment by wesselvdv** [comment]
@danilobuerger What I would like to be able to do is the following:

* relative-folder
  * source-file.component.ts
  * source-file.component.types.ts
* types
  * globalTypes.ts

**Comment by rasmusprentow** [comment]
I am sure this is the same feature as https://github.com/apollographql/apollo-cli/issues/529

**Comment by wesselvdv** [comment]
@rasmusprentow With the difference that you're requesting the ability to rename individual type files? I would also like to be able to consolidate all the types into a file with a name of my choosing which is relative to the source file.

**Comment by rasmusprentow** [comment]
What exactly will be in globalTypes.ts?

**Comment by wesselvdv** [comment]
@rasmusprentow That's a current functionality, see: https://github.com/apollographql/apollo-cli/blob/c4a29cb4750570f6dd1cc1bb805e611f35832837/packages/apollo-cli/src/generate.ts#L134

**Comment by rasmusprentow** [comment]
@wesselvdv Okay I thought it was an output from the cli, looks more like input. 
. I don't really get what you want to achieve then. Perhaps you can explain what input you have and what output you want to get. 

What I wan't is basically to have more control of the naming of the outputted typing files.
