### ISSUE TITLE
Document that ENGINE_API_KEY can be used as an env var

### ISSUE THREAD

**Issue by stubailo** [apollographql/apollo-tooling#552]

**Comment by jhalborg** [comment]
Additional note for this:

I think there’s an issue with requiring the env var to be called something specific (i.e. `ENGINE_API_KEY`). For example, `create-react-app` requires a prefix to all custom env vars, `REACT_APP_`. This effectively makes it impossible to use Engine with CRA :cry:  https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-custom-environment-variables

**Comment by stubailo** [comment]
That's only if you want to use that variable on the client, though - and you definitely shouldn't be sending your Engine API key to your frontend.

What are you trying to accomplish?

**Comment by jhalborg** [comment]
In my CI flow for my webapp (React), I want the build server to 
1. Get the schema from Engine for my backend
2. Check the queries in the app against the newest schema
3. Abort if any errors are found, continue otherwise. 

To me, that requires an Engine integration from my node scripts in my React app, or am I doing something wrong? 😄

**Comment by stubailo** [comment]
You don't need to do anything create-react-app specific to do that! You just need to add the env var to your build environment, whether that's Netlify, CircleCI, or whatever. The Apollo CLI doesn't need to be integrated into CRA in any special way. The env var directions they have are only if you need to use them in your actual app, not for CI tools like the Apollo CLI.

**Comment by jhalborg** [comment]
Of course, what a brainfart on my part - sorry for the smell! 😄
