### ISSUE TITLE
Cannot use with React Native / Typescript

### ISSUE THREAD

**Issue by epeli** [apollographql/apollo-tooling#574]
The `apollo` module brings in the `@types/node` module as a transitive dependency which is an issue with React Native typings (`@types/react-native`) because they have conflicting type definitions:

```
Cannot redeclare block-scoped variable 'console'.
Duplicate identifier 'require'.
```

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16825

I know this is issue is with `@types/react-native` and/or `@types/node` but that's a long standing issue with no solution in sight so I'm wondering if it would be possible to get rid of the dependency from apollo's side.

The dependencies which brings it in are as follows:

```
myapp@0.0.1
└─┬ apollo@1.9.1
  ├─┬ @types/globby@8.0.0
  │ └─┬ @types/glob@5.0.35
  │   └── @types/node@10.9.4  deduped
  ├─┬ @types/react-dom@16.0.7
  │ └── @types/node@10.9.4
  ├─┬ @types/rimraf@2.0.2
  │ └── @types/node@10.9.4  deduped
  └─┬ apollo-engine-reporting@0.0.2
    └─┬ apollo-engine-reporting-protobuf@0.0.1
      └─┬ protobufjs@6.8.8
        └── @types/node@10.9.4  deduped
```

**Comment by alloy** [comment]
imo the best solution is for runtime dependencies to never depend on `@types/*` packages. These are dev only packages and using the right ones should be left to the dev.

**Comment by danilobuerger** [comment]
@alloy they are dev dependencies: https://github.com/apollographql/apollo-cli/blob/master/package.json#L46

**Comment by alloy** [comment]
How can that be then? Dev dependencies don’t get pulled in when adding a runtime dependency to your package, no? From @epeli’s illustration it does look like the `apollo` package is pulling all of these into their project.

**Comment by danilobuerger** [comment]
My guess would be some weird lerna stuff.
