### ISSUE TITLE
Codegen outputs no models

### ISSUE THREAD

**Issue by bobvanderlinden** [apollographql/apollo-tooling#585]
Whenever I try to generate Typescript from my query I get no models in the output. The output looks like:

```
/* tslint:disable */
// This file was automatically generated and should not be edited.
//==============================================================
// START Enums and Input Objects
//==============================================================
//==============================================================
// END Enums and Input Objects
//==============================================================
```

I'm using GitHub as the graphql source. You can reproduce this using the following gist:

https://gist.github.com/bobvanderlinden/ed64a44cced3c479463851f4ba6ae615

Note that there is a `run.sh` that downloads the GitHub GraphQL schema and generate the Typescript code. For downloading the schema you'll need a GitHub token that can be generated here: https://github.com/settings/tokens/new

**Comment by ianks** [comment]
I had a similar issue, but realized that that my query was invalid. It would be nice to warn/error if the query is invalid for generating types.

**Comment by JakeDawkins** [comment]
In efforts to clean up and triage issues, I'm gong to close this issue, since it hasn't had any conversation in a while. I'd be happy to reopen it if anyone is still having issues with this in current versions of the tooling.
