### ISSUE TITLE
load-schema catches all errors

### ISSUE THREAD

**Issue by mmkal** [apollographql/apollo-tooling#586]
Hi there. I'm pretty new to apollo-cli, and I've just spent a good few hours digging through the source code to track down why my codegen commands were failing. There's at least one easy opportunity to make this process much less painful: https://github.com/apollographql/apollo-cli/blob/8d4e0ac0b1158696c503b3698e492c7c7ccc0bfb/packages/apollo/src/load-schema.ts#L10-L15

After a _lot_ of diving into source code, I eventually found that `try { ... } catch (e) { }` block which is swallowed a helpful error, meaning I ended up with one that didn't give me any hints as to what was going wrong.

@martijnwalraven was there a particular reason the execution couldn't just be allowed to fail there? If it had, I would have seen `Error: Unable to read file blahblah/src/schema.graphql. Type "VisitSubscriptionPayload" not found in document.`. As it was, I saw `TypeError: schema.getMutationType is not a function` _way_ further down in the stack, after an `undefined` schema had been passed around all over the place.

**Comment by mmkal** [comment]
For anyone interested: that second, less actionable error, occurred in `graphql/utilities/TypeInfo.js` which is called by `graphql/language/visitor.js` which is passed a schema object by `apollo/lib/validation.js` which is called by `apollo/lib/generate.js`, which has a `schema` object it picks out of `ctx.documentSets[0]`, which is populated by the `Resolving GraphQL document sets and dependencies` task, which calls `resolveDocumentSets`, which calls `loadSchema`, which is where the error occurs and is swallowed. This means `loadSchema` just returns undefined, and it propagates all the way down that chain. Fun Sunday afternoon figuring all that out!

**Comment by JakeDawkins** [comment]
This issue seems to be stale, so I'll close it unless anyone else objects. We've made a lot of progress in the past few months on error messaging, so this may be partially solved anyway :)
