### ISSUE TITLE
Config does not support multiple schemas

### ISSUE THREAD

**Issue by jhalborg** [apollographql/apollo-tooling#588]
- [x] has-reproduction
- [x] docs
- [x] blocking

It seems that it's not possible to have multiple schemas in the Apollo Config, even though the docs says so. 

Following the docs, I created the following setup:
```
"schemas": {
      "serverSchema": {
        "schema": "downloadedSchema.json",
        "endpoint": "https://my.staging.url.com/graphql",
      },
      "clientSchema": {
        "extends": "serverSchema",
        "clientSide": true,
        "schema": "mergedSchema.json",
        "endpoint": "./src/localState/clientSchema.graphql",
      }
    },
    "queries": [
      {
        "schema": "clientSchema",
        "includes": [
          "**/*.tsx",
          "src/**/*.{ts,tsx}"
        ],
        "excludes": [
          "node_modules/**"
        ]
      }
    ]
```

It fails with the following error output:
```
$ npx apollo schema:download schema.json --config=package.json
 ✔ Loading Apollo config
 ✖ Fetching current schema
   → More than one schema found.
   Saving schema to schema.json
 ›   Error: More than one schema found.
error Command failed with exit code 2.
```
Furthermore, I'm in doubt wether the `schema` prop is for where to ouput the resulting `.json`. schema, or something else? A more complete example under [the readme](https://github.com/apollographql/apollo-cli#schema-dependencies) would be helpful

**Comment by WaldoJeffers** [comment]
Having the same issue after having been misled by the docs :/ I resorted to using as many configuration files as schemas...

**Comment by peeter-tomberg** [comment]
After a bit of abuse, I got it working:

```
  "apollo": {
    "schemas": {
      "serverSchema": {
        "schema": "./data/schema.json"
      },
      "clientSchema": {
        "schema": "./data/schema.local.graphql",
        "clientSide": true,
        "extends": "serverSchema"
      }
    },
    "queries": [
      {
        "schema": "clientSchema",
        "includes": [
          "./src/client/**/*.tsx",
          "./src/client/**/*.ts"
        ]
      }
    ]
  },
```

**Comment by mbinic** [comment]
You could also use [graphql-code-generator](https://github.com/dotansimha/graphql-code-generator)'s [schema ast plugin](https://graphql-code-generator.com/docs/plugins/schema-ast) to stitch the schemas into one for the config. Of course, this wouldn't help you when editing one of those schema files in VS Code.

With frameworks like Loona, or just plain splitting the client schema into multiple files, using wildcards/glob would be very useful.

As a suggestion to make the config (mostly for the VS Code extension) less frustrating to set up - the tolling could introduce some sensible defaults, e.g. consider *.schema.{graphql,gql} files as part of the schema, and others as queries without even having the config. This is just my humble opinion though, haven't been in this for too long, so I might just be talking nonsense :)

**Comment by mbinic** [comment]
Oops, now that I look at it, it seems #588 is more relevant, since the configuration format has changed (https://www.apollographql.com/docs/references/apollo-config.html). Maybe close this issue then?
