### ISSUE TITLE
Retrieve apollo-link-state schema

### ISSUE THREAD

**Issue by GitProdEnv** [apollographql/apollo-tooling#589]
On my client side project I use a backend graphql endpoint and Apollo-link-state. Whereas the backend (downloading the schema and generating the typescript interfaces works flawelessly) I'm stuck at generating a schema for apollo-link-state which is working fine in conjunction with apollo-cli.

The problem is just the client side schema.
My project uses a modularized approach exactly such as [here](https://blog.apollographql.com/modularizing-your-graphql-schema-code-d7f71d5ed5f2). 

Using apollo schema:download --endpoint http://localhost:8000/graphql at the backend side, I don't know how to proceed on the client side.

In my schema.js I export my resolvers, typeDefs and defaults from Apollo-link-state
``export default {
  defaults,
  resolvers: merge(resolvers, dashboardResolvers, redirectListenerResolvers),
  typeDefs: [Query, Mutation, Dashboard, PageBuilder, RedirectListener]
};``

and I follow the basic [Apollo docs ](https://www.apollographql.com/docs/link/links/state.html#defaults) for Apollo-link-state

``export const stateLink = withClientState({
  typeDefs: schema.typeDefs,
  cache,
  resolvers: schema.resolvers,
  defaults: schema.defaults
});
``

How can I retrieve the apollo-link-state schema path to process it to apollo schema:download --endpoint
Thank you for your help

**Comment by heysailor** [comment]
Have a look here: https://github.com/apollographql/apollo-cli/issues/366

- make a client.graphql file, extending Query and Mutation, and pass that file to `apollo codegen:generate` with` --clientSchema=<path to your client.graphql>`

**Comment by JakeDawkins** [comment]
Hey @GitProdEnv! I'm working on triaging some of these issues, so forgive me if I misunderstand.

I believe what you're trying to do is possible now (although I'm not 100% sure the release this happened in). In your client project, all you need to do is `extend` the remote schema to add your client fields. The apollo cli should pick up those extensions while extracting the operations from the client codebase automatically, and generate types based off those extractions.

This is done in the [fullstack tutorial](https://github.com/apollographql/fullstack-tutorial/blob/e39b0a0775eaed64035fedd80e4470f78c2952b5/final/client/src/resolvers.js#L4) and explained [here](https://www.apollographql.com/docs/tutorial/local-state.html#local-schema).
