### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by lirbank** [apollographql/apollo-tooling#593]
Congrats on the new release!

Any chance you could update the changelog with the latest?

**Comment by andykenward** [comment]
Can you please start updating the `CHANGELOG.md` files when doing releases.

You have [lerna-changelog](https://github.com/lerna/lerna-changelog) setup and uses the tagging method on Pull Requests.

But it looks like people doing releases aren't following [publishing] (https://github.com/apollographql/apollo-tooling#publishing) to generate the `CHANGELOG.md` files.

Sidenote, I've recently implemented [conventional commits](https://conventionalcommits.org/) with [lerna](https://lernajs.io) and found it a better setup, [reference](https://github.com/Stinkstudios/npm-packages).

Thanks for all the hard work that goes into Apollo. Just want to make it easier for people maintaining projects using it and need to update their dependencies.

**Comment by kballard** [comment]
Please do this. It looks like you released a version 2.0.0 very recently. Given the major version bump, I'm wondering if it's safe to upgrade to 2.x from 1.9.2 or if this will introduce backwards-compatibility issues. The complete lack of any changelog gives me no way to research this.

**Comment by danpalmer** [comment]
We're stuck on 1.9.x because there haven't been any changelog updates. Please do this so that we can upgrade. Our build doesn't work on the latest version, so understanding the upgrade path would be very useful.

**Comment by JakeDawkins** [comment]
Hey @danpalmer! Most of the commands from 1.9 should still work with 2.3 (the most recent) through aliases. Can you give me more info about what's going wrong so I can help debug?

**Comment by danpalmer** [comment]
Thanks for taking a look at this.

All I know is that it doesn’t compile, so we went to look for the list of breaking changes so we could do a correct upgrade, and found that the change log was unmaintained. 

We might be able to patch bits until it compiles, but that’s not really enough confidence for a production app for us, so we’ll probably wait for the changelog entries.

**Comment by JakeDawkins** [comment]
@danpalmer @lilyball @andykenward @lirbank This issue _should_ be fixed when #933 merges 🎉
