### ISSUE TITLE
codegen:generate flow wrong inexact type and  unnecessary union

### ISSUE THREAD

**Issue by fokot** [apollographql/apollo-tooling#596]
Node returns union of different types

```
fragment CustomerDetailFields on Customer {
  id
  name
}

query CustomerDetail($id: ID!) {
 {
    customer: node(id: $id) {
      ...CustomerDetailFields
    }
  }
}
```

Generated code look like
```
/* @flow */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CustomerDetailQueryVariables = {|
  id: string,
|};

export type CustomerDetailQuery = {|
  ad: {|
    __typename: "Query",
    // Universal interface returning any Object
    customer:( {
        __typename: "User",
      } | {
        __typename: "Task",
      } | {
        __typename: "Customer",
        id: string,
        name: ?string,
      } | {
        __typename: "ScreenedSource",
      }
    ),
  |},
|};

export type CustomerDetailFieldsFragment = {|
  __typename: "Customer",
  id: string,
  name: ?string,
|};
```

**Bug**
`CustomerDetailFieldsFragment` is exact type but customer in `CustomerDetailQuery` is inexact.

**Feature**
I ask only for one type of Fragment so I would rather get optional input than union of all possible types returning from `node` field. In our case it is save, as we add type names to global ids. Maybe this should be generator flag.

**Comment by JakeDawkins** [comment]
In efforts to clean up and triage issues, I'm going to close this issue, since it hasn't had any conversation in a while. I'd be happy to reopen it if anyone is still having issues with this in current versions of the tooling.
