### ISSUE TITLE
[apollo-codegen-flow] "@babel/types" has no exported member 'FlowTypeAnnotation'.

### ISSUE THREAD

**Issue by alvis** [apollographql/apollo-tooling#597]
I'm using `apollo-cli` to generate types for my typescript project. However, I got an indirect hit by the codegen for flow.

In `apollo-codegen-flow`, `FlowTypeAnnotation` is referenced to `@babel/types`. But somehow nowhere I can find this reference in `@babel/types`. Possible the location has changed or it has been removed during the beta process.

To reproduce the problem, you just need to `tsc` in the the `apollo-codegen-flow` package folder, and you can find loads of TS2339.

@martijnwalraven: do you have any idea how can it be fixed?

**Comment by alvis** [comment]
ping @martijnwalraven

**Comment by JakeDawkins** [comment]
In efforts to clean up and triage issues, I'm going to close this issue, since it hasn't had any conversation in a while. I'd be happy to reopen it if anyone is still having issues with this in current versions of the tooling.
