### ISSUE TITLE
[apollo-codegen-swift] autogenerated models : NSObject

### ISSUE THREAD

**Issue by Ewg777** [apollographql/apollo-tooling#599]
- [x] feature

Hi,

Thanks for such a great lib!
I'd suggest to use NSObject as a parent class for autogenerated models in apollo-codegen-swift. So, this will allow to use this models in an objective-c project.

Does it make sense?

**Comment by Ewg777** [comment]
@martijnwalraven
@shadaj
@rricard
What do you think?

```
 public final class GetAccount: NSObject, GraphQLSelectionSet {
```
instead of 

```
 public struct GetAccount: GraphQLSelectionSet {
```

**Comment by martijnwalraven** [comment]
The generated models are Swift structs, not classes, so that wouldn't work. It also uses other Swift language features that aren't available in Objective-C.

**Comment by Ewg777** [comment]
@martijnwalraven Thanks for the reply.
> The generated models are Swift structs, not classes, so that wouldn't work.
Migration to obj-c classes works.
> It also uses other Swift language features that aren't available in Objective-C.
Yeah, I see.
Any idea how to use the models in an objc project?

**Comment by JakeDawkins** [comment]
This issue _seems_ to be resolved and stale, so I'll close it. Feel free to ask questions about usage in our [spectrum community](https://spectrum.chat/apollo) if you still have any :)
