### ISSUE TITLE
Watch not working

### ISSUE THREAD

**Issue by Rockson** [apollographql/apollo-tooling#603]
Looks like the codegen watch is not working

```
const query = gql`
query MyQuery {
  field
}
`
```

when I change the query inside a gql tag it doesn't reload the types

**Comment by wesselvdv** [comment]
Same here, nothing happens with the watch flag.

**Comment by slorber** [comment]
Same, node 8.3.11, with the command `apollo client:codegen --target typescript --addTypename --globalTypesFile ./src/AppApolloGlobalTypes.ts __genTypes__ --watch`

**Comment by kevinhughes27** [comment]
Also not working for me. I tried both the flag and config object.

**Comment by JakeDawkins** [comment]
Can anyone confirm this is still an issue with the latest CLI version?

**Comment by timdev** [comment]
@JakeDawkins - `--watch` works, but emits no output when it detects changes and regenerates code.  

Coupled with a little bit of lag in an IDE, I got confused much like @kevinhughes27 was.

**Comment by JakeDawkins** [comment]
Ha. As it turns out, this was just a 1-line change. It was already in the codebase, but was disabled at some point. I opened a PR to add logging back in :)
