### ISSUE TITLE
Xcode 10 gives build error

### ISSUE THREAD

**Issue by ktkanishka** [apollographql/apollo-tooling#607]
I have below issue while using apllo-cli in Xcode 10. Here is the error I'm getting. I cannot build the project. Please help and let me know if you need more info.
(I have included .schema and apollo script properly)

warning: The version of Apollo.framework in your project requires Apollo CLI 1.8.x, but apollo/1.9.2 darwin-x64 node-v8.12.0 seems to be installed.
note: Installing apollo@1.8 in your project directory to avoid version conflicts...
npm ERR! Error while executing:
npm ERR! /Applications/Xcode.app/Contents/Developer/usr/bin/git ls-remote -h -t ssh://git@github.com/Code/ProjectName.git
npm ERR! 
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Kanishka/.npm/_logs/2018-09-30T15_19_59_045Z-debug.log
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by annjose** [comment]
Looks like this is the same issue as https://github.com/apollographql/apollo-ios/issues/356. Can you try installing Apollo CLI from command line (using `npm install` command)?

**Comment by JakeDawkins** [comment]
In efforts to clean up and triage issues, I'm gong to close this issue, since it hasn't had any conversation in a while. I'd be happy to reopen it if anyone is still having issues with this in current versions of the tooling.
