### ISSUE TITLE
Typescript parsing error (apollo-codegen vs. apollo-cli)

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/apollo-tooling#612]
This issue is blocking a user on upgrading from `apollo-codegen` to `apollo-cli`.

Expected behavior:
```
$ yarn apollo codegen:generate __generated__ --target=typescript --tagName=gql --queries=\"src/**/*.{ts,tsx}\" --schema=./src/__generated__/schema.json
```
Should generate typescript types.

The error thrown by the parser:
```
SyntaxError: Operation extraction from file src/containers/someDirectory/someFile.ts failed with
Unexpected token, expected ")" (33:21)
```

The code in violation (based on column #, it seems to dislike the "destructuring"):
```
interface Props {
  children: ({ data }: { data: Data }) => React.ReactNode | null;
}
```

For reference, this works:
```
interface RenderProps {
  data: Data;
}

interface Props {
  children: (props: RenderProps) => React.ReactNode | null;
}
```

**Comment by nmchaves** [comment]
I was able to resolve this by changing the command to:
```sh
$ yarn apollo client:codegen __generated__ --target=typescript --tagName=gql --queries=\"src/**/*.{ts,tsx}\" --localSchemaFile=./src/__generated__/schema.json --globalTypesFile=./src/__generated__/globalTypes.ts
```

Differences:
1) `codegen:generate` -> `client:codegen`
2) `--schema` -> `--localSchemaFile`
3) add the `--globalTypes` argument (not sure if this is necessary though)

**Comment by JakeDawkins** [comment]
Is this still an issue @trevor-scheer?

**Comment by nmchaves** [comment]
IMO, this can be closed. It was simply "user error" (not updating the command correctly)

**Comment by JakeDawkins** [comment]
Sounds good, thanks @nmchaves!
