### ISSUE TITLE
apollo-codegen-core doesn't have graphql as a dependency

### ISSUE THREAD

**Issue by migueloller** [apollographql/apollo-tooling#616]
The package `apollo-codegen-core` imports `graphql` [here](https://github.com/apollographql/apollo-cli/blob/c50691d8c8fdb0e2beea817052c28ccf5887ea8a/packages/apollo-codegen-core/src/loading.ts#L9-L20) but it doesn't have it as a dependency or peerDependency in the `package.json`. This causes issues with monorepos as dependencies can be hoisted or not, causing the import to fail.

Would an MR for this be accepted?

**Comment by JakeDawkins** [comment]
In efforts to clean up and triage issues, I'm going to close this issue, since it hasn't had any conversation in a while. I'd be happy to reopen it if anyone is still having issues with this in current versions of the tooling.
