### ISSUE TITLE
VSCode: friendlier error messages

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/apollo-tooling#627]
When things go wrong on extension load, the extension doesn't offer any friendly/actionable feedback to help the user resolve the issue.

For example, the user may have their config set up incorrectly, or the network request to engine may fail unexpectedly. We should handle these cases gracefully and give the user relevant messaging to troubleshoot the problem.

**Comment by JakeDawkins** [comment]
This should be resolved by now. Any more specific errors/suggestions can be opened as separate issues :)
