### ISSUE TITLE
Update dependencies on apollo-engine-reporting

### ISSUE THREAD

**Issue by daggerjames** [apollographql/apollo-tooling#629]
According to current [package.json](https://github.com/apollographql/apollo-cli/blob/a84aabb66438d6c346b989db75574b50b7c1be43/packages/apollo/package.json#L54), this repo has restricted `apollo-engine-reporting` to a specific version, which affects the requirement on `graphql v0.13.x` through its sub-dependency `graphql-extensions`.

```bash
myProject@1.0.0
└─┬ apollo@1.9.2
  └─┬ apollo-engine-reporting@0.0.2
    └── graphql-extensions@0.1.2 
```

I just found that the latest version of `apollo-engine-reporting@0.0.6` solved this.

Since I have not used `apollo-engine` yet, could someone help to upgrade it?

**Comment by trevor-scheer** [comment]
@daggerjames thanks for submitting, and sorry for the delay on this. This should be resolved now!
