### ISSUE TITLE
Unexpected "Internal Server Error" on Apollo API while running apollo schema:check with new (valid) schema changes

### ISSUE THREAD

**Issue by chroto** [apollographql/apollo-tooling#634]
Hi, when running `apollo schema:check` with new schema changes the CLI returns an unhelpful Syntax Error with no other information. The new changes are valid and deploy to our Apollo Service just fine.

What we expect to happen is that `apollo schema:check` returns a report of the changes in our schema

Attached below is a screenshot of a debug session that traced down the Internal Server Error with `"Syntax Error: Expected Name, found ["`

![screen shot 2018-10-20 at 9 59 03 am](https://user-images.githubusercontent.com/502800/47257760-cf953580-d44e-11e8-8dc0-9b17828a0b0b.png)

**Comment by JakeDawkins** [comment]
This issue hasn't seen any conversation in a while, and may actually be resolved with the rewrite of the CLI that happened soon after this. If this is still an issue, feel free to object to me closing it :)
