### ISSUE TITLE
Codegen ignores schema paramater

### ISSUE THREAD

**Issue by cesarvarela** [apollographql/apollo-tooling#652]
- [x] has-reproduction
- [ ] feature
- [ ] docs
- [x] blocking
- [ ] good first issue
```
$ apollo codegen:generate --schema=doesntmatterwhatiputhere API.swift
 ✔ Loading Apollo config
 ✔ Scanning for GraphQL queries (20 found)
 ✔ Generating query files with 'swift' target - wrote 1 files
```
Also:

- There arent 20 graphql queries anywhere so I'm not sure from where does it take that number
- Resulting API.swift file is always empty

I'm on Mojave, apollo/1.9.2 darwin-x64 node-v10.12.0

**Comment by jpaas** [comment]
I was struggling with this too on `1.9.2`. Now v2 has been released. The codegen command has changed to `apollo client:codegen` and the `--schema` parameter is gone from the help entirely.

It looks like we may need to provide the schema via the `apollo.config.js` file now. However the `client.service.localSchemaFile` setting does not appear to work. It always errors with `Error: Error in "Loading schema for projectname": TypeError: Only absolute URLs are supported`

There are other people struggling with this with the VScode extension #669 #667 , but it also seems to break codegen.

**Comment by trevor-scheer** [comment]
I'm going to close this, as this issue should be solved via the `--localSchemaFile` flag / related config entry. Please feel free to open another issue if this still persists in `apollo@2.x`
