### ISSUE TITLE
Question regarding codegen and its setup

### ISSUE THREAD

**Issue by RIP21** [apollographql/apollo-tooling#655]
Hi everyone. Couldn't fine my answers in docs so asking here.

*I have following setup:*
- No GQL server at all, only `apollo-link-rest`.
- Code in TS and JS.
- 1 query that I use to test `apollo-link-rest`.
- It works just fine, means all setup is correct.

*What a want to achieve:*
- I want to generate typings from my queries in the JS/TS code
- And then use them when creating `<Query>` components to get autocomplete and correct typing of `data`.
- Generate typings for regular local types hence the type that will be returned from the Query.

*Question is:*
What config files I should have, and what tool I should use to get that up and running?
For now I wrote manually `local.graphql` that describes this only query I have.

*What I tried:*
I tried somehow to run `apollo codegen:generate` but couldn’t find any successful combo of all those weird arguments and settings of cli (is it possible to setup them in a separate file? Like we do with ESLint, Babel etc? (not much of the docs about that))

I tried hard, but failed. Also if it’s possible to generate all @rest / @export definitions, so tools like `js-graphql-intellij-plugin` autocomplete instead of doing them them totally red saying there is no such stuff in schema.

Right now I’m fixing it using stub like that in `local.graphql`
```
directive @rest(path: String!, method: String, type: String!, endpoint: String) on FIELD
```
If it can be generated - will be nice.

**Comment by sasha-firsov-bs** [comment]
@RIP21 , have you found the answer? If so, would you mind to share, please?

**Comment by RIP21** [comment]
@sasha-firsov-bs it's been 4 years. Don't remember anything :D For codegen tho, I would recommend using graphql-codegen
https://the-guild.dev/graphql/codegen

Other than that I have nothing :)
