### ISSUE TITLE
[apollo-codegen-typescript] Import of globaltypes differs on mac/windows

### ISSUE THREAD

**Issue by FlayaN** [apollographql/apollo-tooling#658]
In our team we have some people using windows and some using mac, and we get a conflict on the generated types that use a type in globalTypes.

1. **Intended outcome:**
mac:
```javascript
import { GlobalEnumType } from "./../../../__generated__/globalTypes";
```
windows:
```javascript
import { GlobalEnumType } from "./../../../__generated__/globalTypes";
```

2. **Actual outcome:**
mac:
```javascript
import { GlobalEnumType } from "./../../../__generated__/globalTypes";
```
windows:
```javascript
import { GlobalEnumType } from "./..\\..\\..\\__generated__\\globalTypes";
```
3. **How to reproduce the issue:**
Run apollo codegen:generate on windows.
ex:
`apollo codegen:generate --queries=./src/**/queries.ts --schema=./src/schema.json --globalTypesFile ./src/__generated__/globalTypes.ts --target=typescript --addTypename --watch`

**Possible solution:**

At the moment you are using path.relative to generate that path.

https://github.com/apollographql/apollo-tooling/blob/master/packages/apollo-codegen-typescript/src/codeGeneration.ts#L89

one possible solution is to use path.posix.relative to get a */* version for windows aswell.

**Test of solution on windows machine:**
I didn't get apollo-tooling to build on my windows machine due to some unix stuff in build scripts in apollo-env build so I setup a minor test of this solution instead.

```javascript
import * as path from "path";

console.log(path.posix.relative(
    path.dirname("./src/test/test2/test3.ts"),
    path.dirname("./src/test.ts")
  ));

//output *../..*

console.log(path.relative(
    path.dirname("./src/test/test2/test3.ts"),
    path.dirname("./src/test.ts")
  ));

//output *..\\..*
```

**Comment by adamjez** [comment]
We're having exactly the same problem. Is there any plan to fix it? Is there any workaround?

**Comment by FlayaN** [comment]
This issue is now fixed with:
https://github.com/apollographql/apollo-tooling/pull/826/commits/57fc50b08abd8c276ee05035ecacb9ba55f4b4b4

And it's in release apollo@2.2.0 😃
