### ISSUE TITLE
Missing schema:check and schema:publish commands

### ISSUE THREAD

**Issue by tsaiDavid** [apollographql/apollo-tooling#665]
Was following the latest tutorial after Day 1 @ GraphQL Summit - and noticed that utilizing the following didn't work for me.

`npx apollo schema:check && npx apollo schema:publish` 

https://www.apollographql.com/docs/tutorial/production.html#publish

**Comment by tsaiDavid** [comment]
Did some digging around and saw the alias was still around for `schema:publish`, but can't seem to find `schema:check` anywhere.

https://github.com/apollographql/apollo-tooling/blob/489b7b9a4f/packages/apollo/src/commands/service/push.ts#L9

**Comment by sandbochs** [comment]
Encountered this as well while running through the tutorial and surprised hasn't been reported sooner since it could affect build pipelines.

**Comment by tsaiDavid** [comment]
Looks like the docs are out of date and they need to be swapped to utilize the `service` namespaced set of commands

**Comment by jbaxleyiii** [comment]
@tsaiDavid @sandbochs I'm so sorry about this! I've updated the aliases so both should work!
