### ISSUE TITLE
VSCode : Without Apollo engine

### ISSUE THREAD

**Issue by joaogarin** [apollographql/apollo-tooling#667]
Hello,

I amt trying to use the apollo vs code extension, but I am not using Apollo Engine. :Does the extension support other endpoints ? or even a local introspection result file (json)?

My config looks like this : 

``` 
module.exports = {
  client: {
    service: {
      endpoint: {
        url: 'https://{myendpoint}/graphql'
      },
    }
  }
};

```

Right when opening the editor I can find a couple errors : 

```TypeError: Only absolute URLs are supported``` (even though my endpoint is absolute)
```UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Unable to find ENGINE_API_KEY```

My frontend lives in a subfolder so the apollo.config.js lives also in that folder, even though I also tried putting it in the root but the same errors showed up

Thank you!

**Comment by shadaj** [comment]
Hi @joaogarin, you'll need to just put the `url` directly inside `service`. If you update your config to look like this
```js
module.exports = {
  client: {
    service: {
      url: 'https://{myendpoint}/graphql'
    }
  }
};
```
everything should work fine.

**Comment by joaogarin** [comment]
Hello,

thanks for the feedback. I did try that also, and with it I get only the Unhandled promisse error : 

```
(node:69541) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Unable to find ENGINE_API_KEY
(node:69541) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

but query autocompletion and so on still does not work.

**Comment by shadaj** [comment]
That's odd. The error message is expected, but code completion should have started to work. Where are you defining your query files? By default the extension only performs code completions in `src/**.{js(x), ts(x), graphql}`.

**Comment by joaogarin** [comment]
Ah I see..yeah its not under src/** =/ too bad.

**Comment by jessedvrs** [comment]
> That's odd. The error message is expected, but code completion should have started to work. Where are you defining your query files? By default the extension only performs code completions in `src/**.{js(x), ts(x), graphql}`.

@shadaj Is there a way to configure this default directory `src` ?

**Comment by jessedvrs** [comment]
Found it! @joaogarin you must put the apollo.config.js in the root of the project (so that it can be found by the vscode extension). Then you can configure your target directory like this:
```
module.exports = {
    client: {
        name: 'graphql-vscode-client-test',
        service: {
            url: "http://localhost:5000/graphql",
        },
        includes: [
            "client/src/**/*.{ts,tsx,js,jsx,graphql}"
        ]
    },
};
```
Give your vscode a reload! Works for me, I hope it works for you too!

**Comment by Negan1911** [comment]
With @jessedvrs still not working for me, i got:
```
 ✔ Loading Apollo Project
 ✖ Checking client compatibility with service
   → Unable to find ENGINE_API_KEY
Error: Unable to find ENGINE_API_KEY
    at GraphQLClientProject.get engine [as engine] (~/.npm/_npx/20929/lib/node_modules/apollo/node_modules/apollo-language-server/lib/project/base.js:46:19)
    at Task.task (~/.npm/_npx/20929/lib/node_modules/apollo/lib/commands/client/check.js:20:55)
    at <anonymous>
```

**Comment by jessedvrs** [comment]
@Negan1911 It looks like you are trying to run the Apollo CLI. For VSCode to work with autocompletion, you don't need to use the Apollo CLI.

I also get the ENGINE_API_KEY error in my VSCode output. But (as @shadaj pointed out as well) the autocompletion should still work. The Engine feature is only for viewing performance statistics (as measured by the Engine cloud service) in VSCode.

**Comment by thompk2** [comment]
@jessedvrs That worked for me! Is that `includes` documented anywhere?

**Comment by jbaxleyiii** [comment]
@joaogarin @jessedvrs @thompk2 I've written first pass docs here! https://www.apollographql.com/docs/resources/apollo-config.html#loading-files

**Comment by joaogarin** [comment]
For the likes of me I just can''t get this to work properly...even using the includes. New errors now : 

<img width="458" alt="screen shot 2018-11-15 at 09 57 54" src="https://user-images.githubusercontent.com/2866604/48545065-f6fbe880-e8bc-11e8-8457-9efaa31515f7.png">

```  
Cannot define a new schema within a schema extension.
    at assertValidSDLExtension (/Users/joaogarin/.vscode/extensions/apollographql.vscode-apollo-1.1.12/node_modules/graphql/validation/validate.js:106:11)
    at Object.extendSchema (/Users/joaogarin/.vscode/extensions/apollographql.vscode-apollo-1.1.12/node_modules/graphql/utilities/extendSchema.js:65:43)
    at loadingHandler.handle (/Users/joaogarin/.vscode/extensions/apollographql.vscode-apollo-1.1.12/node_modules/apollo-language-server/lib/project/client.js:60:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by martijnwalraven** [comment]
@joaogarin That is a SDL validation error from `graphql-js`. Do you have multiple `schema` definitions maybe?

**Comment by xyy94813** [comment]
Why i always get error:

`UnhandledPromiseRejectionWarning: Error: No API key found. Please set APOLLO_KEY or use --key`

I just want to use local schema (or my server)

```js
// apollo.config.js
module.exports = {
  client: {
    // service: {
    //   name: 'local',
    //   localSchemaFile: __dirname + 'config/schema.graphql',
    // },
    service: {
      name: 'server',
      url: 'https://{myendpoint}/graphql',
      // optional headers
      // optional disable SSL validation check
      // skipSSLValidation: true,
      includes: ['src/**/*.{ts,tsx,js,jsx,graphql}'],
    },
    // localSchemaFile: 'config/schema.graphql',
    // includes: ['./src/**/*.js'],
    // excludes: ['**/__tests__/**'],
  },
};
```

**Comment by AntoniusGolly** [comment]
I think, you get that when you save your `apollo.config.js` file. But this error is expected when you don't use Apollo Studio and can be safely ignored. It is more important what happens when you click on the Apollo rocket icon in the status bar. When you see an error there, follow that.
