### ISSUE TITLE
Error using `schema:publish` with local .graphql schema file

### ISSUE THREAD

**Issue by aergonaut** [apollographql/apollo-tooling#672]
I am trying to publish my GraphQL schema to Apollo Engine with the `apollo schema:publish` command. [According to the docs](https://www.apollographql.com/docs/platform/schema-registry.html#schema-sources), I should be able to give `--endpoint` the path to a local .graphql file that contains my schema. However, when I try to do this, the command errors:

```
$ apollo schema:publish --endpoint=schema.graphql --key="REDACTED"
 ✔ Loading Apollo Project
 ✖ Uploading service to Engine
   → Only absolute URLs are supported
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (~/.nvm/versions/node/v9.11.2/lib/node_modules/apollo/node_modules/node-fetch/lib/index.js:1265:9)
    at ~/.nvm/versions/node/v9.11.2/lib/node_modules/apollo/node_modules/node-fetch/lib/index.js:1335:19
    at new Promise (<anonymous>)
    at fetch (~/.nvm/versions/node/v9.11.2/lib/node_modules/apollo/node_modules/node-fetch/lib/index.js:1332:9)
    at ~/.nvm/versions/node/v9.11.2/lib/node_modules/apollo/node_modules/apollo-link-http/lib/bundle.umd.js:91:17
    at new Subscription (~/
```

My GraphQL API is authenticated, so I can't point `apollo` directly at the endpoint as it won't have authentication. I was able to get around this by running my server locally and removing the authentication guards from the API endpoint, but I don't think that's a good long-term approach.

**Comment by flipxfx** [comment]
Same here. I'm writing the schema to a json file using `graphqlSync` because the endpoint is authenticated but I can't get the CLI to read the file.

**Comment by Alahel** [comment]
I tried to run even a tmp express server, serving a static graphql.json schema... but when providing an url, it seems that the url is directly read from the apollo api, not from the publish command...

**Comment by MattHartz** [comment]
@flipxfx What does your original command look like? I created a custom apollo.config.js file and put that in the cmd and still the same results.

Thanks!

**Comment by flipxfx** [comment]
It's just `apollo schema:publish` after writing the JSON file. I have `ENGINE_API_KEY` already in env.

**Comment by lirbank** [comment]
Please note that the [documentation](https://www.apollographql.com/docs/platform/editor-plugins.html#local-schemas) says `endpoint`, but it should be `url`. This config works (project is not using Engine):

```js
module.exports = {
  client: {
    service: {
      url: 'http://localhost:4000/graphql',
    },
    includes: ['{client,server}/src/**/*.{ts,tsx}'],
  },
};
```

**Comment by flipxfx** [comment]
That's documentation for editor plugins, not what the original question is. Here is the conflicting documentation that says `--endpoint` can be configured as a local file. https://www.apollographql.com/docs/engine/features/schema-history.html#schema-sources

**Comment by flipxfx** [comment]
That's documentation for editor plugins, not what the original question is. Here is the conflicting documentation that says --endpoint can be configured as a local file. https://www.apollographql.com/docs/engine/features/schema-history.html#schema-sources

**Comment by aergonaut** [comment]
Thanks @trevor-scheer
