### ISSUE TITLE
apollo codegen:generate did't work. TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by kanziw** [apollographql/apollo-tooling#678]
I am trying `codegen:generate` with npm scripts.

```
  "scripts": {
    ...
    "precodegen": "apollo service:download --endpoint=http://localhost:4000/graphql",
    "codegen": "apollo codegen:generate src/types/api.d.ts --queries='src/**/*.query.ts' --addTypename --target typescript --outputFlat"
  },
```

But I faced error..

```
TypeError: Cannot read property 'name' of undefined
    at Object.exports.getServiceName (~/XXXXX/client/node_modules/apollo-language-server/lib/config.js:66:34)
    at new ApolloConfig (~/XXXXX/client/node_modules/apollo-language-server/lib/config.js:74:29)
    at Object.exports.loadConfig (~/XXXXX/client/node_modules/apollo-language-server/lib/config.js:154:22)
    at <anonymous>
```

> `~/XXXXX/client/node_modules/apollo-language-server/lib/config.js:66:34`
![image](https://user-images.githubusercontent.com/10116129/48249556-d6580c80-e43e-11e8-9b7b-af08cfd6b092.png)

Thanks!

**Comment by kanziw** [comment]
FYI>

**Comment by amc-david** [comment]
Having the exact same issue.

**Comment by stnwk** [comment]
Would indirectly be fixed by https://github.com/apollographql/apollo-tooling/pull/676

**Comment by lukepighetti** [comment]
Also running into this and unsure how to proceed.

**Comment by kanziw** [comment]
It works at v1.9.2

```bash
$ apollo codegen:generate src/types/api.d.ts --queries='src/**/*.query.ts' --addTypename --target typescript --outputFlat
 ›   Warning: apollo update available from 1.9.2 to 2.0.8
 ✔ Loading Apollo config
 ✔ Scanning for GraphQL queries (0 found)
 ✔ Generating query files with 'typescript' target - wrote 1 files
```

**Comment by divjose** [comment]
> It works at v1.9.2.... T^T
> 
> ```shell
> $ apollo codegen:generate src/types/api.d.ts --queries='src/**/*.query.ts' --addTypename --target typescript --outputFlat
>  ›   Warning: apollo update available from 1.9.2 to 2.0.8
>  ✔ Loading Apollo config
>  ✔ Scanning for GraphQL queries (0 found)
>  ✔ Generating query files with 'typescript' target - wrote 1 files
> ```

Correct. worked with older version!

**Comment by martijnwalraven** [comment]
I believe this should have been fixed in the latest versions. Could you try again and see if that works for you?

**Comment by lukepighetti** [comment]
Still haven't found a way around this. Should I just be using `gql-gen`?

**Comment by microhubdev** [comment]
@lukepighetti : I'm also getting "no provider was created for config" error. 
Have you managed to resolve it somehow?

**Comment by 0xcaff** [comment]
I solved this issue by writing a client configuration following directions on this page: https://www.apollographql.com/docs/references/apollo-config.html

**Comment by Martinnord** [comment]
This still haven't been resolved. Was on latest version (2.1.9), but had to downgrade to 1.9.2. Any updates?

**Comment by wodCZ** [comment]
Still doesn't work in 2.4.2...

command: `apollo client:codegen -c apollo.config.js --target typescript src/api/types.ts`

> Error: No schema provider was created, because the project type was unable to be resolved from your config. Please add either a client or service config. For more information, please refer to https://bit.ly/2ByILPj

apollo.config.js
```
module.exports = {
    client: {
        service: {
            name: 'somestuff',
            url: 'https://localhost:1337/graphql/',
        }
    }
};
```

**Comment by trevor-scheer** [comment]
For those still seeing the issue, can you please provide a reproduction?

**Comment by myhendry** [comment]
i downloaded the latest version of apollo (apollo@2.4.4) and included in my package.json and ran below commands and it seems to work...

    "schema:download": "apollo service:download --endpoint=http://localhost:4000",
    "schema:generate": "apollo client:codegen --localSchemaFile=./schema.json --target=typescript --outputFlat",
    "gen:types": "yarn schema:download && yarn schema:generate"

before that, i was trying out different versions of apollo and had encountered the common problems apollo users are facing (eg no provider found, no config file found, fragments operations error etc)

**Comment by kanziw** [comment]
Sorry, I'm late!
Now, It works for me! (apollo@2.5.3) Thanks~!

```json
"precodegen": "apollo schema:download --endpoint=http://localhost:4000/graphql",
"codegen": "apollo codegen:generate src/types/api.d.ts --localSchemaFile=schema.json --includes='src/**/!(*.local).ts' --target typescript --outputFlat"
```
