### ISSUE TITLE
README mistake in sample configs?

### ISSUE THREAD

**Issue by cspotcode** [apollographql/apollo-tooling#679]
In the README here:
https://github.com/apollographql/apollo-tooling#service-settings

The example apollo config has `service` as a property of the exports object.  It's not wrapped in a `client` object like it is in the preceding examples.  Is that a typo?

**Comment by JakeDawkins** [comment]
I can't find this anymore, so I'm assuming it's been solved. `service` can be at the root of the config for graphql service projects. 

Only in client projects does `service` have to be under a `client`
