### ISSUE TITLE
`--no-addTypename` does not work

### ISSUE THREAD

**Issue by artemave** [apollographql/apollo-tooling#680]
```
$ yarn apollo client:codegen src --target=typescript --no-addTypename
$ /Users/artem/projects/inlens-web/node_modules/.bin/apollo client:codegen src --target=typescript --no-addTypename
 ›   Error: Unexpected argument: --no-addTypename
```

Looking at the code, the reason appears to be that `addTypename` flag declaration is missing `allowNo: true` option (or should not default to `true`):

![image](https://user-images.githubusercontent.com/23721/48290883-c78c4c80-e474-11e8-8782-6d60894507b4.png)

https://github.com/apollographql/apollo-tooling/blob/master/packages/apollo/src/commands/client/codegen.ts#L47,L50

npm module version: 2.0.9

**Comment by trevor-scheer** [comment]
Resolved in https://github.com/apollographql/apollo-tooling/pull/758
