### ISSUE TITLE
Support --headers for `service:push`

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/apollo-tooling#700]
Publishing a schema via an introspection against local server (as opposed to an introspection file) may require headers in the request. The config currently accepts headers, but the CLI command does not.

**Comment by yongnicholaskim** [comment]
Trying to push our schema from a remote server to Apollo Engine using the CLI:

In my terminal, I've tried:
```
apollo service:push --header='Authorization: Bearer <token>'
apollo service:push --header="Authorization: Bearer <token>"
apollo service:push --header=Authorization: Bearer <token>
```
and every time the response I get is:

`Error: Unable to validate user.`

Is this API working for anybody out there? Any suggestions on what I may be doing wrong, and how to correct it? Or is this a bug?

FWIW, I'm supplying my service name and endpoint in my apollo.config.js file. Ultimately, I would like to move my validation credentials there also, so in my terminal I can just use:

`apollo service:push`

But there's no documentation on how to structure the apollo.config.js file for the header. This is what my apollo.config.js file looks like now:

```
module.exports = {
  service: {
    name: "<service name>",
    endpoint: {
      url: "<url>"
    },
    header: {
      Authorization: "Bearer <token>"
    }
  },
  engine: {
    apiKey: "<key>",
    schemaTag: "dev-test-proxy"
  }
};
```
At this point, ANY method for correctly supplying the header, either via the CLI in my terminal, or via my apollo.config.js would be nice.

**Comment by JakeDawkins** [comment]
@yongnicholaskim I don't believe this issue has been resolved yet for CLI flags, but the `apollo.config.js` still accepts headers. Your example config had two things wrong with it: 

1. the config key for headers is `headers` not `header`. The CLI flag WOULD be `header` since you can use the `--header` flag multiple times, but the config key is `headers`
2. `headers` go under the `endpoint` key. So an example config would look like:

```
service: {
    name: 'my-cool-service',
    endpoint: {
      url: 'http://localhost:4000',
      headers: {
        authorization: 'Bearer lkjfalkfjadkfjeopknavadf',
      },
    },
  },
```

More info here: https://www.apollographql.com/docs/references/apollo-config

**Comment by JakeDawkins** [comment]
@yongnicholaskim I take it back. The `--header` flag does work with either of your first two examples you gave. You're just `required` to provide an `--endpoint` flag also. Even if you're using the default endpoint of `http://localhost:4000`. That definitely needs documentation. I'll add some now.

**Comment by jmvtrinidad** [comment]
`--header` should be after `--endpoint` option
