### ISSUE TITLE
[VSCode] resolve times bounce around

### ISSUE THREAD

**Issue by idris** [apollographql/apollo-tooling#703]
Schema resolve times inline with code is super cool!  However, when I press enter near one of those times, things get weird.  See the gif below.

![apollo-time-weird](https://user-images.githubusercontent.com/13989/48515513-e866f000-e82e-11e8-934b-89735a63f43b.gif)

It seems like you're inserting the time as a pseudo tab character or something.  I don't know what's going on. What I _do_ know is that the GitLens VSCode plugin does this _very_ well in their git blame feature (shows git blame for the line you're on).  You may be able to model yours after what they did.

(FYI, GitLens is disabled in the video above because I wanted to be sure it wasn't causing a strange interaction with Apollo)

**Comment by trevor-scheer** [comment]
Thanks for submitting this Idris!

**Comment by JakeDawkins** [comment]
Is this still an issue?

**Comment by JakeDawkins** [comment]
I'll close this for now since there's no response or other chatter around it, but if this is still happening, let me know and I will gladly reopen :)
