### ISSUE TITLE
Error using schema:publish 400 error

### ISSUE THREAD

**Issue by MattHartz** [apollographql/apollo-tooling#704]
I am trying to push my schema at a remote endpoint using "apollo schema:publish --endpoint=endpoint --key=service:key given to me by my account when creating my first service.

 √ Loading Apollo Project
 × Uploading service to Engine
   → Response not successful: Received status code 400
Error: Response not successful: Received status code 400
    at throwServerError (C:/Users/asdf/AppData/Roaming/npm/node_modules/apollo/node_modules/apollo-link-http-common/lib/bundle.umd.js:36:21)
    at C:/Users/asdf/AppData/Roaming/npm/node_modules/apollo/node_modules/apollo-link-http-common/lib/bundle.umd.js:62:17

I was able to use another npm module to create a .graphql file. "get-graphql-schema" and wrote it to a .graphql file

Here is that .graphql file

"""
The `Date` scalar type represents a year, month and day in accordance with the
[ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) standard.
"""
scalar Date

"""
The `DateTime` scalar type represents a date and time. `DateTime` expects
timestamps to be formatted in accordance with the
[ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) standard.
"""
scalar DateTime

"""
The `DateTimeOffset` scalar type represents a date, time and offset from UTC.
`DateTimeOffset` expects timestamps to be formatted in accordance with the
[ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) standard.
"""
scalar DateTimeOffset

scalar Decimal

type DroidType {
  """The Id of the Droid."""
  id: Int!

  """The name of the Droid."""
  name: String
}

"""
The `Milliseconds` scalar type represents a period of time represented as the total number of milliseconds.
"""
scalar Milliseconds

type Query {
  droid: DroidType
}

"""
The `Seconds` scalar type represents a period of time represented as the total number of seconds.
"""
scalar Seconds

**Comment by yangchongduo** [comment]
Can an official person come out to answer this question?
How did you deal with it?

**Comment by yangchongduo** [comment]
✔ Loading Apollo Project
  ✖ Uploading service to Engine
    → Unexpected token < in JSON at position 0
ServerParseError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at ~/.npm/_npx/15228/lib/node_modules/apollo/node_modules/apollo-link-http-common/lib/bundle.umd.js:49:29

**Comment by Gomah** [comment]
Had the same issue using `NODE_ENV="production"` within the same `.env` file; Using anything but production fixed my issue.

**Comment by mxdevmanuel** [comment]
When the environment variable is productos, apollo automatically disables introspection as a production best practice, as far as i know

**Comment by JakeDawkins** [comment]
Yeah, if introspection is disabled (in production) and you're relying on an endpoint to publish the schema, this can't work. you'd need to use schema files or a dev endpoint for this to work.

Since I don't think this is an actual bug (at least currently), I'll close this

**Comment by maurocolella** [comment]
@JakeDawkins this is affecting us significantly when using tracing or federated tracing, which is something we want to do in production.

On our (Google Cloud) environment, App Engine, `NODE_ENV` is set to production by default. We want to capture detailed traces, and we want to do this per environment (using variants), but schema upload and updates fail a a side-effect of this restriction.

We could always override `NODE_ENV` (tested) but I'd prefer not as it could affect other parts of the application.
