### ISSUE TITLE
service:check should support --localSchemaFile

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/apollo-tooling#716]
A user should be able to validate their current schema against Engine with an introspection result or SDL

**Comment by LennyPenny** [comment]
Yea I just ran into the same roadblock, sadly our CI environment makes it kinda difficult to self host the schema at build time

**Comment by guoliu** [comment]
Any updates on this issue? It's bizarre that `service:push` support `localSchemaFile` but `service:check` doesn't 🤔

**Comment by pscarey** [comment]
Happy to take this up as a PR, will look into it next week. 

Note, your docs [https://www.apollographql.com/docs/platform/integrations.html#check-schema-on-ci](here) imply this is possible already:

> Note: Your apollo service:check command needs a source to from which to fetch your schema. This is most commonly provided as a URL to a running server (with introspection enabled), but can also be provided as a path to a file with your shcema in it. See other options here.
