### ISSUE TITLE
Can't resolve apollo-client in react-apollo

### ISSUE THREAD

**Issue by mwarger** [apollographql/apollo-tooling#721]
I'm getting the following error when trying to run a React project using TypeScript.

This occurred after upgrading from apollo 1.9.2 to 2.1.2.

This is strange, because it's complaining about what look to be different packages, but something about this version trips it up.

Please let me know if any other information would be helpful.  Thank you.

Error:
```
Failed to compile.

./node_modules/react-apollo/react-apollo.browser.umd.js
Module not found: Can't resolve 'apollo-client' in 'project\node_modules\react-apollo'
```

**Comment by trevor-scheer** [comment]
@mwarger that is bizarre, do you have a repo where I could reproduce this?

**Comment by mwarger** [comment]
I do not, but I can try to make one.

**Comment by fgiarritiello** [comment]
@mwarger Did you resolve this? I'm getting the same error

**Comment by mwarger** [comment]
@fgiarritiello I have not, but I have started a repo for reproduction.  Give me a couple days and I will follow-up.

To be clear - downgrading `apollo` back to 1.9.2 fixed the issue for me temporarily.

**Comment by mwarger** [comment]
Is that apollo?  I think we may be talking about different packages.  I was referring to https://www.npmjs.com/package/apollo.

**Comment by fgiarritiello** [comment]
react-apollo

**Comment by xdevnull** [comment]
Any update?

**Comment by xdevnull** [comment]
Seems not a bug. Following this https://s3.amazonaws.com/apollo-docs-1.x/initialization.html#installation
will cause the error on newer version of apollo. (v2)

**Comment by JakeDawkins** [comment]
Is this still an issue?

**Comment by mwarger** [comment]
No.
