### ISSUE TITLE
tagName not being applied when searching documents.

### ISSUE THREAD

**Issue by berrigan** [apollographql/apollo-tooling#723]
It would seem that `tagName` argument is no longer being applied.

This seems to come from `loadAndMergeQueryDocuments` (`packages/apollo-codegen-core/src/loading.ts`) no longer being called in `generate` (`packages/apollo/src/generate.ts`).

This can be doubly seen with the `tagName` parameter to `generate` no longer being used.

Combined with the regression seen in https://github.com/apollographql/apollo-tooling/issues/706#issuecomment-439001881, it seems impossible to apply document/query searching to a subset of files.

**Comment by trevor-scheer** [comment]
Thanks for submitting an issue @berrigan! I'm off through the holiday so no promises as to how soon I can get to this but it's next on my list!
