### ISSUE TITLE
VS Code - Integrate apollo commands

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/apollo-tooling#725]
Add commands typically run from the `apollo` CLI to the VS Code command palette.

**Comment by buzinas** [comment]
Also, how about adding a way to execute the query you're writing for testing purposes?

Prisma's extension does that, and it's the only thing I'm missing after switching to apollo:

![codelens](https://user-images.githubusercontent.com/15905/47411584-82c0a000-d769-11e8-983b-f2ed49bea922.png)

**Comment by JakeDawkins** [comment]
I don't think these things are going to be added in the near future. The commands are too configurable, and the query execution is a much larger discussion around the future of the extension and graphiql/playground/etc. I'll close this for now.
