### ISSUE TITLE
fix : Uncomment test suite

### ISSUE THREAD

**Issue by andykenward** [apollographql/apollo-tooling#737]
The apollo commands service tests have been commented out for the summit.

Can this https://github.com/apollographql/apollo-tooling/commit/04452e584e572906b36cfb6654def6fa4a9b8de2 be reverted / fixed?

As versions have been released without these tests running.

**Comment by jbaxleyiii** [comment]
@andykenward we are working to get these test suites back working asap! @JakeDawkins is rewriting the file mocking system that was a hack within codegen (and not the new language server) to make it work. Should be back on line this week!

**Comment by JakeDawkins** [comment]
This is an ongoing project that gets worked on as features are worked on, so I'm going to close this issue, but it's not abandoned :)
