### ISSUE TITLE
Apollo Graphql Extension reported as malicious and disabled

### ISSUE THREAD

**Issue by tomitrescak** [apollographql/apollo-tooling#745]
Hi, the Apollo extension is disabled in VS Code with the text that it is malicious ;( What is this sorcery? I was very much enjoying this extension ;(.

**Comment by tsaiDavid** [comment]
@tomitrescak - see this https://github.com/apollographql/apollo-tooling/issues/742

**Comment by tomitrescak** [comment]
@tsaiDavid thanks, I was searching for this issue with text malicious and couldn't find it. All good, will wait for fix.
