### ISSUE TITLE
schema:publish rejects official certificates

### ISSUE THREAD

**Issue by StefanFeederle** [apollographql/apollo-tooling#757]
The CLI rejects my official SSL certificate:

```
FetchError: request to https://server.myhiddendomain.de:3010/graphql failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (C:/Users/Peter Feederle/AppData/Roaming/npm/node_modules/apollo/node_modules/node-fetch/lib/index.js:1444:11)
```

The CLI can't verify the certificate that is officially signed by lets encrypt.
The exact same endpoint is trusted in Chrome, Firefox, ...

I'm on apollo/2.1.6 win32-x64 node-v8.9.4

**Comment by trevor-scheer** [comment]
Hey @StefanFeederle, is this still an ongoing issue for you? If it is, I'll leave the issue open - otherwise I'll close. Thanks!
