### ISSUE TITLE
Provide warning when no apollo.config.js found

### ISSUE THREAD

**Issue by evans** [apollographql/apollo-tooling#771]
The cli should confirm that no apollo.config.js was found(maybe providing the pwd for the benefit of ci) if no api key was detected during the startup. When no config or service name is found, then we should probably also stop execution without moving forward to the next step.

![image](https://user-images.githubusercontent.com/5565407/49321823-f79c9d80-f4be-11e8-8275-77dbccee6706.png)

**Comment by cheapsteak** [comment]
Perhaps the warning could include a link to relevant docs on apollo.config.js?

**Comment by JakeDawkins** [comment]
This should be resolved by now :) Thanks for noting it
