### ISSUE TITLE
Possible regression: no longer able to extend with client schema

### ISSUE THREAD

**Issue by mike-marcacci** [apollographql/apollo-tooling#786]
As first noted in #731, the `--clientSchema` CLI option has been removed. However, there is no documentation on how to reimplement the desired behavior, especially when using `--localSchemaFile`.

I see that @bsunderhus got it working in his setup somehow, but looking at the source I'm not sure how. Has this ability been removed?

I've resorted to just applying the client query myself, with this old script I had laying around, in case anyone else finds this necessary:

```js
#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const { introspectionFromSchema } = require("graphql/utilities");
const { makeExecutableSchema } = require("graphql-tools");
const { fileLoader, mergeTypes } = require("merge-graphql-schemas");

// Make sure unhandled errors in async code are propagated correctly
process.on("uncaughtException", error => {
  console.error(error);
  process.exit(1);
});

process.on("unhandledRejection", error => {
  throw error;
});

async function introspectSchema(input, output) {
  const schemas = [].concat(...input.map(i => fileLoader(i)));
  const typeDefs = mergeTypes(schemas, {
    all: true
  });

  const schema = await makeExecutableSchema({
    typeDefs,
    resolverValidationOptions: { requireResolversForResolveType: false }
  });
  const introspection = await introspectionFromSchema(schema);
  const json = JSON.stringify(introspection, null, 2);
  fs.writeFileSync(output, json);
}

const input = [
  path.resolve(__dirname, "../../../schema/*.graphql"),
  path.resolve(__dirname, "../src/schema/*.graphql")
];

const output = path.resolve(
  __dirname,
  "../src/schema/__generated__/schema.json"
);

// Generate an introspection JSON format from remote GraphQL server merging
// with any local GraphQL schemas
introspectSchema(input, output, true);
```

**Comment by bsunderhus** [comment]
@mike-marcacci  as I said in #731 , apparently the _codegen_ finds all the `.graphql` code in your files. This is the comand that I'm using. 

```shell
apollo codegen:generate __generated-types --target typescript --includes=src/data/* --globalTypesFile src/data/__generated-types.ts
```

My client schemas files are `.graphql` files laying around the `src/data` folder. The apollo tooling is basically finding all the `.graphql` files inside `src/data` and everything works "fine". My biggest complain is the lack of documentation on this big behaviour change

**Comment by mike-marcacci** [comment]
Aha! Thanks @bsunderhus I had `--queries=\"src/**/*.js\"` instead of `--includes=\"src/**/*{js,graphql}\"`. I completely agree: this is a great change that allows far greater flexibility RE organization of schema extensions... if it was just documented :)
