### ISSUE TITLE
VSCode: Only execute extension on currently opened files

### ISSUE THREAD

**Issue by damassi** [apollographql/apollo-tooling#805]
Right now the extension runs over the entire project, leading to issues in distant parts of the codebase appearing in the errors panel even though a dev might not be working anywhere near. Ideally this would behave like vscode-typescript where it only validates files that are currently open in tabs or recently closed, or at least filters out issues from unopened files.

**Comment by JakeDawkins** [comment]
I'm not sure if there's an easy solution to this right now, since the language server _has_ to scan every file. We allow types to be used/extended in any file, as well as support the ability to find other references to types in a project.
