### ISSUE TITLE
Document `apollo.config.js`'s `engine` options

### ISSUE THREAD

**Issue by justinanastos** [apollographql/apollo-tooling#806]
The `engine` key in `apollo.config.js` is required to download the schema from apollo engine but it's undocumented.

To download a schema from engine, one must have the following minimum `apollo.config.js`:

```js
module.exports = {
  client: {
    service: 'my-service-name'
  },
  engine: {
    apiKey: 'service:my-service-name:abcdefg'
  }
};
```

**Comment by trevor-scheer** [comment]
@justinanastos, we want to recommend the `.env` file approach rather than having this committed in the config.  Maybe that's what we need to document better?

Relevant code:
https://github.com/apollographql/apollo-tooling/blob/master/packages/apollo-language-server/src/config.ts#L309

**Comment by justinanastos** [comment]
Agreed @trevor-scheer !
