### ISSUE TITLE
.graphqlconfig support

### ISSUE THREAD

**Issue by homburg** [apollographql/apollo-tooling#811]
Currently it is not supported to load configuration from the standard `.graphqlconfig`.

It was removed in 202d3f5a3aeeaf0e2a5854c7eb8e725d26440b41 included in #497 

Are there any plans to support `.graphqlconfig` again?

**Comment by dfreeman** [comment]
Would the team here be open to a PR reintroducing `.graphqlconfig` support, or was the removal deliberate? Is it not expressive enough to capture things that are important for Apollo projects? I'd love to get a sense of the motivations 🙂 

The broader ecosystem seems to be standardizing on it for things like editor support and other tooling, and Apollo's own [eslint-plugin-graphql](https://github.com/apollographql/eslint-plugin-graphql) supports reading from `.graphqlconfig`. It would be nice not to need to duplicate information in different places for different tools.

**Comment by JakeDawkins** [comment]
We don't have plans for supporting `.graphqlconfig` right now. Part of the reason for this is the constant evolution of the needs for an apollo config. We need a lot of configuration options around engine settings, and there's a chance for more complicated extensions to the config in the future with our federation work.

Supporting other config formats (or making them the primary) would be pretty difficult, and very verbose.

This _may_ someday be up for consideration, but right now we don't have the bandwidth to work on this.
