### ISSUE TITLE
Your extension have been featured!

### ISSUE THREAD

**Issue by auchenberg** [apollographql/apollo-tooling#814]
Hi,

It's Kenneth from VS Code. I'm reaching out to tell you that we have featured your awesome VS Code extension on our marketplace https://marketplace.visualstudio.com/#VSCode.

Please work with your community to resolve any major issues, as you'll probably see a significant bump in new users trying your extension.

Thanks for the great work, and happy coding!

/k

Kenneth Auchenberg
Visual Studio Code
Program Manager, Microsoft

**Comment by trevor-scheer** [comment]
@auchenberg that's wonderful news, thanks for sharing with us!
