### ISSUE TITLE
client:check throws error if project is nested in any folder that isn't src

### ISSUE THREAD

**Issue by michael-watson** [apollographql/apollo-tooling#830]
When trying to use `apollo client:check`, I am receiving errors unless I add `includes` as an array. The screenshot below shows the terminal and `apollo.config.js` file associated with it. 

<img width="1331" alt="screen shot 2018-12-13 at 3 26 14 pm" src="https://user-images.githubusercontent.com/8645958/49974847-0e47e900-fef0-11e8-9593-c3410ddefdce.png">

**Actual outcome:**   
With the `includes` line is commented out, receive an error when running my command.
With the `includes` line not commented out, everything works as expected.

**Intended outcome:**   
All files and folders in the same directory of `apollo.config.js` should be inspected for queries or provide an error that reminds users to include `include`.

After [further digging](https://github.com/apollographql/apollo-tooling/blob/08699fab940d675eac30c487c0b6cbd4137bc84a/packages/vscode-apollo/tsconfig.json#L7), I was able to find that the extension is only looking for `src` folders. The documentation should be updated to reflect this. Any other folder structure would require the `includes` option.

**Comment by trevor-scheer** [comment]
This is resolved with better messaging now:
https://github.com/apollographql/apollo-tooling/blob/1c24b14871bfa96f35c3f326a9f1022018c57468/packages/apollo-language-server/src/project/client.ts#L120
