### ISSUE TITLE
Using `client:codegen` in a precommit hook with lint-staged

### ISSUE THREAD

**Issue by glennreyes** [apollographql/apollo-tooling#846]
Hey all,

I am trying to add `apollo client:codegen` to my lint-staged setup and have this so far:

```json
"*.graphql": [
  "apollo client:codegen ./__generated__/types.ts --outputFlat --target typescript --includes",
  "git add"
],
```

Since this will remove all existing types in the `__generated__/types.ts` file that are not staged, I tried then to use following:

```json
"*.graphql": [
  "apollo client:codegen ./__generated__ --outputFlat --target typescript --includes",
  "git add"
],
```

Note that this will create separate files for each mutations, queries, subscriptions, fragments and global types. The problem here is that it can remove all global types that are not staged on git.

Is there a way to generate the types of files with GraphQL operations in `--includes` without deleting the other types? (So that I can use it in lint-staged)

**Comment by trevor-scheer** [comment]
Hey @glennreyes, did you get around to figuring this out? If yes, would you mind posting what you came up with? If not, I'm not quite sure I understand the issue. Could you go into a bit more detail? Especially w.r.t:
>Since this will remove all existing types in the __generated__/types.ts file that are not staged, I tried then to use following

Running codegen should always give you the most up-to-date types based on schema and queries that were parsed. I'm not sure what could be missing or removed, as you say.

Side note: `--includes` takes an argument, I'm not sure that providing the flag is doing anything for you here.

**Comment by hboylan** [comment]
I've just encountered this issue as well. When the codegen command is run from `lint-staged` the staged files are passed as command arguments. In this case, `--includes` accepts the staged file paths but `__generated__/globalTypes.ts` is missing the types that are not "included".

**Comment by hboylan** [comment]
@glennreyes I settled on the following workaround to have `echo` absorb the trailing list of files from `lint-staged` running the command instead of trying to use `--includes`.
```json
"scripts": {
  "codegen:commit": "npm run codegen && git add src/graphql/__generated && echo"
},
"lint-staged": {
  "src/graphql/!(__generated__)/*": [
    "npm run codegen:commit"
  ]
}
```
