### ISSUE TITLE
Add @client directive support in VS Code

### ISSUE THREAD

**Issue by joltmode** [apollographql/apollo-tooling#847]
I am trying to set up IDE to ease GraphQL development for our junior team members. And not gonna lie, to help myself too.

I have a query that operates on client state:

```
import gql from 'graphql-tag';

export default gql`
mutation LoadProfile($profile: ProfileInput!) {
  loadProfile(profile: $profile) @client {
    accessToken
    avatar
    name
  }
}
`
```

Though, removing the `@client` does not invalidate the query.

![image](https://user-images.githubusercontent.com/1030080/50227540-a2adc200-03ae-11e9-8abe-7cf921fa148a.png)

Is this expected behaviour or I have misconfigured something or it's a bug?

---

Otherwise, everything seem to be working - autocompletion for both client queries and remote queries, go-to definition, validation, for instance:

![image](https://user-images.githubusercontent.com/1030080/50227641-df79b900-03ae-11e9-8824-0e86236e5170.png)

Just that dropping `@client` from client queries doesn't throw anything.

**Comment by aleccool213** [comment]
I don't think there is support for knowing if a field comes from a remote source or a client source in vscode apollo yet.

**Comment by JakeDawkins** [comment]
Good news! This is actually being worked on right now by @jgzuke! I'll assign him and he can add his PR to this issue when one is open 🙌
