### ISSUE TITLE
VS Code - Strange gql Template Syntax Highlighting

### ISSUE THREAD

**Issue by micchickenburger** [apollographql/apollo-tooling#848]
There seems to be strange syntax highlighting in the Apollo GraphQL VS Code extension when using single quote descriptions:

<img width="439" alt="image" src="https://user-images.githubusercontent.com/4521230/50245458-2314f880-0398-11e9-9920-0eb129845ffb.png">

Multiline descriptions work fine though:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/4521230/50245739-eeee0780-0398-11e9-99bc-17dc3471199b.png">

Perhaps I'm wrong in assuming that single quote descriptions are valid, but they are used in the example at [https://facebook.github.io/graphql/draft/#sec-Descriptions](https://facebook.github.io/graphql/draft/#sec-Descriptions).

VS Code version 1.30.0
Apollo GraphQL Extension version 1.2.7

**Comment by trevor-scheer** [comment]
Thanks for reporting @micchickenburger, I'll land #1270 shortly and resolve this!
