### ISSUE TITLE
Typescript Modern Root Directory

### ISSUE THREAD

**Issue by 0xcaff** [apollographql/apollo-tooling#860]
I'm using the following project structure:

```
.
├── package.json
├── node_modules
│  └── @forte-music/schema
│      └── schema.graphql
└── src
   ├── __generated__
   └── query.ts
```

In package json

```json
  "apollo": {
    "client": {
      "service": {
        "name": "forte",
        "localSchemaFile": "./node_modules/@forte-music/schema/schema.graphql"
      }
    }
  },
```

When using

```bash
apollo codegen:generate --queries 'src/**/*.{graphql,ts,tsx}' --target typescript
```

A `__generated__` folder is added in the project root.

```
__generated__
└── globalTypes.ts
```

Is there a way to specify an output root? I would like the `__generated__` folder to be in the src folder and nothing outside src to be affected.

**Comment by trevor-scheer** [comment]
Hey @0xcaff, sorry for the delayed response here. It looks like you may have found a way to achieve what you needed, but we also have the `--outputFlat` flag which is what I think you wanted. The README at the root of this project enumerates all the possible flags. You can get the same printout by running `npx apollo client:codegen --help`. Hope this is helpful - feel free to reopen a separate issue if you're still having any problems 👍

**Comment by 0xcaff** [comment]
No, `--outputFlat` puts all the output into a single directory. This is not the desired behavior. I want to put the `globalTypes.ts` under `src/__generated__/globalTypes.ts` instead of `./__generated__/globalTypes.ts`.

**Comment by narciero** [comment]
I am also having the same issue...trying to generate the `globalTypes.ts` under the `src/__generated__` folder instead of the root of my project (where `package.json` is)

**Comment by masashiswingle** [comment]
I am also having this issue too. 

This causes typescript build folder structure complications bc it imports a file outside of src.

**Comment by langarus** [comment]
@masashiswingle  any luck on not automatically creating the generated folder?
