### ISSUE TITLE
how to read the schema from a graphql file with apollo 2

### ISSUE THREAD

**Issue by e-cherrier** [apollographql/apollo-tooling#869]
Hi,

with apollo 1.9.2 I'm used to make introspection of the graphql schema using a file as endpoint (that way the server does not need to run). Here the 1.9 command:

`apollo schema:download --endpoint ./schema/app.graphql ./schema/schema.json`

now with apollo 2, that command, renamed service:download, supports only an url, and I got that error
    → Only absolute URLs are supported

I did not find in the doc how to do that now. thanks for your help.

**Comment by JakeDawkins** [comment]
hmm... this is an interesting use case, and I'm somewhat surprised it worked with the `--endpoint` flag to begin with.

Have you tried defining an `apollo.config.js` with something like the following

```
module.exports = {
  service: {
    localSchemaFile: './path/to/schema.graphql',
  },
};
```

**Comment by e-cherrier** [comment]
Hello Jake,
many thanks for your answer. that is solving my issue!
Now with the solution that look's like so simple! I even found it in the doc :(... :D

note that in 1.9 giving a file to the endpoint parameter was described in the doc.

**Comment by JakeDawkins** [comment]
Great! Glad to hear it’s working 😊
