### ISSUE TITLE
Running codegen against several schemas

### ISSUE THREAD

**Issue by ivstas** [apollographql/apollo-tooling#875]
I have a use case when I need to perform code generation against 2 schemas:
- the first one is a result of introspection retrieved from the backend
- the second one is a local state managed by apollo-link-state

It looks like all the code generation was built on the assumption there would be only one schema, it doesn't let me specify more than 1 schema.
Are there any workarounds to this?

**Comment by vadistic** [comment]
I'm not sure what are your requirements, but this works for me using local state & apollo engine.

Your local schemas are autodetected and merged when it's SDL (as oposed to OperationDefinitons)

```js
// apollo.config.js
require('dotenv').config()

module.exports = {
  client: {
    service: 'my-service-name',
    clientOnlyDirectives: ['connection', 'type'],
    clientSchemaDirectives: ['client', 'rest'],
    includes: ['src/**/*.{ts,tsx}'],
    excludes: ['src/generated/*.graphql']
  },
  engine: {
    apiKey: process.env.ENGINE_API_KEY
  }
}
```

The codegen on queries then runs against downloaded introspection (from apollo engine) and includes the local schema sdl.

```ts
// src/schema.ts
export const schema = gql`
  extend type Query {
    localField: String!
    localType: LocalType!
  }

  type LocalType {
    id: ID!
    name: String!
  }
`
```

```tsx
// src/components/some-components.tsx
const exampleQuery = gql`
  query ExampleQuery($where: UserWhereUniqueInput!) {
    localField @client
    localType {
      id
      name
    }
    user(where: $where) {
      ...User
    }
  }

  ${UserFragment}
`

```

Result:
```ts
// src/generated/queries.ts
export interface ExampleQuery {
  localField: string;
  localType: ExampleQuery_localType;
  user: ExampleQuery_user | null;
}
```

**Comment by elliottsj** [comment]
Thanks @vadistic!

I was even able to get mine working using a `.graphql` SDL file instead of a `schema.ts` file. My config:

```js
// apollo.config.js

module.exports = {
  client: {
    service: {
      name: 'my-app',
      localSchemaFile: './graphql/server.graphql',
    },
    includes: [
      './graphql/clientOnly.graphql',
      './common/**/*.{ts,tsx}',
    ],
  },
};
```

`server.graphql` contains the GraphQL types from the server, and I'm defining my client-only types in `clientOnly.graphql`. `apollo client:codegen` is able to pick up both and generate TypeScript types from the merged schema.

**Comment by JakeDawkins** [comment]
Yep! That's how this is supposed to work. In practice, you could define client types next to their queries/mutations/resolvers, and as long as those typedefs are able to be found via the `includes`, it should work like a charm! 

Closing this since it looks resolved :)
