### ISSUE TITLE
VS Code - autocomplete not working in all files

### ISSUE THREAD

**Issue by subhash** [apollographql/apollo-tooling#883]
When `apollo.config.js` is thus:
```
module.exports = {
    client: {
        name: 'graphitti schema',
        service: 'graphitti-schema',
    }
};
```
and `.env` set appropriately to point to Apollo Engine service, VS Code shows both autocomplete and metrics working in `src/see.graphql` file:
![works](https://user-images.githubusercontent.com/87746/50947290-84c21180-14c3-11e9-94c6-c1757aa7b036.png)

But when `apollo.config.js` is updated to include files in other directories:
```
module.exports = {
    client: {
        name: 'graphitti schema',
        service: 'graphitti-schema',
        includes: [__dirname+ '/client/**/*.js', './client/**/*.graphql', './src/**/*.graphql']
    }
};
```

VS Code continues to show metrics for the included js files, not does not show autocomplete or type information on hover:

![bug](https://user-images.githubusercontent.com/87746/50947322-baff9100-14c3-11e9-9131-1156e1965375.png)

What am I missing?

**Comment by DavyBello** [comment]
I have the same issue.
It seems vs code autocomplete currently only work in the src folder

**Comment by abhimanyuPathania** [comment]
Adding `includes` field in `apollo.config.js` seems to break the extension for me. 'Unable to load the service stats' error and does not show any autocomplete or types.

**Comment by MakcStudio** [comment]
work example

includes: ['wwwroot/*.ts, wwwroot/**/*.ts', 'wwwroot/**/**/*.ts']

**Comment by mliq** [comment]
Same problem here. I set up a project without a `src` folder for the first time because Next.js does not allow you to put everything in a `src` folder. Now I'm caught in the 'convention over configuration' dead zone.

**Comment by odensc** [comment]
To anyone subscribed to this issue and still looking for a solution - the workaround described in #1002 worked for me. Simply remove the `./` from your `includes` paths and everything should work!

**Comment by trevor-scheer** [comment]
Thanks for posting this @odensc, we've got a fix for this in the works 😄 (I just referenced this issue from the PR so it will auto-close)
