### ISSUE TITLE
Deprecate apollo v1.x

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/apollo-tooling#903]
Deprecate the npm package and document the deprecation in the README

**Comment by JakeDawkins** [comment]
Should we still do this @trevor-scheer? Since apollo-ios still uses 1.x, could that cause any issues?

**Comment by designatednerd** [comment]
I believe that it will - I would like to move to 2.x soon but I'm not quite sure what that's going to involve.

**Comment by JakeDawkins** [comment]
👍 I'll close this issue _for now_, but we can revisit later!
