### ISSUE TITLE
[codegen] In watch mode does not tracked changes in schema file

### ISSUE THREAD

**Issue by nodkz** [apollographql/apollo-tooling#906]
I have such package.json script

```
"gen": "apollo client:codegen --target=typescript --localSchemaFile=../server/src/schema/__generated__/schema.graphql --includes=./src/**/*.{ts,tsx} --tagName gql --watch",
```

When I change components in files correctly regenerated.

BUT. When I regenerate `schema.graphql` file it does not regenerate files.

EXPECTED BEHAVIOUR: regenerate all files if `localSchemaFile` changed

**Comment by JakeDawkins** [comment]
@nodkz Is this still an issue? It _may_ have been fixed with some recent releases

**Comment by hwillson** [comment]
Closing as this should be fixed in recent versions. Let us know otherwise - thanks!

**Comment by hoorncj** [comment]
Still seems like an issue: #1991
