### ISSUE TITLE
Cannot read property 'getMutationType' of undefined

### ISSUE THREAD

**Issue by Eldhopj** [apollographql/apollo-tooling#908]
```
Warning: apollo update available from 1.9.2 to 2.1.8
[12:43:55] Loading Apollo config [started]
[12:43:55] Loading Apollo config [completed]
[12:43:55] Resolving GraphQL document sets and dependencies [started]
[12:43:55] Scanning for GraphQL queries (5 found) [title changed]
[12:43:55] Scanning for GraphQL queries (5 found) [completed]
[12:43:55] Generating query files [started]
[12:43:55] Generating query files with 'swift' target [title changed]
[12:43:55] Generating query files with 'swift' target [failed]
[12:43:55] → Cannot read property 'getMutationType' of undefined
TypeError: Cannot read property 'getMutationType' of undefined
```
Getting this error 
i researched a bit about it and i gone through many steps as per mentioned in internet 
1. Moving schema.json file into the place where AppDelegate lies
2. `sudo npm install --save graphql` Updating graphQl dependencies
3. And i upgraded my apollo to using `sudo npm install -g apollo@2.1.8 ` and i checked it **apollo/2.1.8 darwin-x64 node-v10.14.2** (checked from the project root folder)
4. `sudo npm install -g apollo` upgraded into latest apollo 2.3.0

even all these steps i still getting the error , i am currently using the script from the apollo graphql ios documentation , and the version i am using is 0.9.5

**Comment by horaciosolorio** [comment]
Same issue :(

**Comment by Eldhopj** [comment]
@horaciosolorio downgrade to apollo codegen and to apollo 0.7.0 there is no issue

**Comment by JinkProject** [comment]
@Eldhopj How did you downgrade?

**Comment by JakeDawkins** [comment]
Apollo 2.x isn't completely compatible with 1.x commands. Especially around codegen. From first glance, this looks like a config issue, and a schema isn't being loaded. I'd recommend using the latest version of apollo (I think 2.9.2 right now) and follow [this guide](https://www.apollographql.com/docs/references/apollo-config) to setup your project.

@JinkProject If you (or anyone else in this thread) is having issues still, can you provide more detailed info about your project setup and config file/flags?
