### ISSUE TITLE
[codegen] output file argument is not accepted and throws error

### ISSUE THREAD

**Issue by davidLeonardi** [apollographql/apollo-tooling#909]
I'm running the following command:

`apollo codegen:generate --queries=./src/**/*.tsx --schema=./schema.json --outputFlat --target=typescript ./src/schemaTypes.ts`

This is while using `apollo/2.3.0 darwin-x64 node-v11.6.0`.

I get the following error:

```> apollo codegen:generate --queries=./src/**/*.tsx --schema=./schema.json --outputFlat --target=typescript ./src/schemaTypes.ts

 ›   Error: Unexpected argument: ./src/schemaTypes.ts
 ›   See more help with --help```

**Comment by sebastianseilund** [comment]
I think you need to quote the glob pattern you set in `--queries`. Otherwise it'll expand into multiple arguments. Your command above will be executed as:

```sh
apollo codegen:generate --queries=./src/queries/Query1.tsx ./src/queries/Query2.tsx ...
```

Which `apollo` does not understand.

Try this:

```sh
apollo codegen:generate --includes='./src/**/*.tsx' --localSchemaFile =./schema.json --outputFlat --target=typescript ./src/schemaTypes.ts
```

(I also changed some deprecated flag names)

**Comment by JakeDawkins** [comment]
I think this was resolved, so I'm going to close this. Let me know if that's not true :)
