### ISSUE TITLE
client:codegen is broken

### ISSUE THREAD

**Issue by liron-navon** [apollographql/apollo-tooling#946]
Maybe I'm just not reading the documentation right, but there is no explanation of this issue, I have no idea what the error logs even mean. Does "client:codegen" not supposed to generate type definitions?

**Intended outcome:**
I'm trying to generate type definitions, so it should generate types

**Actual outcome:**
Doesn't generate types and shows errors

**How to reproduce the issue:**
Create a graphql server and run:
```
apollo client:codegen myFile.ts --target=typescript --endpoint=http://localhost:3000/graphql
```

**Versions**

"apollo-server": "^2.0.5",
"graphql": "^0.13.2",
"apollo": "^2.3.1".

I'm getting these errors for all of the types, I have no idea what that even means...

```
 ›   Type "Writer" already exists in the schema. It cannot also be defined in this type definition.
 ›
 ›   Field "Writer.id" already exists in the schema. It cannot also be defined in this type extension.
 ›
 ›   Field "Writer.name" already exists in the schema. It cannot also be defined in this type extension.
....
```

If I try to use schema:download and then generate the types from a local file using:

```
apollo client:codegen file.ts --target=typescript --localSchemaFile=.graphql/schema.json
```

I get this error:

```
    Generating query files
 ›   Error: Error initializing Apollo GraphQL project "Unnamed Project": Error: Error in "Loading schema for Unnamed Project": TypeError: 
 ›   graphql_1.isTypeSystemDefinitionNode is not a function

```

**Comment by vadistic** [comment]
Wait, one more idea

> How to reproduce the issue:
Create a graphql server and run:

You're trying to generate typings for server? I.e get types and resolvers singatures from server SDL for apollo-server? If thats the case then apollo's `client:codegen` is not a tool for that. It generate typings for client-side graphql queries - `OperationDefinitionNodes`

You'll want to use something like https://github.com/dotansimha/graphql-code-generator or https://github.com/prisma/graphqlgen for server side

**Comment by liron-navon** [comment]
@vadistic That was not clear from the documentation, especially since it does allow me to download the DSL.
Sorry for the false alarm then, but please update the documentation maybe? mention that it is only for clients?

**Comment by vadistic** [comment]
Well - to clarify: apollo cli allow downloading server SDL for client type generation without continuously running endpoint (or apollo engine). It also does codegen on your server & client side SDL - but it's used for generating types for Query & Mutation operations.

Tbh I also tried to use it for server schema some time ago, so maybe docs are slightly lacking a word or two. But you know - it's **client**:codegen so maybe we should know better^^

**Comment by JakeDawkins** [comment]
@liron-navon @vadistic glad this got sorted out! We're still working a bit on clarifying our errors–they're a bit all over the place at the moment, so thanks for your patience 🙈

We're working on some of our platform/cli docs as well pretty soon, so I'll keep this in mind. Thanks for bringing it up! If this issue is good to go then, I'll close it. If not, feel free to say so 😄

**Comment by madmaxlax** [comment]
> Wait, one more idea
> 
> > How to reproduce the issue:
> > Create a graphql server and run:
> 
> You're trying to generate typings for server? I.e get types and resolvers singatures from server SDL for apollo-server? If thats the case then apollo's `client:codegen` is not a tool for that. It generate typings for client-side graphql queries - `OperationDefinitionNodes`
> 
> You'll want to use something like https://github.com/dotansimha/graphql-code-generator or https://github.com/prisma/graphqlgen for server side

this was totally what i was looking for, thank you! @vadistic
