### ISSUE TITLE
Error: Cannot find module core-js/proposals/array-flat-and-flat-map

### ISSUE THREAD

**Issue by mtmckenna** [apollographql/apollo-tooling#962]
**Intended outcome:**

Trying to install/run a serverless app using `apollo-server-lambda`.

**Actual outcome:**

When running `apollo-server-lambda` v2.3.3, I get an error when running the server in `apollo-env`. That error looks like this:

```
'Error: Cannot find module \'core-js/proposals/array-flat-and-flat-map\'',
```
I think the issue is that `apollo-env` pins the `core-js` dependency to `^3.0.0-beta.3`, which currently resolves to `3.0.0-beta.12`. From the looks of it, the issue is that, between [beta.11](https://github.com/zloirock/core-js/blob/v3.0.0-beta.11/packages/core-js/proposals/array-flat-and-flat-map.js) to [beta.12](https://github.com/zloirock/core-js/blob/v3.0.0-beta.11/packages/core-js/proposals/array-flat-and-flat-map.js), the `array-flat-and-flat-map.js` has moved?

**How to reproduce the issue:**

I think running any app with `apollo-server-lambda` v2.3.3 should do it.

**Versions**

`apollo-env 0.3.0`

**Comment by timothyis** [comment]
Thanks for submitting this issue @mtmckenna, I was about to do the same.

We have an example of deploying `apollo-server` with ZEIT Now and the pinning issue caused our example – which also allows users to initialize projects from – to break and make our CI fail.

I highly suggest pinning a specific version (no `^`) when using beta versions to avoid unnecessary breakage.

I had to install and pin a specific `core-js` version to fix this: https://github.com/zeit/now-examples/commit/2583cd773b6e6e04f827c1d899689ef913e237ad

**Comment by timothyis** [comment]
Looks like a PR was submitted! #961

**Comment by gae123** [comment]
CI stopped working suddenly here with this error some time on Friday midday PST .. very serious!!! We are using apollo graphql which I guess depends on this, but I thought we had all our versions locked in package.json, need to understand better why we were impacted....

**Comment by JakeDawkins** [comment]
Thanks for jumping on this so quickly! We've pinned the core-js dep and rereleased. Fixes should be in `apollo-env@0.3.1`

**Comment by zamiang** [comment]
I believe apollo server express (and likely other apollo-server-x) need to be updated as part of this fix - the dep chain looks like so and as such, I can't update to `apollo-env@0.3.1`

```
apollo-server-express@2.3.3
  └─┬ apollo-server-core@2.3.3
    └─┬ @apollographql/apollo-tools@0.3.0
      └── apollo-env@0.3.0
```

**Comment by nodegin** [comment]
Actually I forced to use `"apollo-server-express": "2.2.2"`

I cannot believe that old version is hitting this bug, WTF?

**Comment by trevor-scheer** [comment]
@nodegin can you please clarify? Did pinning to version `2.2.2` _fix_ the problem? Or was it broken because you already had it pinned to that version? Going to try to reproduce to confirm while I wait to hear from you.

**Comment by abernix** [comment]
For anyone who is still running into this bug, if an `apollo-server-*` package was installed prior to the above fix, the version of `core-js` with the breaking change is likely baked into the project's `package-lock.json` or `yarn.lock` as a transitive dependency, as that is what these files intend to do: Achieve reproducible installs regardless of any new transitive dependency which might fulfill semver desires but inadvertently break a build.

You can inspect the lock files manually to see if that is the case (e.g. search for `core-js@3.0.0-beta`), but running `npm install apollo-server-express@2.3.3` (or `yarn add apollo-server-express@2.3.3`) again should cause the package manager to update the transitive dependency resolution in the lock-file.

**Comment by mschipperheyn** [comment]
I still have this issue

```
apollo-env@0.4.0
│  └─ core-js@3.0.0-beta.13
├─ babel-polyfill@6.23.0
│  └─ core-js@2.6.5
├─ babel-register@6.26.0
│  └─ core-js@2.6.5
├─ babel-runtime@6.26.0
│  └─ core-js@2.6.5
├─ core-js-compat@3.0.0
│  └─ core-js@3.0.0
├─ create-react-class@15.6.3
│  └─ core-js@1.2.7
├─ create-react-context@0.2.2
│  └─ core-js@1.2.7
├─ fnb@0.0.1
│  └─ core-js@2.6.5
├─ react-addons-create-fragment@15.6.2
│  └─ core-js@1.2.7
├─ react-addons-perf@15.4.2
│  └─ core-js@1.2.7
├─ react-addons-pure-render-mixin@15.6.2
│  └─ core-js@1.2.7
├─ react-addons-update@15.6.2
│  └─ core-js@1.2.7
├─ react-native-mock@0.3.1
│  └─ core-js@1.2.7
├─ react-native-web@0.11.2
│  └─ core-js@2.6.5
├─ react-swipeable-views-utils@0.12.18
│  └─ core-js@1.2.7
├─ recompose@0.30.0
│  └─ core-js@1.2.7
└─ social@0.0.1
   ├─ @babel/register@7.4.0
   │  └─ core-js@3.0.0
   ├─ babel-register@6.26.0
   │  └─ core-js@2.6.5
   ├─ babel-runtime@6.26.0
   │  └─ core-js@2.6.5
   ├─ core-js-compat@3.0.0
   │  └─ core-js@3.0.0
   ├─ core-js@2.6.4

```

My installation installs core-js 2.6.5. This is one hell of a rabbit hole with `"babel-core": "7.0.0-bridge.0",`. I'm surprised I haven't run into this more often

**Comment by trevor-scheer** [comment]
@mschipperheyn I don't quite follow, re: `"babel-core": "7.0.0-bridge.0"`

This much looks correct to me:
```
apollo-env@0.4.0
│  └─ core-js@3.0.0-beta.13
```
Could you paste the error or share some more info? A reproduction would be great if you're able to provide one.

**Comment by stevez86** [comment]
Has anyone found a fix for this? I'm running into this issue.

```
./node_modules/apollo-env/lib/polyfills/array.js
Module not found: Can't resolve 'core-js/features/array/flat' in
```

my yarn.lock is showing apollo-env@0.5.1 which depends on core-js@^3.0.1. 

Going through my yarn file I notice there are serveral dependencies on core-js ranging from 1 to 3.

```
├─ apollo-env@0.5.1
│  ├─ core-js@^3.0.1
│  ├─ core-js@3.2.1
│  ├─ node-fetch@^2.2.0
│  └─ sha.js@^2.4.11
```

Here are all the various 'Can't resolve' files when I build my next.js project some of which are not caused by the apollo-env package, like the one above. Should I be looking at fixing this through babel? 

```
core-js/modules/es.array.concat
core-js/features/array/flat
core-js/library/fn/array/from
```

**Comment by eternalmatt** [comment]
For me, I had core-js as a root dependency, and it seemed apollo-env was using that rather than the local one.  I solved this with `npm i core-js@3`
bad:
```
| `-- apollo-server-core@2.9.7
|   `-- @apollographql/apollo-tools@0.4.0
|     `-- apollo-env@0.5.1
|       `-- core-js@3.3.6
+-- core-js@2.3.0
```
good:
```
| `-- apollo-server-core@2.9.7
|   `-- @apollographql/apollo-tools@0.4.0
|     `-- apollo-env@0.5.1
|       `-- core-js@3.3.6
+-- core-js@3.3.6
```
